### ISSUE TITLE
Anzeigen von berechneten Werten in MutableUI

### ISSUE THREAD

**Issue by AkikoOsaka** [JirkaDellOro/FUDGE#103]
Wenn ein Mutator einem Wert enhält, der beim Erzeugen des Mutator berechnet wurde, kommt es bei der Generierung der FoldableFieldsets für MutableUI Elemente zu einem Problem.
Die sind besonders wichtig für ViewData.
Bei der Generierung wird rekursiv durch alle Verschachtelungsebenen des übergeben Mutators gearbeitet. Hierfür wird jedesmal wenn ein Wert in einem Mutator als Typ "Object" desegniert ist das zugehörige Attribut des Mutables als eigenes "Sub-Mutable" interpretiert. Mit diesem Sub-Mutable wird ein weiteres Fieldset angelegt, ein Mutator des Sub-Mutables geholt und der Prozess geht eine Verschachtelungsebene tiefer.
Wenn der Wert allerdings errechnet wurde (z.B. im Fall von Transforms, wessen Werte aus einer Matrix errechnet werden), gibt es keine direkte Relation zum Mutable. 
Es wurde probiert ob man den Wert des Mutators als Mutable interpretieren kann, allerdings ohne Erfolg.
Code Snippet zeigt wie SubMutables erzeugt werden. (UserInterface/Source/UIGenerator/UIGenerator.ts Zeile 43ff)
```
case "Object":
   let subMutable: ƒ.Mutable;
                            
if ((<ƒ.General>_mutable)[key])
   subMutable = (<ƒ.General>_mutable)[key];
else
    subMutable = <ƒ.Mutable>_mutator[key];

UIGenerator.createFromMutable(subMutable, _parent, key);
```

**Comment by JirkaDellOro** [comment]
getMutatorTypes gibt jetzt sehr viel genauer Auskunft über die Typen, aus denen die Mutatordaten gehören! Bislang gab es nur die Typenbezeichnungen "boolean", "string", "number" und "Object", oder die Typenbezeichnung selbst ist ein Objekt, dann entstammen die Daten einem Enum.

Jetzt fällt die Typenbezeichnung "Object" weg und wird ersetzt durch durch den Namen des tatsächlichen Typs. Siehe im Screenshot "Matrix4x4", "Vector3" und "Color"
![Anmerkung 2019-09-19 231134](https://user-images.githubusercontent.com/6279994/65282219-a84e5900-db34-11e9-960a-7301612bcbc2.png)

**Comment by JirkaDellOro** [comment]
Der Screenshot stammt von https://github.com/JirkaDellOro/FUDGE/tree/master/Test/Transfer/MutatorTypes

**Comment by JirkaDellOro** [comment]
Folgendes gilt weiterhin:
- der Mutator liefert alle ausgewählten Daten über die Objekthierarchie hinweg
- getMutatorTypes liefert nur die Typen auf der ersten Ebene des Objektes, auf welchem sie ausgeführt wird.

Folgt man also der Verschachtelung in die Hierarchie, so muss man sich auf jeder Ebene die Typen von dem jeweiligen Kindobjekt geben lassen, wenn man sie braucht (derzeit nur das UI). Die Werte selbst aber holt man aus dem Mutator, denn dort liegen schon alle vor. Auf keinen Fall sollte man sich bei der Rekursion immer wieder neu den Mutator zusammenfummeln lassen, den HACK sollten wir nun abräumen!

**Comment by JirkaDellOro** [comment]
Commit:  9b8e66905d36f51b67ab67cae6d76d1722b35ae4

**Comment by JirkaDellOro** [comment]
Sind wir hier fertig?

**Comment by AkikoOsaka** [comment]
Ja, Ich glaube wir sind hier fertig.
Danke für die Errinerung
