### ISSUE TITLE
"Container is null"

### ISSUE THREAD

**Issue by AkikoOsaka** [JirkaDellOro/FUDGE#116]
Nachdem Ich jetzt den Fix implementiert habe damit der Viewport und die Kamera wieder zusammen spielen im Editor, ist mir ein Fehler in der ViewCamera entgegengesprungen.
Beim automatischen generieren des UserInterfaces aus dem Mutator der ComponentCamera wurde mir immer eine Exception entgegengeworfen, da das Attribut "Container" = null ist.
Ich hab grad in der Doku nachgeschaut und Container referenziert auf den Knoten an dem die Kamera hängt, Natürich hat jetzt aber mit unserem neuen Setup die Editorkamera keinen Knoten mehr.
Als Workaround hab ich jetzt einfach alle Attribute die null sind nicht bauen lassen vom UIGenerator.
So kommt es zumindest zu keinen Fehlern wenn eine Eigenschaft leer ist. 
Gibt es dass Ich sonst mit dieser Info anfangen sollte?

**Comment by JirkaDellOro** [comment]
Ich glaube, wir sollten der Camera verbieten den Container an den Mutator zu liefern. Der darf nicht mutiert werden!

**Comment by AkikoOsaka** [comment]
Mir wär auch kein guter Usecase für eingefallen den Container zu mutieren.

**Comment by JirkaDellOro** [comment]
Das darf auch keine andere Component liefern, da es das System in einen instabilen Zustand bringen könnte, wenn man einfach die Beziehung zum Knoten mutiert...
