### ISSUE TITLE
Flat Shading - Flickering

### ISSUE THREAD

**Issue by SimonStorlSchulke** [JirkaDellOro/FUDGE#120]
Flat Shading verursacht starkes Flickering - [siehe Video](https://youtu.be/_EEkUSHL-qw), während Smooth Shading butterweich läuft. Da das Problem auch in der [Light Testszene](https://jirkadelloro.github.io/FUDGE/Test/Shading/Light/Light.html) auftritt, glaube ich nicht dass es an meinem Code liegt - [hier](https://github.com/hs-furtwangen/FUDGE-Chemistry_MasterW19/blob/master/dev/tests/MatCap/lib/MatCap.ts) trotzdem der Problemshader.

Das Problem tritt in Firefox und Chrome auf.

**System Information**
Operating system: Windows-10-10.0.17763 64 Bits
Graphics card: GeForce GTX 1080/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 416.34

**Comment by JirkaDellOro** [comment]
Kein Flickering bei mir...

**Comment by JirkaDellOro** [comment]
PS: Geiler Shader!

**Comment by JirkaDellOro** [comment]
Ist das noch aktuell, @SimonStorlSchulke ?

**Comment by SimonStorlSchulke** [comment]
Ich bin gerade im Urlaub ohne den PC auf dem es auftraf. Ich überprüfe es bei nächster Gelegenheit.
