### ISSUE TITLE
UIGenerator createFromMutable

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#124]
Ich glaube, es würde mir besser gefallen, wenn ich der Methode nicht zwingend ein Parent-Element übergeben muss, sondern sie mir zurück gibt, was sie gebastelt hat und ich kann mir dann aussuchen, was ich damit mache. 

@AkikoOsaka : siehst Du darin ein Problem?

**Comment by AkikoOsaka** [comment]
Ich würde dann das Parent Objekt optional machen, und dann an das Parent Element hinzufügen falls es vorhanden ist, ansonsten ein neues schaffen.
In jeden fall wird das Parent Element zurückgegeben.
Klingt das gut für dich?

**Comment by JirkaDellOro** [comment]
Wenn ich mir den Code so anschaue, hast Du das Schema an vielen Stellen durchgezogen. Die Methoden heißen abstrahiert createSomething(...), müssten aber, so wie sie implementiert sind, createSomethingAndAppendToParent(...) heißen. Du solltest grundsätzlich das "Parenting" der aufrufenden Funktion überlassen, also einfach eine Abstraktionsebene höher schieben.

Erscheint das problematisch? Deine Rekursionen sollten immer noch funktionieren können.

**Comment by AkikoOsaka** [comment]
Ne hast eigentlich recht. 
Sollte relativ unproblematisch sein das rauszurationalisieren

**Comment by JirkaDellOro** [comment]
Kann das weg?

**Comment by JirkaDellOro** [comment]
??????????????????
