### ISSUE TITLE
Bild für Matrix4x4

### ISSUE THREAD

**Issue by Hexadezimal** [JirkaDellOro/FUDGE#125]
In der Dokumentation von FUDGECore sollte noch ein Bild für Matrix4x4 eingefügt werden.

**Comment by JirkaDellOro** [comment]
Das Bild gab es, ich habe nur dummerweise noch etwas zwischen es und die Klassendefinition geschrieben, wodurch es nicht mehr zugeordnet wurde. 

Dafür hübsche ich es jetzt noch etwas auf...
