### ISSUE TITLE
Vector2

### ISSUE THREAD

**Issue by Hexadezimal** [JirkaDellOro/FUDGE#127]
Möglichkeit der Translation etc. von Vector2

**Comment by JirkaDellOro** [comment]
Vector.ONE einbauen

**Comment by Plagiatus** [comment]
Translation etc.?
Was denn noch so? Rotation? 

Und wenn ich so darüber nachdenke, macht Translation eines Vektors keinen Sinn, weil der Vektor immernoch der selbe ist, nur mit einem anderen Startpunkt, was aber ja den Vektor nicht verändert?

**Comment by Hexadezimal** [comment]
Ich habe ausversehen eine falsche Beschreibung geschrieben, als ich das Issue während PRIMA erstellt habe. Es soll ein Vector.ONE eingebaut werden und keine Translation.

**Comment by JirkaDellOro** [comment]
Warum closed?

**Comment by Plagiatus** [comment]
Weil ich eine Vector2.ONE() Funktion auf den Dev branch gepusht habe und damit das issue erledigt habe?

**Comment by JirkaDellOro** [comment]
Hab' s gesehen...

**Comment by JirkaDellOro** [comment]
Habe es jetzt noch um _scale erweitert, damit es mit Vector3 übereinstimmt. Dabei fiel mir auf, dass dies auch mit UP, RIGHT etc. gemacht werden sollte und die Methoden auch nicht UP, RIGHT sondern Y, X heißen sollten. Siehe Vector3

magst Du das machen? Vielleicht hat es Effekte auf Animation?

**Comment by Plagiatus** [comment]
Nein, sollte keine Auswirkungen haben, eher auf den Vektoreditor.
Und ja, kann ich schnell machen.

**Comment by Plagiatus** [comment]
Das umbenennen in X und Y bedeutet allerdings, dass es nicht mehr als `get` deklariert werden kann. Finde ich ein bisschen schade, aber ist bei Vector3 ja auch nicht so. Schon wieder mehr konsistenz, yay.
