### ISSUE TITLE
Refactor Lights

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#129]
Ich hatte mir den Punkt in meinen Projektplan eingetragen. 

1. Es geht darum, dass derzeit die Lichter, wie Meshes, Coats, Materials etc., Ressourcen sind, die mit Hilfe einer ComponentLight an einen Node gebunden werden können. 

2. Die Alternative wäre, sie wie derzeit die Kamera, nicht als Ressourcen zu definieren, sondern nur als Parametrierung der ComponentLight. Will man dann das gleiche Licht an anderer Stelle wieder verwenden, muss man einen Knoten, an dem die Componente hängt zunächst als Ressource definieren und dann diese Knotenressource als Kind an den Zielknoten binden. Das erscheint umständlicher, ist aber das Verfahren das bei Unity genutzt wird.

Wenn ich gerade so gummientenhaft darüber fabuliere, erscheint mir Version 1 als die bessere, den Version 2 kann ich auch damit immer noch abbilden. Der Unterschied wäre lediglich, dass Lichter als Ressourcen zur Wiederverwendung einzeln im Projekt auftauchen. Damit sehe ich aber auch sofort, welche Lichttypen überhaupt im Projekt definiert sind.

Allerdings sollen Lichter auch z.B. flackern können und zwar unabhängig voneinander. Damit ist klar, dass die Componenten nicht lediglich Referenzen auf die eine Lichtressource nutzen dürfen, sondern  auf einzelne Instanzen. Die braucht es schließlich auch zum Rendern. Damit ist Version 2 eigentlich die richtige...

Beiträge zur Entscheidungsfindung sind willkommen...

**Comment by Plagiatus** [comment]
Also, Lichter müssen am Ende ja alle als Einzelinstanz zur Laufzeit existieren, korrekt?

Grundsätzlich finde ich es nicht schlecht, wenn man Licht-Konfigurationen wiederverwenden kann, am besten so direkt und umstandslos wie möglich. Allerdings sehe ich auch die Problematik mit dem unabhängigen flackern.

In diesem Zusammenhang fände ich von den beiden gegebenen Optionen die 2. am besten. Was ich aber vllt sogar noch besser fände, wäre eine "Konfiguration" zu speichern. Aber das ist ja letztendlich genau die Version 2.

**Comment by JirkaDellOro** [comment]
Es ist jetzt eher 2. geworden, allerdings kann man, wenn man möchte es so wie 1. betreiben. Jedenfalls müssen Lichter nicht zunächst als Ressourcen abgelegt sein, sondern können mit der ComponentLight (zusammen und ggf. auch von ihr) erzeugt und bei Bedarf nur von ihr referenziert werden. Man kann aber auch ein Licht erzeugen und einer Komponente bei deren Konstruktion anheften.
