### ISSUE TITLE
Build Probleme

### ISSUE THREAD

**Issue by TDorner** [JirkaDellOro/FUDGE#132]
Ich habe versucht Fudge neu zu bilden, allerdings bekommen ich etwa 60~ Fehler die alle mit dem WebGL2RenderingContext zusammenhängen. Das Problem dabei ist, dass ich auf die Definitionen zugreifen und einsehen kann, aber diese nicht verwendet werden. 
Keine der Dateien in denen die Fehler auftauchen sind von mir verändert worden (nur im Mesh, RenderManager, RenderOperator treten die Fehler auf).
Ideen für einen Fix? Bin mir gerade unsicher an was es liegen kann.

**Comment by JirkaDellOro** [comment]
Wenn Du einen Klon des Repositories gemacht hast, lasse in der obersten Verzeichnisebene "npm install" laufen. Dann sollten alle Module und Definitionen installiert werden. Melde dich, wenn es dann immer noch Probleme gibt. Derzeit scheint es auch die Standard-WebGL-Definition-Datei nicht auf dem aktuellen Stand zu sein, aber 60+ Fehler erscheinen mir zu viel.

**Comment by TDorner** [comment]
Danke hat gepasst, hatte nicht mehr daran gedacht den npm install neu laufen zu lassen.
