### ISSUE TITLE
AudioListener

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#134]
FUDGE kompiliert nicht mehr, es scheint mit dem letzten PullRequest von Thomas zusammen zu hängen. AudioListener gibt es sowohl in FUDGE als auch in der WebGL-Lib, so scheint es, vielleicht ist das ein Hinweis. Dringend fixen!

**Comment by JirkaDellOro** [comment]
Habe einen Quick-Fix gebaut, indem ich deine Klasse, Thomas, in AudioListenerX umbenannt habe... soll aber so sicher nicht sein.

**Comment by TDorner** [comment]
Komisch, hatte bisher mit WebGL noch keine Konflikte. Setz mich dran..

**Comment by JirkaDellOro** [comment]
Erkenntnisse?

**Comment by TDorner** [comment]
Die Datei ist eine alte unbenutzte Klasse, die mir fälschlicherweise mit reingerutscht ist - kann gelöscht werden.

**Comment by JirkaDellOro** [comment]
Welche Datei?

**Comment by TDorner** [comment]
Core/Source/Audio/AudioListener.ts bzw AudioListenerX also die umbenannte Datei. Will sie nicht selber löschen ohne dann auch gleich neu zu builden.

**Comment by JirkaDellOro** [comment]
Ok, dann weiß ich bescheid. Aber bevor ich das mache: derzeit höre ich bei den Tests nichts. Kannst Du das bitte zuerst überprüfen?

**Comment by JirkaDellOro** [comment]
Ich habe das File gelöscht und in deine AudioTestOne eine Bremse eingebaut, so dass erst Nutzerinteraktion erforderlich ist, wie es für die Browser vorgesehen ist. Leider höre ich weiter nichts, es wäre sehr wichtig, dass DU das untersuchst, denn es bremst gerade das Projekt aus!
