### ISSUE TITLE
MeshCube

### ISSUE THREAD

**Issue by Joscha97** [JirkaDellOro/FUDGE#135]
Die faceNormals im MeshCube sind teilweise sinnlos deklariert. 
Zum Beispiel faceNormal /*3*/ im MeshCube.ts

**Comment by JirkaDellOro** [comment]
Nein, ist doch alles korrekt. Die Faces sind folgendermaßen definiert
                // First wrap
                // front
                1, 2, 0, 2, 3, 0, 
                // right
                2, 6, 3, 6, 7, 3,
                // back
                6, 5, 7, 5, 4, 7,

                // Second wrap
                // left
                5 + 8, 1 + 8, 4 + 8, 1 + 8, 0 + 8, 4 + 8,
                // top
                4 + 8, 0 + 8, 3 + 8, 7 + 8, 4 + 8, 3 + 8,
                // bottom
                5 + 8, 6 + 8, 1 + 8, 6 + 8, 2 + 8, 1 + 8

Die Face-Normal wird angegeben jeweils am letzte Vertex eines Trigons, respektive also an jedem dritten Vertex in der obigen Liste. Das sind die Vertices 0, 3, 7, 12, 11 und 9. Genau für diese sind die Normalen abgelegt.
