### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#137]
Du hast einen Tab von zwei Spaces in deinem Code. Hatten wir das so festgelegt oder war das nur deine persönliche Präferenz? Im Wiki konnte ich dazu nix finden.

**Comment by Plagiatus** [comment]
Ich habe es bei mir auf 2 Leerzeichen gesetzt, weil das in deinem Code so war und weil du das im tslint so festgelegt hast (und mir vscode sonst dauernd auf die Nerven gegangen ist):

https://github.com/JirkaDellOro/FUDGE/blob/development/Core/Source/tslint.json#L10

Ich glaube allerdings, dass sich die tslint Spezifikation geändert hat, so dass das evtl nicht mehr richtig hervorgehoben wird.

**Comment by JirkaDellOro** [comment]
Potzbiltz, tatsächlich. Bei mir wird aber nix gemotzt und der AutoFormatter setzt es auf 4. Zwei finde ich aber wirklich schöner...

**Comment by Plagiatus** [comment]
Ja, ich habe mich inzwischen auch schon an 2 gewöhnt, obwohl ich ja ursprünglich ein Verfechter von 4 war. 😉
https://stackoverflow.com/questions/34174207/how-to-change-indentation-in-visual-studio-code

**Comment by JirkaDellOro** [comment]
merci
