### ISSUE TITLE
Mac OSX WebGL Texture

### ISSUE THREAD

**Issue by benediktgrether** [JirkaDellOro/FUDGE#139]
Texturierung unter Mac OSX Chrome Funktioniert mit Hardware Rendering nicht. 
Software Rendering funktioniert.

Auf Firefox gab es bis jetzt keine Probleme.

**Comment by JirkaDellOro** [comment]
David zum Testen

**Comment by JirkaDellOro** [comment]
@DavidNiemann kannst Du dich erinnern, was mit dem Bug passiert ist? Er ist noch offen...

**Comment by DavidNiemann** [comment]
Wenn ich mich richtig erinnern lag das an Einstellungen von Chrome bei Mac, und die Lösung die Einstellung in Chrome zu ändern.

**Comment by benediktgrether** [comment]
Der Workaround bei Chrome auf dem Mac war das deaktivieren der Hardwarebeschleunigung (Ich glaub so heißt es, bin gerade nur am Handy). Danach werden die Sprites angezeigt.

**Comment by JirkaDellOro** [comment]
Hallo Benedikt, vielen Dank
