### ISSUE TITLE
Problem mit Debug.log

### ISSUE THREAD

**Issue by LukasBrauschHFU** [JirkaDellOro/FUDGE#142]
Sobald Debug.log einmal aufgerufen wurde, erstellt die Konsole keine weiteren Einträge mehr, egal, ob danach Debug.log oder Debug.alert aufgerufen werden. 

Um dies zu testen muss ƒ.Debug.log aufgerufen werden und mit Werten versehen werden wie zum Beispiel "ƒ.Debug.log("Log |  Console+Alert | 1 Object: ", test);". Sobald dies oder eine ähnlicher Befehl hiernach aufgerufen wird, kann man diesen Fehler beobachten. Die einzige Außnahme bietet hier Debug.Info, bei dem die Konsole immer noch wie gewohnt funktioniert.

**Comment by JirkaDellOro** [comment]
Bislang noch nicht reproduzierbar mit meinem Testcode. Bitte genauer untersuchen

**Comment by JirkaDellOro** [comment]
War ein Furz
