### ISSUE TITLE
Namensgebung

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#148]
Zu diskutieren:

addChild, appendChild, attachChild...
addComponent, appendComponent, attachComponent

**Comment by Plagiatus** [comment]
"append" klingt für mich allgemein nach "in eine Liste hinten hinzufügen".

"attach" ist für mich "etwas anheften".

"add" ist das generische "hinzufügen".

Bei der Componente würde ich sowohl attach als auch add bevorzugen, da einem Node eine Komponente ja angefügt wird, was ihm dann neue Eigenschaften gibt.  
Bei dem Child würde ich add oder append nehmen, je nach dem ob die Kinder nach außen offensichtlich in einer Liste gespeichert werden.

So. Das ist jetzt aber nicht einheitlich. Wenn es um noch mehr Dinge geht, bei denen diese Namensgebung wichtig ist, und sie einheitlich sein sollte, würde ich das algemeinste nehmen: "add"

**Comment by JirkaDellOro** [comment]
Schön, dass Du einsteigst. Ich sehe auch die beiden gegensätzlichen Richtungen: `attachComponent`/`appendChild` vs `addComponent`/`addChild`.

Components und Children haben sehr unterschiedliche Bedeutung und Wirkung, die durch die unterschiedliche Bezeichnung der Aktionen unterstrichen wird. Andererseits handelt es sich in beiden Fällen schlicht um Aggregation, ein `add` passt also sicher. Zudem gibt es `addEventListener`. Außerdem habe ich derzeit bei allen dreien `remove...` zum Entfernen, das müsste dann auch konsequenterweise `detach` sein bzw. ein Antonym für `append`, das aber gar nicht existiert.

Während ich das schreibe wächst die Überzeugung, dass `add` für alles der bessere Weg ist. Dann kann ich beim Coden auch einfach mal `add` schreiben uns sehen, was alles aggregiert werden kann.

Weitere Meinungen sind willkommen...

**Comment by Plagiatus** [comment]
ein antonym für append könnte "pop" sein, zumindest wird das in der Programmierung gerne als "das letzte Element in einer Liste entfernen (und zurückgeben)" verwendet, was das Gegenteil von "dieses Element als letztes an die Liste anhängen", append oder auch push genannt, ist.

Ja, das `irgendwas.add` und dann die IDE Vorschläge machen lassen hatte ich auch im Kopf als ich gesagt habe, dass es nicht einheitlich wäre.

**Comment by JirkaDellOro** [comment]
Hmmm... jetzt ist mir wieder eingefallen, warum ich das überhaupt appendChild genannt hatte. Das ist Standard-DOM-Jargon.

**Comment by JirkaDellOro** [comment]
Aaalso, es heißt jetzt addChild, aber es gibt noch eine Referenz-Property auf diese Funktion mit dem Namen appendChild für die DOM-Jünger
