### ISSUE TITLE
Coding Style beachten

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#158]
@SimonStorlSchulke : siehe Wiki
z.B.
- Anführender Unterstrich kennzeichnet formale Parameter
- Alles ist explizit zu typisieren
- Getter und Setter nur verwenden, wenn sie auch eine Funktion haben, die über die eines öffentlichen Attributs hinaus gehen

**Comment by SimonStorlSchulke** [comment]
Alles klar! Ich werde in Zukunft genauer darauf achten.

**Comment by JirkaDellOro** [comment]
Hast Du TSLint installiert? https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin

Ich habe die Konfiguration tslint.json im FUDGE-Projekt ziemlich streng eingestellt, der Linter sollte da ziemlich mit drauf achten.
