### ISSUE TITLE
Menubuttons Position im Editor

### ISSUE THREAD

**Issue by AkikoOsaka** [JirkaDellOro/FUDGE#162]
Die Buttons für das Hinzufügen für Knoten und Komponenten sollten nicht unten an der View hängen. 
Es muss ein passender Platz gefunden werden und entsprechend müssen die dazugehörigen Menüs auch einen besseren Platz finden.

**Comment by JirkaDellOro** [comment]
Geht nun über Rechtsklick-Kontextmenü
