### ISSUE TITLE
View Ressource

### ISSUE THREAD

**Issue by AkikoOsaka** [JirkaDellOro/FUDGE#166]
Der Editor benötigt eine Ressource View, welche die Projektordnerstruktur darstellt. Ebenfalls muss es möglich sein, Ressourcen zu speichern und diese dann an Knoten anzuheften (Meshes, Texturen, etc.)

**Comment by JirkaDellOro** [comment]
Hierfür gibt es in FUDGE bereits die Klasse SerializableRessource. Subklassen hiervon stellen Ressourcen dar, die entsprechende behandelt werden sollen. Dazu bedarf es im Editor einer entsprechenden Verwaltung, der Objekte dieser Subklassen managed, wenn der Nutzer sie zusammenklickt. Für per Code erschaffene ist er selbst verantwortlich.

**Comment by JirkaDellOro** [comment]
Im UI muss es zunächst die Möglichkeit geben Ressourcen zu erzeugen wie

- Create Mesh
- Create Material
- Create Node Resource (Prefab)

Was dabei zustande kommt, muss entsprechend visualisiert und zur Weiterverwendung/-bearbeitung zur Verfügung gestellt werden.

**Comment by JirkaDellOro** [comment]
Außer 
https://github.com/JirkaDellOro/FUDGE/issues/166#issuecomment-592922514

bitte beachten, dass es auch einen ResourceManager in Fudge gibt, der die Ressourcen sammelt und bereitstellt. Wahrscheinlich muss dessen Inhalt dargestellt werden.
