### ISSUE TITLE
Viewport und Camera Controls

### ISSUE THREAD

**Issue by AkikoOsaka** [JirkaDellOro/FUDGE#167]
Die Viewport Kamera sollte über Maus und Tastatur kontrolierbar sein. 
Hierfür werden auch Gizmos benötigt. 
Darüber hinaus wird auch "Picking" benötigt, um unter anderem Gizmos interaktiv werden und Knoten in der Szene ausgewählt werden können.

**Comment by JirkaDellOro** [comment]
In erster Version jetzt nutzbar
