### ISSUE TITLE
Editor Themes

### ISSUE THREAD

**Issue by AkikoOsaka** [JirkaDellOro/FUDGE#168]
Die Struktur der Editorthemes sollte überarbeitet werden.
Themes sollten einheitlich sein und leicht erstellbar. Hierfür sind Styleguides und Templates von nöten. 
Themes sollten möglicherweise jeweils in ihre eigenen Ordner gepackt werden (DarkTheme, LightTheme, etc). 
Für die einfache Benutzung, Anpassung und Erstellung von Themes ist es vielleicht von Vorteil, Farben und ähnliches auszulagern in Variablen (falls möglich im CSS).

**Comment by JirkaDellOro** [comment]
siehe 
https://codepen.io/thebabydino/pen/WbwJyg

Man kann sogar Berechnungen in CSS anstellen. Damit sollte alles leicht auf ein exzellent zu verwaltendes Minimum zusammenschrumpeln können.

Ich habe auch das Base.css von GoldenLayout heruntergeladen und Editor/HTML gesteckt. Es ist dumm, hier auf eine Online-Verbindung angewiesen zu sein.
