### ISSUE TITLE
Sammlung von Meshes, Componenten, Shader etc zur Auswahl

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#170]
Wir jetzt automatisch im FudgeCore erzeugt und kann bei der entsprechenden Superklasse abgeholt werden. Siehe

Test/Resources/SubclassRegistration/Test.html

Mit diesen Listen sind nun Aktionen wie "AddComponent", "CreateMesh" oder "SelectShader" im UserInterface zu füttern.

**Comment by JirkaDellOro** [comment]
Ist das angekommen?

**Comment by AkikoOsaka** [comment]
Ist angekommen
