### ISSUE TITLE
Normalenbehandlung in MatCap Shader

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#172]
Da steht
```glsl

                        mat4 normalMatrix = transpose(inverse(u_projection));
                        vec4 p = vec4(a_position, 1.0);
                        vec4 normal4 = vec4(a_normal, 1.0);
                        vec3 e = normalize( vec3( u_projection * p ) );
                        vec3 n = normalize( vec3(normalMatrix * normal4) );

                        vec3 r = reflect( e, n );
```

Mir ist nicht klar, wie die Normalenbehandlung hier gedacht ist. Im FlatShader schicke ich die Normalen durch die Welt-Matrix um sie dann mit der Beleuchtung zu verrechnen. Wie ist das hier? Ich bitte um kurze Erläuterung.

**Comment by JirkaDellOro** [comment]
... und wo kriegt der überhaupt die Normalen her?

**Comment by JirkaDellOro** [comment]
Ich habe den RenderManager umgebaut und auch die Shader überarbeitet. Der MatCap-Shader bekommt jetzt die Normalen, das war vorher nicht so. Allerdings scheint er damit nicht gut umgehen zu können, dass solltest Du nun anpassen/fixen...

**Comment by SimonStorlSchulke** [comment]
Sorry für die Verspätung, habs gefixed.
