### ISSUE TITLE
MeshComponent Mutator gibt Mesh nicht mit

### ISSUE THREAD

**Issue by AkikoOsaka** [JirkaDellOro/FUDGE#174]

**Comment by JirkaDellOro** [comment]
Okay. Interessant ist, dass
- wenn kein Mesh referenziert ist, im Mutator und in MutatorTypes der Eintrag `mesh` vorhanden ist, der Wert is null
- wenn ein Mesh referenziert ist, der Eintrag fehlt.

Das ist auch logisch, denn Objekte, die nicht Mutable sind, werden entfernt. Jetzt muss ich mir überlegen, wie wir mit Ressourcen dabei umgehen....

**Comment by JirkaDellOro** [comment]
Bitte dringend übrigens meine Ausführungen in #166 beachten!

**Comment by JirkaDellOro** [comment]
So, ich habe eine Unterstützung eingebaut. Dabei ist mir aufgefallen, dass in UserInterface noch die falsche getMutator-Methode genutzt wird, siehe #175. Das muss zuerst behoben werden.

ComponentMesh manipuliert jetzt im MutatorForUserInterface das Attribut `mesh` folgendermaßen
- wenn kein Mesh referenziert ist, steht im Mutator ein Verweis auf die Klasse `Mesh` und in MutatorTypes der Name der abstrakten Klasse, also "Mesh". 
- wenn ein Mesh referenziert ist, verweist `mesh` auf diese Instanz und in MutatorTypes der Name der konkreten Klasse, z.B. "MeshQuad"

Stellt man also fest, dass unter mesh keine Instanz sondern eine Klasse bzw Funktion referenziert ist, kann man diese nutzen um die richtigen Ressourcen zu finden und dem Nutzer eine Auswahl zu präsentieren. 

Hier ist bereits ein Test für die entsprechende Funktionalität
FUDGE/Test/Transfer/Mutator/Test.html


Ich bin noch nicht sicher, ob das alles so richtig gut ist und habe Ideen für Verbesserungen. Aber wir schauen mal, wie weit wir damit kommen.

**Comment by JirkaDellOro** [comment]
Eine Sache habe ich jetzt doch schon eingebaut, ich denke, dass wir das brauchen werden. Von den subclasses kann man jetzt direkt zu deren baseClass navigieren, ohne die Prototypenkette durchsuchen zu müssen. Hat man also ein Objekt kann man das Attribut "baseClass" dessen Contructors erfragen, auch über mehrere Hierarchiestufen hinweg. Somit kann man dann aus bestehenden Ressourcen weitere mit der gleichen Basisklasse heraussuchen, die es ersetzen könnten.

Beispiele finden sich im oben bereits angegebenen Test und in 
FUDGE/Test/Resources/SubclassRegistration/Test.html
