### ISSUE TITLE
Render-Events

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#185]
Ich überlege gerade, z.B. für eine Billboard-Funktion, welche Objekte in Richtung Kamera dreht, ein Render-Event einzuführen.

So etwas könnte man vielleich auch für anderes gebrauchen, z.B. die Inklusion der Physik-Transformationen oder ähnliches. Bitte postet mal hier Ideen dazu, wenn welche kommen. Ich könnte mir beispielsweise folgende Events vorstellen:
- wenn ein Viewport ein draw aufruft oder der draw fertig ist
- wenn ein Graph durchkalkuliert wird oder wurde
- wenn die Welttransformation eines Knotens berechnet wird
- wenn ein Knoten gerendert wird oder wurde

Da es natürlich Zeit kostet, zur Laufzeit prüfen, ob ein Objekt ein solches Event abfangen möchte, könnte es an manchen Stellen performancerelevant werden, weshalb ich die Anwendungsfälle abschätzen möchte.

**Comment by Dev-MarkoF** [comment]
Wie ich das sehe würde ich für eine komplette Entkoppelung der momentanen Physik, eine Event Struktur im Rendering benötigen bzw. auch für die Zukunft weiterbringend finden.

Wichtig wäre eine Event Struktur, die Daten nicht nur übergibt sondern einen Zugang ermöglicht diese auch verändert wieder in den Ablauf einzuspeisen.

Ablauf:
Rendering Startet
Welttransformationen werden berechnet
       -> EventCalculatedWorldTransform Node
       -> Event: CalculatedWorldTransform Branch
       <- Einspeisung von EventAntwort (bsp. Physik Transformationen, Animation Transformationen)
Lichtberechnung
Übergabe an die Renderpipeline.

Derzeit setze ich die Physik einfach ans Ende der Renderpipeline und brauche den Szenenbaum. Für eine Modularisierung muss ich nur ein Event haben, was sich zwischen Matrizen Calculation und Rendering schieben kann.

Ich sehe nur zwei Punkte an die man direkt denken muss.
Regeln / Prioritätssystem für Antworten des Events und Priorität in Kombination von Abhängigkeiten World/Local.

Bsp. Es gibt Animation, Physik und Postprocessing. Wer hat die Hoheit? Wer greift nur local/world zu.
Laut der Physik muss die immer die Hoheit bei allen statischen/dynamischen Nodes im Rendering haben und ignoriert die Local Hierarchy. 
Ich weiß nicht ob dieser Zugang mit den angedachten Events abbilden lässt. Oder ob es das ist was ich brauche.

**Comment by JirkaDellOro** [comment]
Es gibt jetzt drei neue Events

-     RENDER_PREPARE_START: wird vom Renderer gefeuert, bevor die Rekalkulation und Lichtsetzung startet. Registrieren über Render.addEventListener
-     RENDER_PREPARE_END: wird vom Renderer gefeuert, nachdem die Rekalkulation und Lichtsetzung durch ist. Registrieren über Render.addEventListener
-     RENDER_PREPARE: wird vom Renderer ausschließlich (nur target-phase) am betreffenden Knoten gefeuert, bevor dessen Rekalkulation stattfindet. Registrieren über node.addEventListener
 
Bei letztem Event kann also eine Manipulation der lokalen Transformation stattfinden. Derzeit klinkt sich ComponentAnimator hier ein um das zu tun. Wenn Physikkomponenten auch auf diesem Weg eingreifen, muss man noch die Priorität klären.

Kannst Du damit schon etwas anfangen?

**Comment by Dev-MarkoF** [comment]
Ich denke schon, ich schaue es mir mal an, wenn ich dazu komme, für die jetzige Integration sind die Events ja nicht nötig, da ich alle Zugriffe ja direkt im Core gemacht habe.
Kann man mit den Events auch das Rendering überschreiben, bzw. verhindern? Das wäre vlt. ein interessanter Gedanke. Mittels einer Flag beim Event, dafür braucht es aber vlt. auch eine Prio. 
Einsatz z.B. beim Physik Debugging, bei dem ich ja auch einen Modus habe, der mir nur Physik Objekte rendert und das normale Fudge Rendering verhindert. Kann mir das allgemein für Debug Rendering vorstellen, wenn ein neues Modul implementiert wird und das einen eigenen Debug Renderer beinhaltet, dann kann man nur die interessanten Nodes im Editor anzeigen lassen.

Halte ich jetzt nicht für unbedingt nötig, aber gerade bei der Physik fand ich den Modus jetzt praktisch. Wenn man sich mein Experiments/Phase2_Joints anschaut, da sieht man die Joint Verbindungen einfach besser und hat so ein gutes Verständnis davon, wenn man nur Wireframes der Physik Objekte hat. Kann mir das z.B. für Audio Komponenten auch gut vorstellen, für ein Wireframe des Audioradius/Abfalls.
-> Kann man auch über einen allgemeinen Debug Renderer lösen, aber ist denke einfacher, wenn das jedes Modul für sich implementiert, da Debugging von Komponenten auch kein Lighting/Shading benötigt.

**Comment by JirkaDellOro** [comment]
Ich müsste selbst erst mehr Erfahrung mit dem Physikmodul machen, um sinnvoll mitreden zu können. Leider komme ich nicht dazu. Hättest Du Nerv, uns in PRIMA einmal eine Einführung zu geben?

**Comment by Dev-MarkoF** [comment]
Klar, aber nur Code mäßig im Editor funktioniert das glaube ich noch nicht soweit. Nutzt ihr den Editor überhaupt schon in Prima?

Modularisierung ist in Fudge nicht so einfach wie angedacht, weil man für externe Module Eingriffe wirklich tief in alle Berechnungen und Vorgänge brauchen kann. Mir ist aufgefallen im Editor könnte das noch relevanter werden. Vermutlich bräuchte man da irgendwann Schnittstellen um Editor Extensions zu schreiben, die sich in das Menü trotzdem einfügen.

**Comment by JirkaDellOro** [comment]
In diesem Semester würde ich den Editor zum ersten mal nutzen wollen. Aber es muss noch nicht die Physik drüber laufen. Nächste Woche wäre der ideale Zeitpunkt für eine Einführung. PRIMA findet immer Di und Do von 16.15-17.45 Uhr statt. Passt dir das?

**Comment by Dev-MarkoF** [comment]
Ja, ist machbar. Sag mir einfach, wenn es gebraucht wird und was ihr gern wissen wollt.

**Comment by JirkaDellOro** [comment]
Dann komm doch am Dienstag um 16.15 Uhr in dm15. Wir wollen wissen, was die Physik leistet und wie wir vorgehen müssen, um sie zu implementieren. Ich denke, Du kannst deine Beispiele aus der Thesis durchgehen, aber wir sollten auch zusammen etwas kleines basteln. Gerne kannst Du schon einen Code vorbereiten, auf dem wir dafür aufbauen und nach und nach die Physik-Features implementieren.
