### ISSUE TITLE
transparente Oberflächen

### ISSUE THREAD

**Issue by plojo** [JirkaDellOro/FUDGE#186]
Transparente Flächen verhalten sich nicht so wie erwartet. Ich habe hier mal eine Beispielszene gebastelt anhand der ich meine Probleme beschreiben möchte.
![image](https://user-images.githubusercontent.com/38690628/83012520-ce10f380-a01b-11ea-8a64-ea701f7a8be6.png)
Im Bild befinden sich drei Flächen (MeshQuads) welche von vorne nach hinten die Farben Rot, Grün und Blau haben. Die mittlere Fläche hat einen gesetzten alpha-channel Wert von 0.5 sie sollte also halb durchsichtig sein. Die vordere/hintere Flächen sind undurchsichtig. Zu erwarten wäre also, dass dort wo die grüne Fläche vor der Blauen liegt sich die Farbe Cyan ergibt und dort wo Rot vor Grün liegt die Grüne überdeckt wird. Wie aber zu sehen ist verhält sich alles ganz anders. Undurchsichtige Flächen die vor durchsichtigen liegen werden durchsichtig gerendert und durchsichtige Flächen welche vor undurchsichtigen liegen werden undurchsichtig gerendert.
Ich habe meinen Beispielcode mal hochgeladen: [Beispiel](https://github.com/JirkaDellOro/FUDGE/tree/development/Miscellaneous/Experiments/Jonas/Transparence)

**Comment by JirkaDellOro** [comment]
Da gab es eine grundsätzlichen Fehler im RenderOperator, die BlendModes waren bezogen auf Destination, nicht auf Source
