### ISSUE TITLE
Keyboard Enums depending on language

### ISSUE THREAD

**Issue by Dev-MarkoF** [JirkaDellOro/FUDGE#188]
KEYBOARD_CODE Layout default is english.
German Layout issues, e.g. Y <-> Z. 
Since FUDGE is used mostly in an environment where german keyboards are the vast majority it's probably more intuitive for users to have for example a KEYBOARD_CODE.Z actually happening on pressing Z not Y.
Maybe changing it hardcoded to german layout, for the often used cases like Z/Y, or have a mapping that is depending on something like system language.

**Comment by JirkaDellOro** [comment]
see #269
