### ISSUE TITLE
Something like a LineRenderer

### ISSUE THREAD

**Issue by Dev-MarkoF** [JirkaDellOro/FUDGE#189]
Having the possibility to add a line object to the rendering pipeline could be used for visual debugging of something like raycasts, or a general direction, physics joint axis and much more.

**Comment by JirkaDellOro** [comment]
Wie besprochen zunächst das Rendering von OIMO nutzen und dem beibringen, auf unseren Canvas zu malen.

**Comment by Dev-MarkoF** [comment]
- Closed - Für Physik Debugging implementiert, für Dinge wie z.B. Lauf-Pfade zeichnen ggf. noch irgendwann nötig.
