### ISSUE TITLE
Klassen(Konstruktoren) zur Laufzeit über String erhalten

### ISSUE THREAD

**Issue by plojo** [JirkaDellOro/FUDGE#190]
Wie Besprochen hier noch die Issue: Ich brauche noch eine Möglichkeit die Konstruktoren der Component-Klassen zur Laufzeit über einen String zu erhalten. Also z.B. sollte ich über den string "ComponentMaterial" den entsprechenden Konstruktor erhalten.

**Comment by JirkaDellOro** [comment]
Wenn Du die Superklassenkette kennst und den Namespace, solltest Du so vorgehen können (im Beispiel heißt die Klasse, deren Konstruktor gesucht ist "Class", eine der Superklassen "Superclass" und der Namespace "Namespace"):


```typescript
    let class: typeof Superclass = globalThis["Namespace"]["Class"];
```
damit kann man dann auch Instanzen kreieren
```typescript
    let instance: Superclass = new class(...);
```
