### ISSUE TITLE
Vertexnormalen der Sphere

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#192]
die scheinen noch nicht richtig gespeichert zu werden. An einem der Pole haben alle Flächen beim Flatshading die gleiche Farbe. Ich schätze, das alle Flächen an einem Vertex zusammen laufen und dieser derjenige ist, der die  Normale trägt. Es ist immer der letze Punkt in einem Trigon. Das könnte das Verhalten erklären.

**Comment by SimonStorlSchulke** [comment]
Alles klar - ich kümmere mich demnächst darum. Notfalls werde ich einfach auch an den Polen so viele übereinanderliegende Vertices generieren wie es Sektoren gibt. Aber das muss ja auch anders gehen.

**Comment by JirkaDellOro** [comment]
Gibt's hier schon etwas Neues? Robin Schwab macht seine Abschlussarbeit zum Modell-Editor und ich habe mit ihm bereits über allgemein das Problem der Flächennormalen gesprochen und deren Definition am jeweils dritten Vertex in einem Mesh aus zusammenhängenden Trigonen. Er wird das Problem ohnehin haben und könnte sich ggf. auch um die Sphere als Übung kümmern.

**Comment by SimonStorlSchulke** [comment]
Ich guck's mir mal an sobald ich mit meinem Umzug fertig bin an. Ich kann auch mal mit Robin sprechen. Wenn er das übernehmen will - gerne.

**Comment by JirkaDellOro** [comment]
Ich habe einen Lathe-Editor gebaut, der das Problem nicht hat und werde die Sphären darüber erzeugen lassen.

**Comment by JirkaDellOro** [comment]
Ich bin verwirrt. Ich habe nicht das angekündigte getan, kann aber auch nicht erkennen, das jemand anderes an der Sphere gearbeitet hat. Das Problem aber kann ich nicht mehr sehen...
