### ISSUE TITLE
Fudge Editor - Problems loading Components

### ISSUE THREAD

**Issue by Dev-MarkoF** [JirkaDellOro/FUDGE#194]
Updated Scene tree only showing the first component (mesh component) when an item is clicked. -> error "cannot read property toString" at fillContent().
Some component infos might also not be loaded/set.

**Comment by JirkaDellOro** [comment]
In den Files hat die Eigenschaft idResource gefehlt. Ich gehe derzeit davon aus, dass dies dem Alter der Dateien geschuldet ist, da diese Eigenschaft seit Januar 2020 bei der Konstruktion eines Materials automatisch definiert wird und somit auch serialisiert werden sollte. Ansonsten wird das Problem wieder auftreten, wenn wir wieder ans Speichern/Laden gehen. Als Fix habe ich eine Fake-Id in die Dateien händisch eingetragen.
