### ISSUE TITLE
Environment Map / invertierte Normalen

### ISSUE THREAD

**Issue by SimonStorlSchulke** [JirkaDellOro/FUDGE#205]
Ich hoffe ich irre mich nicht, aber soweit ich weiß gibt es noch keine schnelle Methode eine Environment Map in Fudge zu erstellen. In FudgeChemistry habe ich das gelößt, indem ich mir den MeshSphere Code rübergezogen habe, die Indicies und Normalen umgedreht habe und dann Szenenumschließend eine solche texturierte Kugel verwendet habe. Ist es geplant noch eine Methode für Hintergründe mit Equirectangular Projection einzubauen? Sonst würde ich entweder:

- Option 1: Beim SphereMesh eine Option einbauen die Normalen umzudrehen
- Option 2: eine generelle invertNormals Methode in Mesh einbauen

 Im Grunde funktioniert es ja mit der Kugelmethode gut und ist für die Lehre vielleicht sogar logischer(?) Andererseits wäre es eventuell später wichtig die EnvironmentMap klar zu kennzeichnen - z.b. für Image Based Lighting und Reflektionen falls das geplant ist.

**Comment by JirkaDellOro** [comment]
Als ich deine Innenraumkugel gesehen hatte, dachte ich, dass es gut wäre eine generelle Flip-Methode zu haben. Spricht etwas dagegen?

**Comment by SimonStorlSchulke** [comment]
Nein ich finde nicht - dann werde ich mich bei Gelegenheit mal darum kümmern.

**Comment by SimonStorlSchulke** [comment]
Mal ein kurzes Update dazu: Eigentlich ist das Prinzip ja sehr einfach. 1. Normalen invertieren, 2. Indices Laufrichtung umdrehen (also bei jedem Triangle i[0] und i[2] vertauschen. Also so:
```ts
public flipNormals(): void {

      //invertNormals
      for (let n: number = 0; n < this.normalsFace.length; n++) {
        this.normalsFace[n] = -this.normalsFace[n];
      }

      //flip indices direction
      for (let i: number = 0; i < this.indices.length - 2; i += 3 ) {
        let i0: number = this.indices[i];
        this.indices[i] = this.indices[i + 2];
        this.indices[i + 2] = i0;
      }
      this.createRenderBuffers();
    }
```

Nun sieht das auch immer richtig aus mit ShaderTextured - was eigentlich dafür sprhct, dass die Indices richtig sind. Bei ShaderFlat scheint aber offensichtlich, dass da irgendwo ein on-off Error oder so drin ist, weil die segmente immer um 1 je Stack verdreht erscheinen. So sieht z.b. Torus und Sphere aus:
![inv](https://user-images.githubusercontent.com/25198913/87584830-62273f00-c6de-11ea-8b29-8ab4760c169b.jpg)

Und beim Cube noch schlimmer.
Ich hab schon sehr viel rumprobiert mit den Zahlen aber ich komme nicht drauf was es sein könnte.

**Comment by JirkaDellOro** [comment]
Beim Flatshading musst Du aufpassen, weil immer der dritte Vertex eines Trigons die Flächennormale angibt. Wahrscheinlich gerät das durcheinander.

**Comment by JirkaDellOro** [comment]
Vielleicht passt es, wenn Du [i] und [i+1] vertauschst, dann bleibt der dritte stehen und verweist nur auf die gespiegelte Normale.

**Comment by SimonStorlSchulke** [comment]
Das hat tatsächlich funktioniert - ich kann nich fassen, dass ich das vorher nicht ausprobiert habe und du lößt es in 5min 😄

**Comment by JirkaDellOro** [comment]
Also bitte.... das waren höchstens 3 Minuten
