### ISSUE TITLE
Serialization/-Deserialization of Vector3 properties

### ISSUE THREAD

**Issue by Dev-MarkoF** [JirkaDellOro/FUDGE#206]
There is no dedicated serialization of Vector3 properties, either there is one that is deeply hidden within something like serializable or it needs to be written.

**Comment by JirkaDellOro** [comment]
Es gab bislang tatsächlich noch nicht die Notwendigkeit, einzelne Vektoren zu serialisieren, daher wurde es nicht implementiert. Das ist ein Designprinzip bislang. Jetzt gibt es die Möglichkeit, eine Serialisierung zu schreiben, die letztlich ganz primitiv aussieht wie des des Coats:
```typescript
        public serialize(): Serialization {
            let serialization: Serialization = this.getMutator(); 
            return serialization;
        }
        public deserialize(_serialization: Serialization): Serializable {
            this.mutate(_serialization);
            return this;
        }
```
oder der Mutable-Klasse gleich diese Funktionalität zu spendieren, so dass alle Subklasse eine Standard-Serialisierung habe. Darüber möchte ich noch etwas sinnieren, nächste Woche fliegt mir sowieso alles um die Ohren, wenn ich mich an den Editor setze. Es wäre aber hilfreich, wenn Du mich auf die Klasse verweist, die Du serialisieren willst.

**Comment by JirkaDellOro** [comment]
Ich hadere gerade ein wenig... was meinst Du?

Ursprünglich war mein Plan, das man für die Serialisierung das Interface Serializable unterstützen und damit die erforderlichen Methoden schreiben muss. Im einfachsten Fall, und der liegt hier vor, so wie oben schon angegeben. Das könntest Du jetzt einfach in Vector3 einbauen.

Baue ich das in Mutable-Klasse, hat jedes Mutable gleich diese Funktionalität. Das ist bequem, bedeutet aber, dass die Serialisierung nicht zwingend funktioniert, da der Mutator nicht genug Information trägt, um komplexere Strukturen damit zu rekonstruieren. Darauf wird ein Entwickler dann aber nicht mehr von der IDE gestoßen, weil die Standardfunktionalität ja da ist...

**Comment by Dev-MarkoF** [comment]
Klar kann ich das in Vector3 in der Art wie das in Matrix4x4 gemacht wird einbauen, dachte nur dass das übernommen wird, weil es Teil von Fudge und nicht Physics ist. Haben wir wohl aneinander vorbei geredet, dann bau ich das demnächst noch ein.

**Comment by JirkaDellOro** [comment]
Wie geschrieben, das obige Muster müsste schon so passen.

**Comment by Dev-MarkoF** [comment]
Tut es nicht, bisher wenn ich ohne meine Änderungen Vector3 gespeichert habe, werden sie als z.B. 
"anchor"[ 
"0":value,
"1":value,
"2":value
]
gespeichert/serialisiert
und eine deserialisierung ist für Vektor3 garnicht vorhanden gewesen, nur in Matrix4x4 wird die gespeicherte Serialisierung einfach in den Typ des Vector3 gepresst, was dort funktioniert, aber ich brauchte eine Funktionsweise die a) eine ordentlich formatierte Serialisierung erlaubt, was nur der Fall war, wenn ich die standard "serialize" function von serializable extra nochmal in vector3 eingebaut habe, anstatt die base class zu nutzen. Wodurch das dann in x,y,z anstatt float32 datentyp speichert.

Außerdem entsprechend noch eine deserialize und mutate function eingefügt habe. Vector3 scheint mir bisher recht unterentwickelt, da anscheinend laut Kommentaren nicht klar ist, ob man von float32 daten array nicht auf x,y,z als public variables gehen will. 

So funktionierts jetzt, speichern/laden aller physik komponenten funktioniert definitiv behind the scenes, komplett. Dafür befinden sich auch 2 Testszenen in meinem experiments Ordner. Visuell werden components bisher nicht fehlerfrei geladen, da klappt was nicht, aber ich habe auch noch nicht die neuesten Änderungen am Editor probiert.  :)

**Comment by JirkaDellOro** [comment]
Ups, da hatte ich nicht dran gedacht, dass die Grundlage für Vector3 das FloatArray ist. Das ist schon sinnvoll, da die Vektoren zur Laufzeit ständig mit WebGL kommunizieren müssen und dies das Schnittstellenformat ist. Dafür war dann der Rest tatsächlich unterentwickelt, da bislang noch nicht benötigt. Danke für die Implementation.

**Comment by JirkaDellOro** [comment]
Da ich gerade in der Vector3-Klasse war habe ich mal nach deiner Implementierung von `mutate` geschaut.

```typescript
    public mutate(_mutator: Mutator): void {
      let _x: number = <number>_mutator["x"];
      let _y: number = <number>_mutator["y"];
      let _z: number = <number>_mutator["z"];
      this.x = _x;
      this.y = _y;
      this.z = _z;
    }
```

Das Problem dabei ist, dass es auch unvollständige Mutatoren geben kann, es soll dann trotzdem funktionieren. Zudem kann man hier noch leicht optimieren. Eine bessere Implementation müsste etwa so aussehen:

```typescript
    public mutate(_mutator: Mutator): void {
      this,set(
         <number>_mutator["x"] || this.data[0],
         <number>_mutator["y"] || this.data[1],
         <number>_mutator["z"] || this.data[2]
      )
    }
```

Bitte prüfe dies und baue es entsprechend um, dann können wir das gleich mitmergen, wenn Du so weit bist.

**Comment by Dev-MarkoF** [comment]
Ah, stimmt, daran hatte ich nicht gedacht. Mutatoren sind mir ein wenig suspekt noch als Konzept.
Ist eingebaut und funktioniert wie gedacht.
