### ISSUE TITLE
VectorEditor

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#209]
@Robin-Sb
Habe die Konversation mit Lukas gefunden, er hatte es in einen eigenen Branch gepusht: https://github.com/JirkaDellOro/FUDGE/tree/VectorEditor-old-origins

Ich glaube, ich habe es bereits von dort in den Development-Branch kopiert, bitte vergleiche mal.

**Comment by Robin-Sb** [comment]
Der Branch scheint im Großen und Ganzen gleich zu sein, der einzige Unterschied, den ich gefunden habe, ist, dass es im VectorEditor-Branch (https://github.com/JirkaDellOro/FUDGE/tree/VectorEditor-old-origins/Experiments/Lukas/VectorEditor/src/VectorEditor) noch einen UIHandler.ts File gibt, welcher im Development-Branch nicht existiert. 
Ich weiß aber natürlich nicht, ob das absichtlich weggelassen oder vergessen wurde, die ganzen Dateien wurden ja scheinbar von Hand kopiert und nicht gemerged.

**Comment by JirkaDellOro** [comment]
Weiß ich gerade auch nicht mehr. Probier' beides mal aus. Wenn es im Branch EditorPanelRedesign genauso läuft, kannst Du damit weiter machen, denke ich.

**Comment by Plagiatus** [comment]
Wenn ich mich richtig erinnere, war der UIHandler damals nur als Übergangslösung gedacht, bis der "richtige" handler von Moni einsatzbereit ist.

**Comment by JirkaDellOro** [comment]
Und ich glaube ihn eliminiert zu haben, als ich den Editor umbaute.

**Comment by Robin-Sb** [comment]
Der UIHandler wird auf jeden Fall noch einige Male in Editor.ts referenziert, das compiled also nur wenn man diesen eingebunden hat. Wenn man außerdem noch die Panels in der index.html einbindet, sieht das in etwa so aus: 

![Screenshot_20200906_125832](https://user-images.githubusercontent.com/34275205/92324327-05426800-f041-11ea-9d76-811d17dae86c.png)

Ist das der richtige (aktuelle) Stand?

**Comment by JirkaDellOro** [comment]
Ich fürchte, wir reden von unterschiedlichen Dingen. Wenn ich den Editor meine, dann spreche ich von ganz FUDGE. Da habe ich den Kram rausoperiert. Es gab Ansätze von Monika und Lukas, den Animationseditor und vielleicht auch den Sketcheditor zu integrieren. Die sind derzeit schlicht auskommentiert, weil ich den Editor ganz auf den Kopf gestellt habe. Sie müssen erst nach und nach wieder aktiviert/integriert werden.

@Robin: derzeit kannst Du also erst einmal unabhängig damit herumspielen, bis FUDGE so weit ist, dass wir über eine Integration des Modellers sprechen können.

**Comment by JirkaDellOro** [comment]
Könnte man den Issue schließe @Robin-Sb ?
