### ISSUE TITLE
Canvas is cleared when createPickBuffers is called

### ISSUE THREAD

**Issue by Robin-Sb** [JirkaDellOro/FUDGE#216]
Invoking viewport.createPickBuffer() directly (for example via keydown-event) clears the canvas so that it becomes white/empty. If the viewport.draw() method is invoked afterwards, this behaviour leads to a flickering effect.

This seems to happen at `this.canvas.width = rectCanvas.width;` in adjustFrames().

**Comment by JirkaDellOro** [comment]
createPickBuffers existiert nicht mehr. Wäre schön, wenn Du, Robin, mal nachschauen könntest, ob alles noch funktioniert und das Problem behoben ist.

**Comment by Robin-Sb** [comment]
Ich habe mal gemerged und alles nachgebessert, das Picking funktioniert jetzt wieder und der Fehler trat bei mir nicht mehr auf.
