### ISSUE TITLE
CameraControl

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#221]
Ich habe eine erweiterte Kamerasteuerung gebaut, die über FudgeAid eingesetzt werden kann. Ist noch nicht ganz das, was es werden soll, da noch kein Picking stattfindet, repräsentiert es aber bezüglich der restlichen Funktionsweise. Probiere es aus unter

https://jirkadelloro.github.io/FUDGE/Editor/Examples/Forest/Forest.html

Mit Shift und Alt kannst Du auf Translation- bzw Rotation-Mode umschalten, ansonsten gilt Orbit-Mode.

PS: Die Szene wurde übrigens komplett im Editor erschaffen.

**Comment by JirkaDellOro** [comment]
Ich habe nun eine intuitive Kamerasteuerung auf der Basis von Picking

**Comment by Robin-Sb** [comment]
Die neue Kamera ist meiner Meinung nach im Kontext des Modellers etwas schwierig zu benutzen (ich hatte dort auch einfach die OrbitKamera verwendet), weil das Selektieren von Widgets relativ schwierig wird, da sich die Position der Objekte ja während dem Picking verändern.

Außerdem ist die Kontrolle etwas unpräzise, was für den Modeller wohl ein größeres Problem ist als für den Editor. 
Es wäre ziemlich hilfreich, wenn man die alte Kamera irgendwie auch noch benutzen könnte.
