### ISSUE TITLE
Nutzerinteraktion Mesheditor

### ISSUE THREAD

**Issue by Robin-Sb** [JirkaDellOro/FUDGE#222]
### Translate

![DragNDrop](https://user-images.githubusercontent.com/34275205/98848447-071a1480-2452-11eb-8af8-2f946cd3f39f.png)
_Drag'n'Drop_

![TranslateWidget](https://user-images.githubusercontent.com/34275205/98848480-1305d680-2452-11eb-8f7a-a500d3685585.png)
_3D-Widget with axis constraints_
_constraints are also toggable via x,y,z keyboard presses_

### Rotation

![RotateWidget](https://user-images.githubusercontent.com/34275205/98848688-62e49d80-2452-11eb-8b52-b4513050597c.png)
_rotation 3D Widget_
_angle from mouse movement is translate into rotation angle_

### Scale

![ScaleWidget](https://user-images.githubusercontent.com/34275205/98848784-83acf300-2452-11eb-961a-74e74b31f85d.png)
_scalation 3D widget with axis constraints_

### All transformations 

![SlideControl](https://user-images.githubusercontent.com/34275205/98848839-96bfc300-2452-11eb-946e-b8ea09e1f313.png)
_manual slide control (exists already)_

### Extrude 

![Extrude](https://user-images.githubusercontent.com/34275205/98848934-bfe05380-2452-11eb-895f-cde90d184844.png)
_selected vertices are duplicated_
_new vertex position is at cursor position_

### Select
![Select](https://user-images.githubusercontent.com/34275205/98849048-e1413f80-2452-11eb-8536-99b2a1ca42c4.png)
_vertex below pointer is selected on mouse down
If a selected vertex is selected alread, it will be deselected
If a mouse down event is fired and no vertex is nearby, the entire selection will be cleared
Selection only exists in Edit-Mode since the scene only consists of one node._

[Lathe könnte sowas in der Art sein](https://webglfundamentals.org/webgl/lessons/webgl-3d-geometry-lathe.html)
Ist das etwa was du dir darunter vorgestellt hattest?

Ich freue mich über Rückmeldung jeglicher Art. 
Da die Deadline meiner Thesis in nicht mal zwei Monaten ist, kann es gut sein, dass zeitlich nicht alles umsetzbar ist.

**Comment by JirkaDellOro** [comment]
Umgesetzt und in Robins Thesis dokumentiert
