### ISSUE TITLE
Physik - Neue Erkenntnisse und weiteres Vorgehen.

### ISSUE THREAD

**Issue by Dev-MarkoF** [JirkaDellOro/FUDGE#224]
Habe ja schon länger daran gedacht Oimo durch Ammo zu ersetzen, da mir einige Dinge nicht ganz sauber vorkommen.

Ich habe mich schon länger an einen ersten Versuch von Fudge mit Ammo rangesetzt und bin inzwischen soweit gekommen, dass ich mal ein paar Dinge ansprechen wollte.

a) Leider unterstützt Ammo wohl auch keine Concave vs. Concave Kollision, nur Original Bullet unterstützt das über einen speziellen gImpact Algorithmus, der aber nicht portiert wurde, weil sich Concave Collider auch durch massig Convex darstellen lassen. Dennoch ist Ammo einfach die bessere Physik Engine und hat auch z.B. Terrain Collider.
-> _Es gibt Algorithmen die aus einem Mesh eine möglichst kleine Anzahl von Convexen Meshes erstellen, das schau ich mir vlt mal an. Da man es schwer verantworten kann, dass Nutzer selbst mehrere Collider anhängen und anpassen müssen um das zu erreichen. Hatte es von Unity her echt nicht so komplex erwartet, aber Concave Gegenstände sind in interaktiven Anwendungen wirklich ein Problem._  :)

b) Ich habe in der Thesis ja schon an Ammo gedacht und rumprobiert bin aber nie auf die Lösung gestoßen warum Ammo einen so komplizierten Weg nutzt um geladen zu werden. Stichwort. Ammo.then() Ladevorgang. Nun ist mir allerdings aufgefallen, wo das Problem liegt. Es liegt an FUDGE. Ein Problem, was vlt. noch öfter auftauchen könnte, aber nicht muss.

**Die Paradigmen von FUDGE aus bisheriger Anwendersicht liegen teilweise auf Javascript Niveau nicht auf Typescript.** Weshalb Ammo nicht korrekt im Hintergrund geladen werden kann, so dass eine "versteckte" Integration möglich ist. 
Eine FUDGE Szene wird direkt im Script gecoded, 
Pseudocode:
```
window.addEventListener("load", init);
function (init){
viewport.initialize
viewport.addEventlistener(gameloop, update)
**node.addComponent(f.ComponentRigidbody)  // -> Hier krachts weil vor Ammo/Modul initialisierung**
}

function update(){
   viewport.draw()
   **f.Physics.simulate ()**
  // --> Genau hier krachts spätestens, weil der Javascript code ohne Kapselung schon bearbeitet wird, selbst wenn ich sage halte an bis Ammo geladen ist, versucht er dennoch Ammo zu finden, weil Javascript ohne Kapselung den Code liest und sich fragt was dieses Ammo ist.
}
```
Hier wird immer Javascript mit Typescript vermischt, tatsächliches Typescript wie ich es in Anwendungen immer wieder vorfindeu und worauf ich von Ammo Entwicklern darauf hingewiesen wurde, sollte natürlich nur Klassenaufrufe auf der 1. Ebene haben und keine functions die Anwendungslogik produzieren.

Jetzt ist das aber natürlich aus einer strictly typed Sicht und da ich gerade wieder mehr C# Programmiere schlechter Stil, eigentlich genau das was man mit typescript vermeiden möchte. Es muss natürlich gekapselt werden, dann kann man entsprechend auch erst Ammo laden und dann ein Objekt von z.B. der Klasse Szene erstellen, diese ist dann die Basis der Anwendung der Nutzer.
Pseudocode:
```
class Scene{
 
  public static viewport
  public static sceneTree
 
  constructor(){
  //init code, objekte erstellen, Spiellogik aufbauen
  }

 public static update(){
     Scene.viewport.draw()
     f.Physics.simulate()
 }
}

let scene : Scene = f.Physics.initialize(Scene) 
```
 // -> Ich gebe der Physik die Klasse von der ich ein Objekt haben möchte und im Hintergrund wird das Objekt erst dann erstellt und der Code gelesen, wenn alles geladen ist. Dies ist eigentlich die korrekte Vorgehensweise. Führt allerdings dazu, dass Anwender halt tatsächlich nur objekt-oriented Code schreiben und bis auf diese Zeile kein javascript.
// Und wenn ich keine Physik wollte dann würde ich z.B. so etwas wie let scene : Scene = f.initialize(Scene) aufrufen. Der Weg sollte aber immer sein, dass ein Objekt meines Spieles erzeugt wird. Anstatt meine Anwendung direkt auf der ersten Ebene zu Programmieren.

TL;DR;

- Für eine Ammo Integration müssten grundlegende Änderungen an der Vorgehensweise von FUDGE Coding vorgenommen werden, die allerdings den Standards entsprechen. Das hätte aber auch Auswirkungen darauf, wie der Editor Szenenaufbaut, der kapselt soweit ich weiß auch nicht.

- Ich würde vermutlich eher an der Oimo Integration basteln, z.B. Trennung von RB und Collider. Vlt. in Folge dessen an der automatischen decomposition von Concave Meshs in einzelne Convexe arbeiten

- Allerdings ein Umstieg auf neuere/bessere Engines vlt. auch mal andere Module wird schwierig. Da FUDGE sich nicht nur an Typescript hält. Bzw. auch noch mit Namespaces arbeitet, anstatt dem modernen ES6 Modules, was wie ich gemerkt habe auch zu Import Schwierigkeiten für Module führen kann. Weil man in Namespaces "internal modules", keine "external modules" laden kann, ohne dass sie selbst zu external modules werden und somit nicht mehr mit dem Namespace verbunden sind. 

Muss man jetzt alles nicht beachten, wollte nur mal so ein wenig schreiben, was ich gerade so erarbeitet habe. Auf meinem PhysicsAmmo Branch habe ich das entsprechend mal realisiert und dadurch Ammo entsprechend versteckt integriert. Zu finden in Physics/Ammo_Simple_Updated. 
**Daran arbeite ich aber wohl nicht mehr weiter, da ich denke, dass die Modernisierungen an FUDGE zu umständlich sind um sie umzusetzen, da wir ja eher an Featurereichtum arbeiten.**

**Comment by JirkaDellOro** [comment]
Ich habe leider noch keinen Weg gesehen, wie ich statt mit Namespaces mit ES6-Modulen arbeiten und immer noch so ordentliche und simple Strukturen produzieren kann, die dann in ein einziges FudgeCore-File kompilieren, ohne weitere Tools wie WebPack etc. nutzen zu müssen. Daher bleibe ich bislang dabei.

Schau mal, wie der RenderManager autoatisch, da statisch, geladen wird. Er wird durch ein fudgeConfig parametriert, das man vor dem Laden von FudgeCore im HTML definieren kann. Ich schätze, dass Du mit dem gleichen Ansatz auch dein Physikproblem lösen kannst. Ich poste ein Beispiel aus der Praxis

**Comment by JirkaDellOro** [comment]
```html
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DoomFace</title>
  <script>FudgeCore = {fudgeConfig: {antialias: true, alpha: true}}</script> 
  <script src="../FudgeCore/FudgeCore.js"></script>
  <script src="../FudgeAid/FudgeAid.js"></script>
  <script src="Main.js"></script>
</head>
```

**Comment by Dev-MarkoF** [comment]
Danke, ich schau mal danach. 
Finde gerade nicht, wo wird der RenderManager den geladen bzw. instanziert? Finde ehrlich gesagt auf die Schnelle den Startpunkt einer FUDGE Anwendung nicht mehr.


Aber ich glaube, dass löst das darunterliegende Problem nicht.

OOP erfordert, dass Code "gelesen" wird, wenn er gebraucht wird.
Javascript "liest" den Code aber direkt beim Einlesen. 
D.h. eventuelle Variablen/Functions die Ammo. enthalten schmeißen einen Fehler und obwohl Ammo. später wenn der Code tatsächlich genutzt wird vorhanden ist, ist die Anwendung schon nachhaltig fehlerhaft.

Wenn man allerdings in Typescript nach normalen OOP Standards kapselt, d.h. seine Anwendung in Klassen verpackt, dann wird der Code von "javascript.prototypes" erst "gelesen" wenn er tatsächlich genutzt wird. 

Fudge arbeitet da einfach nicht objekt-orientiert, bzw. es wird so nicht gelehrt, ansich hindert einen natürlich nichts daran objekt-orientiert zu programmieren. Für eine Ammo Integration müsste es dann nur wirklich forciert sein, auch in den bestehenden Beispielen und der Funktionsweise des Editors.

btw. wollte das mit den Modulen nur mal ansprechen, weil die Physik Engines z.B. in neueren Varianten alle auf Module setzen, weil das wohl durch Node.js auch ein wenig forciert wird, denke das kann sich halt noch auf andere Punkte auswirken, sehe das aber auch so, dass NameSpaces übersichtlicher sind.

**Comment by JirkaDellOro** [comment]
Statischen Eigenschaften werden direkt beim Kompilieren erzeugt. FUDGE macht sich das an vielen Stellen zu nutze, so auch beim RenderManager. Damit wird eben sicher gestellt, dass Grundfunktionalität von Anfang an vorhanden ist.

**Comment by Dev-MarkoF** [comment]
Ah so meinst du das, ne das trifft leider nicht das was ich meine, glaube ich hab das Problem noch nicht richtig rübergebracht.

Ammo ist nicht statisch, Ammo ist einfach nur über ein **Javascript Promise** eingebunden und es ist eine **Promise Violation**, **wenn irgendwo Code Ammo. enthält bevor das Versprechen erfüllt ist**.
In OOP wird Code aber **nicht gelesen bevor er kein Objekt davon instanziiert wird**, wodurch die Javascript Runtime im Browser nicht auf Ammo stößt und eben kein Promise Fehler geworfen wird. Den Fehler abzufangen bringt leider nichts, sobald er geworfen wird, wird sowohl Fudge als auch Ammo nicht mehr korrekt ausgeführt.
 
Javascript hat um OOP zu realisieren diese Prototype Geschichte eingeführt, was wir in Typescript als Klasse kennen. Eine Szene in Fudge sollte eine Klasse sein, die durch einen Einstiegspunkt gestartet wird. 
So wie das im klassischen C# und java die Main() Methode ist, oder in Unity die Start(). Objekte sollten erzeugt werden und nicht ausgeführter Code auf oberster Ebene.

Fudge ist auf Editoren Seite in Typescript geschrieben, soweit so gut.
Wenn du dir jetzt allerdings sämtliche Tests und Beispiele anschaust, siehst du, dass Fudge zwar in Typescript geschrieben ist, aber Produkte mit Fudge bisher als eher _typed_ Javascript geschrieben sind und eben nicht reines Typescript bzw. OOP.

Alle functions müssten Methoden einer Klasse sein und alle Variablen entsprechend public properties dieser. Im Falle des Anwendungsstarts einer Fudge Anwendung wird dann entweder.
[Wie es eigentlich aussehen sollte](https://github.com/JirkaDellOro/FUDGE/blob/PhysicsAmmo/Physics/FUDGEandAmmo_Simple_updated/Main.ts)

ƒ.initializeApp(SzenenKlasse) aufgerufen, oder ƒ.initializeAppWithPhysics(SzenenKlasse) für eine Anwendung mit Physik.
Wobei der gesamte Anwendungscode sich in SzenenKlasse bzw. Unterklassen die von dieser instanziiert werden befinden.

Damit gewährleistet man optimale Funktionsweise und könnte z.B. eine Szene auf mehrere Canvas rendern. Außerdem ist so der Fudge Editor/Engine Code näher an dem Produktionscode.

Das bisherige Vorgehen führt zu meinem Problem, mit Ammo und könnte in Zukunft zu weiteren Problemen mit Modulen führen. Ich bin wie gesagt auch erst durch Entwickler von Ammo darauf gestoßen, hätte mir aber früher auffallen müssen.

Ich will jetzt auch keinen grundlegenden Paradigmenwechsel herbeiführen, nur das Problem muss bekannt und erklärt sein.

**Comment by JirkaDellOro** [comment]
Lass den ruhig mal offen, ich muss mir darum Gedanken machen...

**Comment by Dev-MarkoF** [comment]
Ok, aber ich bin schon von Ammo abgerückt, 
auch wenn das unabhängig davon ein wieder auftretendes Problem sein könnte.
Ehrlich gesagt sind wir nämlich mit unserer Oimo Integration wirklich erstmal zukunftssicher bedient. 

Ich kümmere mich eher um Oimo Verbesserungen. Die aber natürlich alle zeitlich TBD sind.

- Die Trennung von Collider und Rigidbody -> Muss mir dann aber nochmal überlegen wie ich das mit Events anders angehen muss. Aber das erlaubt dann bessere Compound Shapes, innerhalb einer Node mit vielen Collider Components, anstatt wie bisher vielen Nodes mit einem Collider

-  Im Zuge dessen dann einen Automatisierten Algorithmus, der aus einem Concaven Mesh, z.B. einem Ring eine Vielzahl von passenden Collider Components an die Node hängt.

- Der Debug Draw von Buffergröße unabhängig machen, bisher gibt es eine maximal Anzahl von Objekten die im Physik Debug zu sehen sind, danach sind sie unsichtbar. (Weil Buffer vorinitialisiert werden)

- Andere kleine Dinge die mir aufgefallen sind. Da Oimo an sich nicht wirklich weiterentwickelt wird, schaue ich ob ich daran direkt basteln kann.

**Comment by JirkaDellOro** [comment]
Konkave Meshes sind auch kein drängendes Problem derzeit. Wieso bist Du wieder von Ammo abgerückt und hat sich etwas bei Oimo verändert, dass Du zur Einschätzung "zukunftsicher" kommst?

Grundsatzdiskussion: bitte verweise mich zu Quellen bezüglich "In OOP wird Code aber nicht gelesen bevor er kein Objekt davon instanziiert wird," Ich möchte das gerne prüfen und FUDGE daraufhin untersuchen.

**Comment by JirkaDellOro** [comment]
PS: früher musste man explizit zu Beginn eines FUDGE-Programms RenderManager.initialize(...) aufrufen. Das habe ich extra wegrationalisiert. So aber könnte man aber immer noch die Physik starten, denke.

**Comment by Dev-MarkoF** [comment]
Quellen für objekt oriented programming und das Javascript dem nicht folgt? Das ist ja eigentlich bekannt, dafür hat man ja Typescript und das Prototype Keyword eingeführt. Hab da jetzt leider nicht die eine Quelle, sondern Ergebnisse aus eigenen Tests und Problemen an die ich immer wieder stoße.
Javascript ist ein ganz  großer Haufen Mist und trotzdem seit Jahrzenten die einzige Websprache, deshalb sind alle so hyped auf wasm, weil damit z.B. in C# komplette Webseiten programmiert werden können. Javascript ist eine freie Sprache und wird ja mit Biegen und Brechen ausgeführt, selbst wenn Fehler im Code sind, daher ist die Reihenfolge nicht immer so ganz praktisch.
Aber unter anderem kann man hier eine Diskussion zu Javascript Ausführung finden.
[Is Javascript Read Line by Line?](https://stackoverflow.com/questions/15395347/does-a-browser-truly-read-javascript-line-by-line-or-does-it-make-multiple-passe)

Ich glaube die alte Version mit RenderManager.initialize() macht auch nicht das was ich erhoffe. 

Das Problem liegt glaube ich tief in dieser offenen Struktur von Javascript und den Gegenmaßnahmen die man eingeführt hat wie z.B. Promises. 

In C# kann ich davon ausgehen, dass wenn ich etwas referenziere es auch vorhanden ist, weil es compiled wird und damit integriert. Es schmeißt mir sonst Fehler und lässt mich nicht compilen. Javascript aber lässt Definitionen von z.B. Ammo.btVector3 zu und liest dann beim compilen die Zeile, ist sich aber nicht sicher ob Ammo schon da ist, weil das zwar referenziert ist und ein Promise existiert, dass Ammo kommen wird, aber das Promise noch nicht erfüllt ist. Dadurch wird vermutlich die ganze Anwendung "zerstört". Deshalb bekomme ich bei einer Promise Violation garkeine Fudge Szene angezeigt, selbst wenn ich garkeine Physik nutze, aber allein die Defintion von irgendeinem Ammo lässt den Javascript Compiler platzen.

Wenn ich allerdings best practices für Typescript bzw. die Javascript Variante prototype nutze und alles in Klassen kapsel, dann wird der Code offensichtlich erst bei der Instanziierung und nicht der Definition des Objektes genutzt, daher ist sichergestellt, dass das Promise erfüllt ist, wenn der Compiler den Code liest.

**TL;DR;** 
Ich denke da Javascript eben nicht interpretiert ist, sondern auch compiliert, ist Code, der hinter einem Promise steht nur safe, wenn er instanziiert wird, weil das instanziierte Objekt vom compiler vermutlich anders behandelt wird als Code der ohne Objekt auf der 1. Ebene steht, weil mit der Einführung von mehr OOP Prinzipien in Javascript vermutlich auch die Sicherheiten dieser Prinzipien übernommen wurde.
Wenn ich den kompletten Fudge Anwendungscode in 
Ammo().then(function (Ammo){ //Anwendungscode }); 
packe, gehts auch, da dann das Promise auch vom compiler als save erkannt wird.

_____________________________________________________
Ammo, hat neue Tücken, z.B. 
- kann ein Rigidbody nicht ohne Collider bestehen, d.h. ich müsste an eine Fudge Node immer beides gleichzeitig hängen und sicherstellen, dass beides auf einer Node ist, auch wenn eines entfernt wird.
- Wasm ist nicht umsetzbar, weil Wasm cross origin geladen wird und das für die Nutzer entweder bedeutet, dass ihre Anwendung immer auf einen Server geladen werden muss, weil file// vom Browser immer als Cross Origin behandelt wird. Und in Tests habe ich von Wasm allein ehrlich gesagt nicht so viele Performancevorteile gespürt.
 
Außerdem wie schon erwähnt wurde von Bullet nicht die gImpact Klasse portiert, ich könnte die c++ Bindings natürlich selbst machen und Ammo selber builden, aber das wäre einfach ein unglaublicher Aufwand für direkte Concave Mesh Collider, wenn sich Concave Mesh Collider so schon durch eine Vielzahl von Convexen abbilden lassen.  

Oimo bietet alles an was wir bisher gedacht haben, außer Softbodies, aber da Fudge keine Softbodies benötigt, weil diese für Spielkonzepte eigentlich nichts erweitern und mehr für Spielerreihen bzw. tiefgehende Simulationen gedacht sind, denke ich nicht, dass wir eine viel größere Engine brauchen nur um eine unnötiges Feature mitzuschleppen. 
Zumal für Softbodies auch die Mesh Klasse anders aufgebaut werden muss, vermutlich, unter anderem müssen schließlich die Normalen immer wieder neu berechnet werden usw.

Ammo ist einfach deutlich komplexer aufgebaut, es ist mit der momentanen Integration relativ leicht eine neue Engine zu integrieren, wie z.B. Cannon.js oder vermutlich Goblin.js, aber Ammo ist sehr speziell, da müsste man dann doch nochmal tiefgehend anders denken. _Siehe, Problematik warum ich das Issue überhaupt eröffnet habe._

Die Schwäche von Oimo liegt nur in der langsamen/stoppenden Weiterentwicklung und der Genauigkeit, aber beide Fallen hier nicht so ins Gewicht und in Zukunft wird vermutlich eher noch neue Engines bzw. neue Portierungen kommen, wie schonmal erwähnt könnte PhysX stabile Ports bekommen und dann hätte man dieselbe Engine wie Unity/Unreal (wobei die wechseln wollen), da lohnt sich ein voller Umstieg aufgrund von Dringlichkeit nicht.

**Comment by Dev-MarkoF** [comment]
Gerade keine neuen Entwicklungen in diesem Bereich.
