### ISSUE TITLE
Erstellen einer Schnittstelle um Sounds einzubinden

### ISSUE THREAD

**Issue by christophsaile** [JirkaDellOro/FUDGE#229]
Hallo @JirkaDellOro ,

wie gestern in unserem Gespräch besprochen:
Issue zum Thema: Erstellen einer Schnittstelle um Sounds einzubinden.

**Comment by JirkaDellOro** [comment]
Der Issue ist in diesem Repository falsch aufgehoben und müsste eigentlich zum Lobalarp-Projekt. Trotzdem hier der Code zum Einbinden:

https://rina14.github.io/Abschlussarbeit/Theater/Sound.ts

Die Sound-Klasseregelt  das interne Management, relevant für die Verwendung sind die statischen Methoden play und fade.
