### ISSUE TITLE
updateUserInterface-Aufruf des UI-Controllers wird nicht entfernt

### ISSUE THREAD

**Issue by Robin-Sb** [JirkaDellOro/FUDGE#230]
Der beim Konstruktor-Aufruf der Controller-Klasse hingefügte Aufruf refresh() bzw. updateUserInterface() wird momentan nicht entfernt, auch wenn das zugehörige DOM-Element nicht mehr existiert bzw. auch nicht, wenn das zugehörige View geschlossen wurde. Vor allem bei längerer Laufzeit, bzw. wenn viele Elemente hinzugefügt werden, kann das zu Performanz- und eventuell auch anderen Problemen führen. 

Der Grund liegt wohl darin, dass der Loop nicht an ein Objekt gekoppelt ist, sondern über `window.setInterval()` hinzugefügt wird.

**Comment by JirkaDellOro** [comment]
ich habe die refresh-Methode folgendermaßen erweitert
```typescript
protected refresh = (_event: Event) => {
      if (document.body.contains(this.domElement)) {
        this.updateUserInterface();
        return;
      }
      
      window.clearInterval(this.idInterval);
    }
```

Zwei Dinge:
- ich weiß nicht, wie teuer die `contains`-Methode ist, ich hoffe billig
- wenn man nun temporär das Dom-Element zum Control nicht im DOM hat, endet die Loop. Um sie wieder zu starten, bittet der Controller nun eine Methode `startRefresh`
