### ISSUE TITLE
Stepper

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#234]
Der FUDGE-NumberStepper hat bei Matrizen immer mal wieder NaN angezeigt. Ein Problem, dass ich identifizieren und beheben konnte ist, dass die Vektoren mit Float32 arbeiten und damit früher an Infinity kamen als üblich. Der Stepper zeigt jetzt in dem Fall das Zeichen für Unendlichkeit.

Ich weiß aber nicht, ob es noch andere Situationen gibt, die den Fehler produzieren können.

@Robin-Sb : Da Du derzeit viel damit zu tun hast, bitte ich das zu beobachten und gegebenenfalls zu identifizieren, wie das Problem zu reproduzieren ist, damit ich es untersuchen kann.

**Comment by Robin-Sb** [comment]
Früher hat der Stepper NaN angezeigt, wenn man den ganzen Stepper statt eine einzelne Ziffer selektiert und anschließend das Mausrad bewegt hat. Das schafft man zum Beispiel, wenn man auf den Buchstaben (also x, y oder z) statt auf eine Zahl klickt. Ich bin mir aber nicht ganz sicher ob du das meinst, weil der Stepper ja auch NaN angezeigt hat, wenn man einfach nur lange genug gescrollt hat. 
Inzwischen zeigt der Stepper hier jedenfalls auch Infinity an, noch besser wäre es vielleicht, würde gar nichts passieren. Einen anderen Fehler habe ich bisher nicht gefunden, ich melde mich aber falls mir noch was auffällt. 
Ich habe mich aber noch gefragt, ob es irgendeine Möglichkeit gibt mit Infinity weiterzuarbeiten bzw. wieder einen in einen rationalen Zahlenbereich zu kommen? Eine Lösung wäre wohl entweder resetten zu können (also wieder auf 0) oder beim einmaligen runterscrollen den Wert auf den Maximalwert von Float32 - 1 zu setzen. Noch leichter wäre es wohl, wenn man einfach normal Zahlen eingeben könnte, wenn man das Infinity Zeichen selektiert.

**Comment by JirkaDellOro** [comment]
Weißt Du, dass man einfach bei selektiertem Stepper anfangen kann zu tippen? Zumindest war es so gedacht, ansonsten mit Standard F2

**Comment by Robin-Sb** [comment]
Ah, das wusste ich tatsächlich nicht, ich hätte irgendwie erwartet, dass man bei der selektierten Infinity Ziffer tippen kann, weil das ja bei normalen Ziffern auch geht. 

Alles klar und danke.
