### ISSUE TITLE
Suspension-Physik for Cars

### ISSUE THREAD

**Issue by BeauMo** [JirkaDellOro/FUDGE#235]
The idea is to develop a basic suspension for Cars based on the reworked and renamed MeshHeightMap now MeshTerrain.
With the implemented physics in FUDGE it should be relativly easy to aply the right forces to a basic Car so the attached tyres stay on the ground while the body of the car is conntrolled und leveled by forces.

@Dev-MarkoF If you have time to help me you can add me on Discord Mojo/Moritz#8095 or respond to this issue and i will explain the details in german :)

**Comment by JirkaDellOro** [comment]
A first iteration would not even have tires but just spring-forces attached to the four lower corners of a cube, keeping it above the ground.

**Comment by JirkaDellOro** [comment]
Seid ihr in Kontakt?

**Comment by BeauMo** [comment]
Bisher leider nicht

**Comment by Dev-MarkoF** [comment]
Ich schau mal rein, sorry habe keine Meldung von Github bekommen. 
Gerade mit Prüfungsaufsicht/Beisitz beschäftigt, aber ich habs im Hinterkopf.

**Comment by JirkaDellOro** [comment]
@Dev-MarkoF : wie gesagt, für uns würde es genügen, wenn eine Box an den vier Ecken von Federn gehalten wird. Ist das im gegenwärtigen Zustand abbildbar?

**Comment by Dev-MarkoF** [comment]
Sollte, 
muss man ein wenig konfigurieren, weil die Standard Einstellungen auf Performance ausgelegt sind und das daher die Berechnungen weniger genauer sind. Habe ja dokumentiert was man da einstellen kann.

Aber eine Box mit 4 Federn wird kein gutes Fahrgefühl darstellen, wie gesagt man sollte da eher mal in das Themengebiet Raycast Car reinschauen, da werden Federn über Raycasts simuliert. Mit Gelenken macht man das erst, wenn das richtig aufwendig eingestellt wird.

Mir ist zwischenzeitlich noch die Idee gekommen, das Terrain liefert eine Richtung und einen Y-Wert, bei gleich bleibender Triangle Size? Dann könnte man vlt. einen Terraincollider Simulieren in dem man einen Pyramiden Rigidbody immer auf das Triangle des Terraincolliders positioniert, auf dem sich das Auto befindet. Bzw. auch welche auf die umliegenden Triangles.

**Comment by BeauMo** [comment]
Es geht garnicht so sehr um ein realistisches Fahrgefühl, eher um ein Beispiel, was man mit dem Terrainsystem machen kann. 
Ich habe jetzt ein Auto mit zwei Starrachsen umgesetzt welches über das Terrain fahren kann und unebenheiten ausgleicht. 

So wie ich das im verlinkten Artikel verstanden habe, könnte man das sicher auch mit einer etwas abgewandelten Version meiner Terrainklasse und deiner Physik umsetzten. Ich denke aber, dass dies in anbetracht der Zeit nicht mehr möglich sein wird.

**Comment by Dev-MarkoF** [comment]
Das sieht sehr gut aus, auch mit Bremsweg usw.
Ja mit Zeit ist das möglich. Es ist nur nichts vorgefertigt.

**Comment by JirkaDellOro** [comment]
Jetzt kam ich doch am Wochenende nicht dazu, in den Code zu schauen. Ich stimme Marko aber zu, dass es schon jetzt ziemlich gut aussieht und scheinbar ausreicht um ein Outdoor-Rennspiel abzubilden.

**Comment by BeauMo** [comment]
Das mit dem Aufschaukeln habe ich gefixt. Ist auch im obeen verlinktem Test nicht mehr drin. Außerhalb des Terrain kommt es natürlich zu inkorrekten Rotationen was ich allerdings nicht als Bug einstufen würde.
