### ISSUE TITLE
mtx-Prefix for Matrix

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#238]
Ich mache gerade eine Konsolidierung, weil wir wohl endlich bei Version 0.1 von FUDGE angelangen. Dabei refaktoriere ich auch diverse Namen. Alle Variablen die auf eine Matrix verweisen sollen ein mtx als Prefix haben.

@Dev-MarkoF : bitte das bei der Physik durchführen, da auch die Beispiele angepasst werden müssen und ich nix kaputt machen will. Danke

**Comment by JirkaDellOro** [comment]
PS: ich habe devJirka in development und master gemerged

**Comment by Dev-MarkoF** [comment]
Bin dran, ich bau dann auch gleich den Fix für den Fehler ein und den verbesserten PhysicsDebugDraw.
Ich versuch mal so einen Pull request wenn ich fertig bin, die Änderungen mache ich anhand von "development"

**Comment by Dev-MarkoF** [comment]
Fertig, hab den Pull Request für den Master gemacht, weil du zwischenzeitlich den Development geändert hast, hätte ich soweit ich Git richtig verstehe erst deine Änderungen runterladen müssen, was meine Änderungen überschreibt. Und ich habe verdammt viele Änderungen machen müssen, weil du beim "refaktorieren" ca. 10-20% nötige Funktionen entfernt hast und teilweise bestehende kaputt gemacht, obwohl da ein Kommentar stand warum diese Zeilen nötig waren.

Btw. wie funktioniert das mit dem HTML laden im Editor? Ich konnte das nicht verifizieren, da ich selbst beim laden deiner Beispiel HTML für die simplen farbigen Cubes einen Fehler von "attribute of null" bekomme.

**Comment by JirkaDellOro** [comment]
> Und ich habe verdammt viele Änderungen machen müssen, weil du beim "refaktorieren" ca. 10-20% nötige Funktionen entfernt hast und teilweise bestehende kaputt gemacht, obwohl da ein Kommentar 

Ups... sorry! Aber besser jetzt als nie! Ich komme nachher mal bei dir vorbei und schau' mir dein Editor-Problem an
