### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#240]
Da wir nun zu dritt an FUDGE herumschrauben, müssen wir vorsichtig mit dem Mergen sein. Wenn man von unterschiedlichen Versionen aus seinen Code weiterentwickelt, können beim Mergen schwer nachzuvollziehende Fehler entstehen. So eine Situation haben wir gerade. David wird morgen ein Rollback auf die Version vor Markos Physic-Merge machen und von dort aus zunächst seine und meine Änderungen einpflegen, das waren nicht allzu viele, um zu schauen, ob wir so wieder alle Tests zum Laufen bekommen. Dann wäre es gut, wenn Marco zunächst seine Physic-Änderungen gegen die so erzeugte Version prüft und, sofern alles passt, einen neuen Pull-Request erstellt.

In Zukunft sollte dann David die Merges machen, da kann er zunächst einmal lokal mergen und testen und dann erst denn dev-Branch aktualisieren.

**Comment by Dev-MarkoF** [comment]
Also der Development Branch zum Punkt "compile" sieht Physik mäßig gut aus. Von da aus kann man also weiterarbeiten wie man will. :)

Ich schraube theoretisch gerade nicht mehr weiter, ich wollte mir mal noch die ganzen neuen Editor Sachen ansehen, aber passt gerade nicht so rein.

**Comment by JirkaDellOro** [comment]
David hat eine Branch vor deinem Merge abgezweigt und unsere seitherigen Änderungen eingepflegt, so dass alles läuft. Wir haben sonst Seiteneffekte dass Texturen verschwinden etc. David weiß ein bißchen mehr. Wenn wir so weit sind pushen wir auf development, dann kann man nochmal nach der Physik schauen.

**Comment by DavidNiemann** [comment]
Die Abfrage in FUDGE\Core\Source\Render\Render.ts auf Zeile 131 hat verursacht das keine Texturen mehr angezeigt werden. Ich habe sie jetzt in meinem branch auskommentiert. Mehr weiß ich bis jetzt auch nicht.

**Comment by JirkaDellOro** [comment]
@Dev-MarkoF : da sind wir wohl an der Stelle, an der wir einen eventgesteuerten Eingriff haben wollen, korrekt?

**Comment by Dev-MarkoF** [comment]
Ne, mit der Oimo Integration brauche ich keine Eingriffe, das funktioniert ja soweit alles. Da sind nur nicht funktionale Sachen im Editor sofern ich das richtig sehe. Event bräuchte ich nur, wenn ich jemals dazu komme eine andere Physik zu integrieren, die mehr kann z.B. Heightmap.

**Comment by JirkaDellOro** [comment]
Die Zeile, die David auskommentiert hat, worauf nun wieder richtig gerendert wird, ist

if (Physics.settings != null && Physics.settings.debugMode != PHYSICS_DEBUGMODE.PHYSIC_OBJECTS_ONLY)

nur wenn die Bedingung erfüllt war, wurde gerendert. Wenigstens eine der beiden Bedingungen war also nicht erfüllt. Ergibt das Sinn?

**Comment by Dev-MarkoF** [comment]
Die Zeile war drin, bei meinen Tests und funktionierte Einwandfrei.
Aber ich sehe das Problem, muss nur schauen ob Typescript die Null-Check Notation unterstützt. 
Der Sinn der Zeile ist, dass wenn man die Physik Debug Modus auf Wireframe stellt, nurnoch die Physik angezeigt wird, als Wireframe und Fudge Rendering ignoriert wird. 
Damit ich aber nachschauen kann ob in den Physik Settings der Debug Modus eingestellt wurde, muss ich vorher checken ob es Physik Settings gibt. Aber wenn man Projekte ohne Physik hat, dann hat man natürlich keine Settings, daher wird die Zeile natürlich das Rendering stoppen.

**Comment by JirkaDellOro** [comment]
> werden Pyramiden nicht mehr gezeichnet?   
Das Problem ist nicht bekannt, bei mir kommen sie ganz normal. Prüfe bitte nochmal und erstelle ggf. einen Issue

**Comment by Dev-MarkoF** [comment]
Da muss sich irgendwie was im Chrome aufgehangen haben. Hat sich gelöst, nach einem Neustart. Ganz diffus, war auch eher kein Fudge Problem sondern WebGL im Allgemeinen.

Also wie gesagt, die Zeile ist für das Physik Debugging wichtig, aber wenn ihr sie mit dem genannten Ansatz umschreibt, so dass bei fehlenden Physik Settings die Bedingung erfüllt ist, dann passt alles. Es muss halt nur gewährleistet sein, dass wenn man Physik Debugging auf dem speziellen Modus hat, alles andere ausgeblendet wird, damit man einen Überblick nur über seine Physik Objekte bekommt. 
Das kann man überprüfen in z.B. Physics/Tutorials/Lesson5Debugging -> T Taste um Einschalten des Debuggings und Z zum Modus durchschalten. Oder in Experiments/Marko/Phase2_Joints.

**Comment by JirkaDellOro** [comment]
Roger! @DavidNiemann : bitte übernehmen

**Comment by DavidNiemann** [comment]
Ich habe die Abfrage zu `if (!Physics.settings || Physics.settings.debugMode != PHYSICS_DEBUGMODE.PHYSIC_OBJECTS_ONLY) {` geändert und konnte keine Fehler feststellen. Ich habe Experiments/Marko/Phase2_Joints zum Testen benutzt und die debug-Modes sahen wie in der Anleitung beschrieben aus.

**Comment by JirkaDellOro** [comment]
Dann kannst Du das in den development branch schieben und den Issue schließen.
