### ISSUE TITLE
FUDGE-Editor läuft nicht mit electron Version 12. 

### ISSUE THREAD

**Issue by DavidNiemann** [JirkaDellOro/FUDGE#241]
Die Lösung für die Editor Errors war die electron Version unter 12 zu installieren, indem fall die version11.4.1.. Marius und ich haben versucht die 12.0.2 zum Laufen zu bringen, aber ohne Erfolg.
Unsere Erkenntnis war bis jetzt das remote ab der Version 12 deprecated ist.

**Comment by JirkaDellOro** [comment]
Ich traue dem noch nicht. Bei mir läuft er mit 12.0.0 problemlos. 

@Dev-MarkoF : welche Version hast Du?

**Comment by DavidNiemann** [comment]
Das Ding ist, wenn ich die Version von electron in der Konsole abfrage, habe ich auch 12.0.2, vermutlich electron von meinem PC abfragt. Aber ich habe die Version von FUDGE mit 'npm install electron@11.4.1' geändert so hat sich auch die package.json automatisch geändert und es ging bei Marius und mir.

**Comment by JirkaDellOro** [comment]
Hmmm.... was passiert, wenn Du händisch die package.json manipulierst?

Außerdem: es ist nun zu recherchieren, was wir machen müssen, damit wir ggf. von require wegkommen, wenn das erforderlich ist. Möglicherweise löst sich die Problematik schon auf, wenn wir das neue GoldenLayout ohne jQuery einsetzen. Wie weit ist Marius damit?

**Comment by koenigmm** [comment]
So habe ich es gemacht. Das hat auch nicht funktioniert. Die Electron Versionen unter 12.0.0 funktionieren.
Ich bin bin gerade dabei das neue GoldenLayout auszuprobieren bzw. ich habe es mit npm installiert und muss den Code noch anpassen.

**Comment by JirkaDellOro** [comment]
Ich habe David so verstanden, dass sich Electron als Version 12.0.2 meldet, FUDGE aber trotzdem läuft. 

@DavidNiemann : oder hast Du lokal für FUDGE eine andere Electron-Version installiert und wie meldet diese sich dann?

**Comment by DavidNiemann** [comment]
Lokal für FUDGE habe ich jetzt 11.4.1 installiert, 12.0.2 habe ich global auf meinen PC

**Comment by koenigmm** [comment]
Ich habe es global gar nicht installiert. Ich habe die package.json Datei auf Version 11.4.1 geändert und dann npm install. Mit 12.0.0 und neuer hat es nicht funktioniert

**Comment by JirkaDellOro** [comment]
Wie kommt ihr an die Versionsnummer der lokalen Installation?

**Comment by koenigmm** [comment]
cd in den FUDGE Ordner mit der Package.json und dann
`node list`
bzw.
`node list --depth 0`

**Comment by JirkaDellOro** [comment]
Ich habe das list-Modul nicht. Was spuckt er bei dir aus, wenn Du in dem Ordner "electron -v" eingibst?

**Comment by koenigmm** [comment]
Den Befehl findet PowerShell nicht. 

> electron : Die Benennung "electron" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren 
> Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie  
> den Vorgang.

**Comment by JirkaDellOro** [comment]
und in der normalen CMD?

**Comment by koenigmm** [comment]
auch nicht 

> Der Befehl "electron" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
> 

ich habe Electron nur lokal im Projekt installiert. Vielleicht geht der Befehl deshalb nicht.

**Comment by JirkaDellOro** [comment]
Wie startest Du den Editor gerade?

**Comment by DavidNiemann** [comment]
Egal wo ich "electron -v" eingebe, kommt bei mir 12.0.2, aber in "FUDGE\node_modules\electron\package.json" steht jetzt Version 11.4.1

**Comment by koenigmm** [comment]
`npm run-script build
npm run-script run`

**Comment by JirkaDellOro** [comment]
@DavidNiemann 
Das gibt meiner Kenntnis nach nur an, welche Version die mindeste ist, die benötigt wird. Es sollte keine Auswirkungen auf das Laufzeitverhalten haben. Bitte verifizieren

**Comment by JirkaDellOro** [comment]
@koenigmm : Das build solltest Du eigentlich nicht machen, weil dann eine Executable gebaut werden sollte. run sollte reichen

**Comment by JirkaDellOro** [comment]
Eben habe ich aber eine vielleicht interessante Entdeckung gemacht. Ich starte eigentlich immer einfach über das Batch-File, in dem letztlich nur "npm run-script run" steht. Gebe ich das ein wie Marius, klappt es auch. Das run-script in der package.json sieht nur so aus: "electron Editor/electron". Gebe ich das aber in der Konsole ein, so wie ich früher den Editor meist aus VSCode heraus gestartet hatte, erhalte ich auch die require-Fehler. Bitte untersuchen

**Comment by koenigmm** [comment]
Das habe ich gerade ausprobiert. 
`npm i electron@12.0.2 ` 
damit ich sicher die neuste Version habe. 
und dann die batch gestartet. 

`Uncaught ReferenceError: module is not defined
    at HTMLScriptElement.onload (Fudge.html:15)`
`Uncaught ReferenceError: require is not defined
    at Fudge.js:104
    at Fudge.js:167`
`Uncaught TypeError: Cannot read property 'start' of undefined
    at Fudge.html:29`

wenn ich  wieder auf Version 11.4.1 wechsle `npm i electron@11.4.1` und dann die batch Datei ausführe funktioniert es wieder

**Comment by JirkaDellOro** [comment]
@DavidNiemann 
> Unsere Erkenntnis war bis jetzt das remote ab der Version 12 deprecated ist.  

was meinst Du mit remote?

**Comment by DavidNiemann** [comment]
[hier](https://github.com/electron/electron/blob/12-x-y/docs/api/remote.md) ist ein Modul von electron einer der Veränderungen  größeren Veränderungen in der Version 12

**Comment by JirkaDellOro** [comment]
Ich habe eben mal auf 12.0.2 aktualisiert und es läuft immer noch

**Comment by JirkaDellOro** [comment]
Ich habe noch etwas gefunden:
https://www.electronjs.org/docs/breaking-changes#default-changed-contextisolation-defaults-to-true

Experimentiert bitte mit den Einträgen der Methode addWindow in Main,ts

```typescript
function addWindow(_url: string, width: number = defaultWidth, height: number = defaultHeight): Electron.BrowserWindow {
    let window: Electron.BrowserWindow = new BrowserWindow({
      width: width,
      height: height,
      // fullscreen: true,
      webPreferences: {        // preload: path.join(__dirname, "preload.js"),
        nodeIntegration: true,
        enableRemoteModule: true
      }
    });

    window.webContents.openDevTools();
    window.loadFile(_url);
    window.maximize();
    return window;
  }
```

**Comment by JirkaDellOro** [comment]
Und noch etwas habe ich herausgefunden. Bei laufendem Editor gebe ich in der Javascript-Konsole
`process.versions.electron` ein und heraus purzelt
"9.3.0"

**Comment by JirkaDellOro** [comment]
Und bezüglich remote finde ich noch das:
https://www.electronjs.org/docs/breaking-changes#deprecated-remote-module

Baut mal um, ist eine gute Übung

**Comment by koenigmm** [comment]
Ich habe schonmal versucht remote wieder zu aktivieren. Dafür muss man` @electron/ remote` installieren und den Code anpassen
``` Typescript
nodeIntegration: true,  
enableRemoteModule: true,  
contextIsolation: false

const { app, BrowserWindow, Menu, ipcMain } = require("@electron/remote");

// Im Hauptprozess:
require('@electron/remote/main').initialize()
```

wenn ich das mache und den Code compile, dann bekomme ich folgende Fehlermeldung

```
node_modules/electron/electron.d.ts:6642:21 - error TS2694: Namespace 'NodeJS' has no exported member 'Require'.
6642     require: NodeJS.Require;
```
und beim Start von electron mit der batch Datei folgende Fehlermeldung. 
Ich habe verschiedene stellen für den initialize() ausprobiert. Innerhalb von createFudge() und an den addListenern immer mit dem selben Ergebnis.
```
App threw an error during load
Error: "@electron/remote" cannot be required in the browser process. Instead require("@electron/remote/main").
    at Object.<anonymous> (C:\Users\marius\Documents\GitHub\FUDGE\node_modules\@electron\remote\dist\src\renderer\index.js:14:11)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\marius\Documents\GitHub\FUDGE\node_modules\@electron\remote\renderer\index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

**Comment by JirkaDellOro** [comment]
Müsstest Du dann nicht auch mit einer 12er-Version starten?

**Comment by JirkaDellOro** [comment]
Ich habe mal nur `contextIsolation: false` eingetragen bei den WebPreferences, sonst nichts. Jetzt läuft es bei mir auch mit 12. Bitte verifizieren.

**Comment by DavidNiemann** [comment]
Wenn ich `contextIsolation: false ` bei den WebPreferences eintrage, geht bei mir auch die Versionen über 12.

**Comment by JirkaDellOro** [comment]
Dann checke das mal bitte so ein, auch wenn es derzeit nur ein Workaround zu sein scheint. Wir schauen wieder nach dem Thema, wenn Marius die neuen GoldenLayout-Version integriert hat. Ich schätze, dass sich die require-Problematik auch wegen der Eliminierung von jQuery dann anders gestaltet oder ganz auflöst.

**Comment by Dev-MarkoF** [comment]
Moin, @JirkaDellOro  habe es gerade erst gesehen.
Ich habe Electron 10 global genutzt, aber eigentlich sollte eh das package im Fudge Projekt genutzt werden und das ist vom neuesten Commit her 7.2.4 laut package.json. Ich habe mal sowohl mein globales als auch lokales auf 12.02 geupdated und der Editor läuft problemlos. 
Und spuckt mir mittels "process.versions.electron" auch im laufenden Betrieb das als genutzte Version aus.

**Comment by JirkaDellOro** [comment]
Wenn man unter Einbindung der package.json startet, also über das Batch-File oder npm, die lokalen Installationen genutzt werden, die schließlich auch aufgrund der Datei lokal installiert würde. Starte ich über `electron`, wird die globale Installation herangezogen.

**Comment by JirkaDellOro** [comment]
Wir haben jetzt also einen Workaround, aber wenn die neue GoldenLayout-Einbindung geschehen ist und jQuery FUDGE endlich verlässt, sollten wir die "richtigen" Mechanismen einsetzen.

-> daher an Marius als TODO

**Comment by Dev-MarkoF** [comment]
Über den Editor muss man nochmal nachdenken und auch mal vlt. Ablaufdiagramme oder etwas mehr Doku bereitstellen.
Mir fällt es schwer mich da durchzuwurschteln um die Physik "wieder" auch dort in den Gang zu bringen. 
Das fängt schon dabei an, dass der Render Call nur gesendet wird, wenn man die Kamera dreht? Sonst gibt es keine Update loop mehr?

**Comment by JirkaDellOro** [comment]
Klar, da muss der Editor dann reagieren. Im Moment habe mache ich das nicht, sofern es nicht erforderlich scheint. Jetzt warten wir erstmal Marius Fortschritte ab.

**Comment by JirkaDellOro** [comment]
Ich denke, das hat sich erledigt....
