### ISSUE TITLE
(Information) plugin benötigt für typedoc Version 0.20.35

### ISSUE THREAD

**Issue by DavidNiemann** [JirkaDellOro/FUDGE#242]
Ich habe auf dem branch DavidTest mal die typedoc auf die neuste Version upgedatet und habe es so hinbekommen das die Dokumentation so wie zuvor aussieht. Dafür musste ich [typedoc-plugin-merge-modules](https://www.npmjs.com/package/typedoc-plugin-merge-modules) installieren. Das bewirkt das alle entry points nicht in einzelne Module aufgeteilt werden.

**Comment by JirkaDellOro** [comment]
Ich frage mich, ob wir diese Module mit in die package.json aufnehmen sollen, oder besser nur ein kleines Readme machen, indem erklärt wird, wie man die Doku erstellt und die Module installiert.

**Comment by DavidNiemann** [comment]
Ich kann mal eine Readme schreiben

**Comment by JirkaDellOro** [comment]
Ich nehme an, dass Du aber auch an der typedoc.json rumgebastelt hast. Merge die bitte.

**Comment by JirkaDellOro** [comment]
Das funktioniert noch nicht richtig. Sämtliche Klassen sind nun unter animation_animation zusammengefasst und man kann nur mit größten Schwierigkeiten navigieren.

Siehe FUDGE/Documentation/Reference/Core/classes/animation_animation.fudgecore.pick.html

Schau mal, ob das nicht noch besser geht und frage auch beim TypeDoc-Team an, wie wir mit der neuesten Version eine sinnvolle Docu bauen können.

**Comment by DavidNiemann** [comment]
Ich werde es mir nochmal anschauen

**Comment by DavidNiemann** [comment]
Das, was du beschrien hast, sollte eigentlich von dem Plugin gelöst werden.
Wenn ich eine neue Doku erstelle, sieht der Pfad bei mir so aus:

Documentation/Reference/Core/classes/fudgecore.pick.html

Ich habe bei Typedoc nur noch kein issue geschrieben, weil die schon welche hatten mit ähnlichen/gleichem Problem und sie auf das Plugin verwiesen haben.

Oder habe ich was falsch verstanden?

**Comment by JirkaDellOro** [comment]
Da sollten wir mal eine Online Session machen, am besten morgen früh. Vielleicht mache ich etwas falsch

**Comment by DavidNiemann** [comment]
Alles klar, dann ruf mich morgen früh einfach auf Discord an.

**Comment by JirkaDellOro** [comment]
Und Du mich

**Comment by DavidNiemann** [comment]
@JirkaDellOro ich konnte dein Fehler nicht nachstellen, aber ich habe in die typedoc.json geschrieben, dass das Plugin benutzt werden soll. Somit sollte Typedoc mit Plugin funktionieren, wenn beide nur Global installiert sind.

**Comment by JirkaDellOro** [comment]
... und auch gepusht?

**Comment by JirkaDellOro** [comment]
@DavidNiemann  Habe TypeScript auf 4.4 gehievt, musste entsprechend auch TypeDoc updaten, jetzt wird das Plugin nicht mehr geladen. Kannst Du mal schauen, ob es bei dir klappt und was getan werden muss?

**Comment by DavidNiemann** [comment]
Ich habe TypeScript und TypeDoc auf die neuste Version gebraucht. Die Information für das Laden des Plugin kommt bei mir noch, aber in der typedoc.json muss verändert werden. Ich muss noch schauen, was alles geändert werden muss, weil gerade bekomme ich nur Fehlermeldungen oder ein leeres Dokument.

@JirkaDellOro Hast du mal versucht das Plugin neu zu installieren und bekommst du nicht die Fehlermeldung: Error: No entry points provided ?

**Comment by JirkaDellOro** [comment]
Ja, da war was. Ich hatte die json bereits angepasst, folgend mein letzter Stand. Dann habe ich den Issue geschrieben, weil ich eigentlich an ganz anderen Sachen dran war...

{
    "entryPoints": ["."],
    "entryPointStrategy": "expand",
    "out": "../../Documentation/Reference/Core/",
    "name": "Fudge Core",
    "readme": "none",
    "excludePrivate": "true",
    "excludeProtected": "true",
    "plugin": "typedoc-plugin-merge-modules"
}

**Comment by DavidNiemann** [comment]
Ich habe deine bisherigen Änderungen heruntergeladen und jetzt funktioniert bei mir die Erstellung der Dokumentation mit dem Plugin.

**Comment by DavidNiemann** [comment]
TypeScript 4.4.3
TypeDoc 0.22.4

**Comment by JirkaDellOro** [comment]
ich hatte TypeDoc 0.22.3, aber ein Update hat nichts geändert. Ich erhalte folgenden Fehler:
```
C:\Users\jirka\Documents\HFU\FUDGE\Core\Source>typedoc
Error: The plugin typedoc-plugin-merge-modules could not be loaded.
Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/converter' is not defined by "exports" in C:\Users\jirka\AppData\Roaming\npm\node_modules\typedoc\package.json
```

**Comment by DavidNiemann** [comment]
Hast du der aktuelle Plugin Version. Ich bin Versionen zurückgegangen mit Version 3.0.0 und 3.0.1 bekommen ich den Fehler auch. Mit der neusten 3.0.2 nicht mehr.

**Comment by JirkaDellOro** [comment]
Ooooch.... das war jetzt ein bisschen fies. Die neue Version kam keine 24 Stunden nachdem ich den Issue reaktiviert hatte. Super, dass Du so nachgeschaut hast!
