### ISSUE TITLE
FaceNormals beim Meshimporter

### ISSUE THREAD

**Issue by SimonStorlSchulke** [JirkaDellOro/FUDGE#244]
Ich schreibe gerade einen Exporter für Blender, der Dateien exportieren soll, für die ich in Fudge den Importer schreibe. Wie auch beim OBJ Importer komme ich hier mit den Normalen partout nicht weiter. Der Würfel, den ich zu importieren versuche sieht mit Flatshading und Dreipunktbeleuchtung so aus:

![broken](https://i.ibb.co/ZhzNT1V/2021-04-22-00-43-57-Document.png)

also offensichtlich sind die Normalen falsch. Ich verstehe aber auch scheinbar nicht, was die createFaceNormals Methode von Mesh nun genau tun soll. FaceNormals sind doch die Normalen eines Polygons - bei einem Würfel sollten das also bei 6 Seiten 12 Polygone x3 -> 36 Werte sein oder? Im [MeshCube](https://github.com/JirkaDellOro/FUDGE/blob/development/Core/Source/Mesh/MeshCube.ts) zum Beispiel sind es jedoch 16 x3 -> 48 Werte.... sind es nun doch Vertexnormalen und als "fake Facenormals" wird einfach immer die Normale des dritten Vertex im Face benutzt? Falls ja habe ich keine Ahnung, wie ich das im Im/Exporter umsetzen soll, damit  die Normalen richtig aussehen - weil ja Verts von mehreren Faces genutzt werden...

Hier mal der essentielle Code des Blender Exporters bisher (Python) - ist glaube ich klar, was der macht:
```python
bmesh.ops.triangulate(mesh, faces=mesh.faces[:])

vertices = []
faces = []
normals_face = []

for c_vert in mesh.verts:
    vertices.extend([c_vert.co[0], c_vert.co[1], c_vert.co[2]])

for c_face in mesh.faces:
    faces.extend([c_face.verts[0].index, c_face.verts[1].index, c_face.verts[2].index])
    normals_face.extend([c_face.normal[0],c_face.normal[1],c_face.normal[2]])

json_data = {
    "vertices": vertices,
    "faces": faces,
    "facenormals": normals_face
}

json_string = json.dumps(json_data, indent=4)
```

Der Importer soll dann eigentlich nicht mehr tun als das JSON zu deserialisieren:

```typescript

// Wird im Konstruktor ausgeführt
protected parseObj(data: string): void {
    this.jsonObject= JSON.parse(this.jsonString);
}

protected createVertices(): Float32Array {
    return new Float32Array(this.jsonObject.vertices);
}

protected createIndices(): Uint16Array {
    return new Uint16Array(this.jsonObject.faces);
}

protected createFaceNormals(): Float32Array {
    return new Float32Array(this.jsonObject.facenormals);
}
```

Vielleicht hat ja jemand eine Idee dazu. Ich kann das so auch erstmal so pushen bei Bedarf oder als Branch anlegen. Ich würde den Exporter in nen Extra Ordner im Hauptverzeichnis schmeißen wenn das passt.

**Comment by Dev-MarkoF** [comment]
At a quick glance...
Also technisch sollten es bei einem standard Cube 24 Normals, sein 12 Seiten, eine Seite besteht aus 2 Triangles, also 24 Normals, bei 8 Vertices. 

Ich hätte jetzt mal von Hand ausgerechnet, was die Normalen sein müssten. Ist ja für 8 Vertices machbar.
Dass du jetzt 48 Werte hast, deutet auf eine Dopplung einiger Werte hin, weshalb wahrscheinlich da einige Triangles so komisch sind.

**Comment by JirkaDellOro** [comment]
Es gibt mehrere Dinge zu beachten
- Beim Flat-Shading wird immer die Normale des dritten Trigonvertex als Flächennormale beim Shading herangezogen. Für andere Shader braucht man andere Normalen, Luis hat bereits Gouraud- und Phong-Shader geschrieben, wir müssen noch die Vertexnormalen dafür berechnen lassen, die sind derzeit noch nicht da.
- Es ist zu beachten, wie die Meshes aufgebaut werden. Der einfachste Fall ist, dass jedes Trigon eigene Vertices hat und damit unabhängig von allen anderen Trigonen. Dann stimmen auch eure Überschlagsrechnungen. Damit hat man aber eine Punktewolke mit vielen Vertices auf gleicher Position. Die Meshes von Robins Modeller sollten so aufgebaut sein.
- Andere generierte Meshes werden aber in der Regel anders aufgebaut, so dass ein Vertex von vielen Flächen genutzt wird. Dann muss man aber sehr aufpassen mit der Zuordnung der Normalen und der Texturkoordinaten, damit das Mesh beim Rendern funktioniert. 
- Der MeshCube in FUDGE besteht aus zwei ineinander gesteckten, zweifach gefalteten, C-förmigen Streifen. Innerhalb der Streifen werden Vertices mehrfach von Trigonen genutzt, die beiden Streifen aber sind völlig unabhängig. 
- Es kommt also darauf an, wie Blender die Meshes aufbaut. Möglicherweise ist es sinnvoll, beim Import alle Trigone zu isolieren. Dann hat man zwar keine Optimierung mehr, aber es sollte funktionieren.

Robin ist wahrscheinlich ein guter Ansprechpartner für die Problematik.

**Comment by SimonStorlSchulke** [comment]
> Möglicherweise ist es sinnvoll, beim Import alle Trigone zu isolieren. Dann hat man zwar keine Optimierung mehr, aber es sollte funktionieren.

Ja daran hatte ich auch schon gedacht - so kann ich das erstmal machen. Performancetechnisch hat man dann beim Würfelbeispiel halt im Vergleich zu 8 Vertices 36 - gleich mal die vierfache Menge. Die (Face)Normalen müssen dann aber eigentlich gar nicht vom Exporter gespeichert werden, sondern können direkt im Importer anhand der Vertices pro Face berechnet werden.

Ich kenne mich nicht so gut aus - aber auf Dauer wäre das vielleicht sowieso die bessere Option: Nur die Verticenormalen speichern (und auch als solche nutzen) und die Facenormalen einfach automatisch bei der Mesherzeugung generieren und separat von den vertexnormalen speichern.

**Comment by JirkaDellOro** [comment]
So sind wir das ja bislang angegangen, da die aktuellen Meshes grundsätzlich aus einem simplen Parametersatz generiert werden. Und die Superklasse Mesh verfügt bereits über eine generelle Methode zur Erzeugung der Facenormals, glaube ich.

**Comment by Robin-Sb** [comment]
> Performancetechnisch hat man dann beim Würfelbeispiel halt im Vergleich zu 8 Vertices 36 - gleich mal die vierfache Menge. 

Du brauchst nur 24, jeder Vertex ist ja grenzt ja an 3 Flächen, also brauchst du auch die dreifache Menge an Vertices.
Ich habe das nicht mathematisch erfasst, aber ich glaube auch, dass man diese Art der Datenhaltung braucht um alle beliebigen Meshes mit richtigen Normalen aufzubauen, jedenfalls liest man in der Literatur häufiger, dass ein Würfel aus 24 Vertices aufgebaut sein sollte. 

> Ich kenne mich nicht so gut aus - aber auf Dauer wäre das vielleicht sowieso die bessere Option für Meshes generell: Nur die Vertexnormalen speichern (und auch als solche nutzen) und die Facenormalen einfach automatisch bei der Mesherzeugung generieren und separat von den Vertexnormalen speichern.

Ich denke auch, dass das die beste Lösung ist und gehe auch davon aus, dass das gängigerweise so gemacht wird.

**Comment by SimonStorlSchulke** [comment]
Jo so hab ich's gemacht - funktioniert schon. Ich räum's morgen auf und pushe es. Texturkoordinaten sind halt nochmal komplizierter.

**Comment by Robin-Sb** [comment]
> Ne weil Cube hat ja nicht nur 6 Flächen sondern 12 (Triangles) - 12x3 = 36
Das stimmt, aber die beiden Berührungspunkte von den beiden Dreiecken einer Fläche haben ja auch die gleichen Normale, die kannst du ja wiederverwerten.
