### ISSUE TITLE
Blender (oa) to FUDGE Exporter - Dateiformat

### ISSUE THREAD

**Issue by SimonStorlSchulke** [JirkaDellOro/FUDGE#245]
[Hier](https://github.com/JirkaDellOro/FUDGE/tree/development/Miscellaneous/BlenderExporter) habe ich mal einen Exporter von Blender zu Fudge in unserem eigenen Format angefangen. Schaut mal rein. Der entsprechende Importer kommt dann demnächst aber vorher wollte ich noch das Dateiformat besprechen. 

Im Readme ist eine Beispieldatei, wie sie momentan aussieht. Unterstützde Objekttypen sind Meshes, Lichter, und Kameras. 

Es fehlt noch folgendes:

**Hierarchie**  
Von jedem Objekt wird die Lokala Transformationsmatrix (abhängig vom Parent) gespeichert. Daher wird die Platzierung von Objekten auch noch gar nicht richtig funktionieren bevor das drin ist.
Dafür würde ich einfach jedem Objekt einen "childs" Parameter geben, der dann weitere Objekte enthalten kann. 

~~**Die Möglichkeit, objektdaten von mehreren Objekten Nutzen zu lassen**~~  
EDIT: Schon erledigt. Objektdaten werden in separater Liste von Objekten gespeichert und Objekte referenzieren diese dann nur anhand des Objectdata Namens.

Material - aber da erstmal nur eine Farbe pro Objekt, keine Texturen. 

Fällt euch noch irgendetwas dazu ein?

**Comment by JirkaDellOro** [comment]
Ich glaube wir müssen dringend unterscheiden zwischen Dateien, die Meshes beschreiben und solchen, die ganze Szenen und die darin verwendeten Resourcen beschreiben. Bei letzterem musst Du dich an dem Format orientieren, das der FUDGE-Editor auswirft, in Editor unter Examples findest Du die entsprechenden JSON-Files. Du kannst dir mit dem Editor auch selbst welche generieren. Gerne gebe ich dir online eine Einführung.

Sonst kriegen wir drei Formate, das fände ich schade.

**Comment by SimonStorlSchulke** [comment]
> Sonst kriegen wir drei Formate, das fände ich schade.

Klar - ich hatte das Format eher als unsere Alternative zu GLTF gesehen. FudgeScene ist als Dateierweiterung wohl blöd gewählt - FudgeExchangeFormat oder so vielleicht eher. Aber wenn es einfach möglich ist direkt für das Editor Format zu exportieren, wäre das natürlich am besten, Ich schließe das hier, weil es ja schon eine Diskussion zu dem Issue gibt.
