### ISSUE TITLE
Fudge Editor // Internal Window // Entfernen Funktion

### ISSUE THREAD

**Issue by vale-sch** [JirkaDellOro/FUDGE#246]
Im Internal Fenster des Editors lassen sich Komponenten noch nicht per Shortcut oder Ähnlichem entfernen.

**Comment by JirkaDellOro** [comment]
Geht jetzt, es kommt ein Zwischenmenü das auf eventuelle Abhängigkeiten hinweist. Löschen von Resourcen, von denen andere abhängen ist nicht möglich, es können aber von dem Menü aus alle Ungenutzten gleich gelöscht werden. Bei den anderen muss man zuerst die Abhängigen löschen.
