### ISSUE TITLE
Physics: Collider feuert nicht

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#249]
siehe https://jirkadelloro.github.io/Prima/L03_Physics/FudgeBall.html

Der Goal-Collider ist zum Testen unter den Ball gelegt, es treten aber keine Events auf. Auf der Console sollte "Reset" erscheinen.

**Comment by Dev-MarkoF** [comment]
Ich schaue mal nach, aber da die Liste der Trigger in der Physik Welt stimmt. Musst du bei deinem "Refactoring" etwas in den Collision Funktionen kaputt gemacht haben. 
Ich finde es ein wenig konterintuitiv für jeden RB die Physik Anpassungsmethode aufzurufen, anstatt einmal für alle, ich verstehe den Ansatz der Ersichtlichkeit für Einsteiger, aber das verlängert Code ungemein.

**Comment by Dev-MarkoF** [comment]
Siehe #250
