### ISSUE TITLE
Physics: Seiteneffekte von Physics.start (jetzt adjustTransforms)

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#250]
siehe https://jirkadelloro.github.io/Prima/L03_Physics/FudgeBall.html

Tauscht man die Zeilen 50 und 51, so dass die Trigger definiert werden und danach erst die Collider-Transformationen des Playfields, scheinen die Trigger wieder auf die Identitätsmatrix zurückgeführt zu werden. Sie liegen aber nicht im playfield-Ast.

Code: https://github.com/JirkaDellOro/Prima

**Comment by Dev-MarkoF** [comment]
-> Testprobleme - Siehe "Collider feuert nicht".
Ich kanns/will es jetzt nicht kurzfristig nachvollziehen. 
Gehe aber davon aus, dass es natürlich zu unerwarteten Ergebnissen kommt. Wenn etwas definiert wird, es dann adjusted und danach etwas definiert was sich schon auf das adjusted bezieht. Vorher wurde alles definiert und danach alles auf einmal so adjusted wie der Tree es definiert.

**Comment by JirkaDellOro** [comment]
> was sich schon auf das adjusted bezieht  

Hast Du da etwas im Code gesehen?

**Comment by Dev-MarkoF** [comment]
Nein,
Ich weiß kurzfristig nicht was du falsch machst. Aber nachdem ich mal meine Event Testszene auf das "adjusting" System und neue Referenzen, was ich btw. nicht unterstütze, umgestellt habe (extra Codezeilen, Unübersicht, entgegen gängigen Systemen, etc.) 
Stelle ich fest meine Event Testszene (Tutorial 3) funktioniert einwandfrei. D.h. irgendwas läuft in deiner Prima #249 falsch, wofür ich jetzt zu viel Zeit aufwenden müsste. Es ist aber kein Problem von Fudge/Physik, sondern deinem Szenenaufbau.

**Comment by JirkaDellOro** [comment]
Also ein Problem konnte ich identifizieren. Wenn ich `adjustTransform` aufrufe, übergebe ich den Ast des Graphen, der dann von Render durchkalkuliert wird. Danach wird `updateWorldFromWorldMatrix` aufgerufen, worin aber alle der Physik bekannten Rigidbodies angepasst werden, nicht nur die des angegebenen Astes.

Jetzt habe ich Trigger, die bereits von mir explizit ihre Rigidbodies mit der gewünschten Transformation erhalten haben. Die werden nun auch angepasst, was nicht erwünscht ist.

Spricht etwas dagegen, wenn ich `updateWorldFromWorldMatrix` auch den Ast mitgebe und nur die Rigidbodies anpassen lasse, die auch zu dem Ast gehören?

**Comment by JirkaDellOro** [comment]
PS: ich habe es so verstanden, dass das ehemalige `start` lediglich die Rigidbodies angepasst hat und nichts wirklich "gestartet", deswegen die Umbenennung.

**Comment by Dev-MarkoF** [comment]
Stimmt, das Start hatte ich nur so benannt, weil ich dachte mit der Bezeichnung vergisst man es nicht anzuwenden.

Aber die Funktionalität dahinter ist die Anpassung und ein paar andere Dinge.
Es kann aufgrund von Javascript Callstack Reihenfolgen dazu kommen, dass die `Node,` `Transform `des Körpers nicht voll initialisiert ist, zu dem Zeitpunkt an dem die neue `adjustTransforms `angewandt wird, daher wird vermutlich das adjusting nicht korrekt ausgeführt.

Ich hatte das eben als `Start,` also finale Tätigkeit, vor dem 1. Frame angedacht, um dem Callstack Problem aus dem Weg zu gehen, da bis zu diesem Aufruf alle anderen Tätigkeiten, wie sämtliche Transformationen, Event Initialisierungen usw. abgeschlossen sein sollten.

Da die sehr einfach aufgebaute Testszene auch mit der neuen Herangehensweise funktioniert, aber die Prima Szene nicht, könnte das auf genau die Callstack Probleme hinweisen. Bin aber in dieser komplexen ganzen Asynchronität von Javascript noch nicht ganz drin.

**Comment by Dev-MarkoF** [comment]
@JirkaDellOro Jetzt hab ich das Problem endlich gefunden, habe ich total übersehen und natürlich nicht dran gedacht.

Zeile ~198+ ca. 
`        let triggerLow: ƒ.Node = new ƒ.Node("TriggerLow");
        triggerLow.addComponent(new ƒ.ComponentRigidbody(
            0, ƒ.PHYSICS_TYPE.STATIC, ƒ.COLLIDER_TYPE.CUBE, ƒ.PHYSICS_GROUP.TRIGGER,
            ƒ.Matrix4x4.CONSTRUCTION({ translation: ƒ.Vector3.Y(-5), rotation: null, scaling: new ƒ.Vector3(100, 10, 100) })
        ));`

Es wird eine Node gebaut ohne Transform Komponente, daran hängt sich die Physik auf. Weil die unbedingt eine will.

Bin mir nicht mehr sicher, warum ich es erlaubt habe das zu tun. Aber das ist, was zu den ungewünschten Seiten Effekten führt.
`AdjustTransforms `muss für alles ausgeführt werden, kann aber nur, wenn eine `Transform` bzw. irgendwelche Werte vorhanden sind.

Ich glaube du bist davon ausgegangen, dass du da den Pivot der Komponente einstellst. 
Das sollte vlt. auch so so sein, ist es aber leider nicht. Ich setze den `Pivot `im `Constructor `gar nicht. Das was man da herein gibt, ist nur eine `Initialisierungsmatrix`. Die in `AdjustTransforms / Start` von der echten `Transform `überschrieben wird. Es wundert mich, dass Javascript da keinen Fehler meldet, aber das ist halt typisch für die Sprache.

`Pivot `muss von Hand gesetzt werden, derzeit, hatte das Konzept des Pivots pro `Komponente` erst bedacht, als es schon komplex wurde, das müsste bei der Hereingabe im `Konstruktor `vermutlich gesetzt werden.

Der wird in der `AdjustTransform` ohne  gültigen Matrix versuchen durchzuziehen, daher kommt da so ein Ergebnis raus. Wo man den Collider der Initialisierung sieht. 
Aber der Collider, der nachher für die Trigger und andere Berechnungen genutzt wird, ist quasi `Matrix4x4 => null`. Und die Gruppe die erst nach der Collider Berechnung auf Trigger gesetzt wird, ist dann natürlich `default `und löst keine Events aus.

Folgendes ergibt sich jetzt dadurch:
a) Sollte vermutlich in ComponentRigidbody Contstructor -> mtxPivot gesetzt werden, mit der Hereingabe, die localTransform die derzeit nur für die Initialisierung genutzt wird.

b) Rigidbodies sollten nicht ohne Transform erstellt werden können. Ich würde die nicht automatisch mit generieren lassen, aber das in Konzepten logischer rüberbringen. Die `Transform `ist und bleibt der Kern des Austauschs der Physik zu Fudge, auch bei Triggern. Irgendwo müssen die Berechnungen abgelegt und synchronisiert werden.

**Comment by JirkaDellOro** [comment]
Wir sollten uns Gedanken machen, ob dann mtxPivot überhaupt sinnvoll ist. Wenn alles, auch Trigger. eine Knotentransformation brauchen, und diese mit dem Rigidbody überschrieben wird, erscheint mtxPivot irreführend.

Wo genau werden den die Knotentransformationen von der Physik überschrieben? Die Stelle habe ich noch nicht gefunden.

**Comment by JirkaDellOro** [comment]
Ich habe mal adustTransforms so angepasst, dass tatsächlich nur die Rigidbodies behandelt werden, die im angegebenen Ast liegen. Render füllt bei prepare ohnehin Arrays mit Referenzen um das spätere Zeichnen zu optimieren. Es werden nun auch die Referenzen auf Physikknoten gesammelt. ajdustTransform sieht so aus (in devJirka):

```typescript
    public static adjustTransforms(_branch: Node, _toMesh: boolean = false): void {
      Render.prepare(_branch);
      for (let node of Render.nodesPhysics)
        node.getComponent(ComponentRigidbody).updateFromWorld(_toMesh);
    }
```

Anfügen von Transform-Komponenten an die Trigger hat das andere Problem gelöst, jetzt kann man weiter denken über Optimierungen.

**Comment by Dev-MarkoF** [comment]
Physik überschreibt die Transform immer im Render Vorgang. `private static setupPhysicalTransform(_branch: Node): void` von Render.ts. Da überschreibe ich die `mtxLocal `der Node, was im Hintergrund sich bei der Transform meldet.

Den `mtxPivot` denke ich, ist nicht unnötig. Damit hat der Nutzer die Möglichkeit einen Collider zu erzeugen, der andere Maße hat, als die Transform. Der Pivot wird in der `updateFromWorld` berücksichtigt, er wird nur bisher nirgends gesetzt, wenn man nicht manuell `cmpRb.mtxPivot` setzt. Vermutlich kann die angesprochene eher unnötige `_mtxTransform` im Konstruktor durch den Pivot ersetzt werden. (Vorsicht, dann muss aber `createRigidbody(...)` auch angepasst werden).

Sehe ich das richtig, dass du die Kopplung von RB zu Transform aufheben möchtest, so dass diese Komponente nicht nötig ist? Dafür müsste im Rendering vermutlich Anpassungen gemacht werden. 

Iirc, wird doch die `mtxWorld `aus der `local` berechnet, mit Rücksicht auf Hierarchien und sofern eine `Local `vorhanden ist wird diese fürs Rendering benutzt? Die Physik überschreibt die `mtxLocal `anstatt der Welt, weil die Physik keine Transformations-Hierarchien kennt. 
Da muss also vermutlich eine Fallunterscheidung eingesetzt werden, damit die Physik bei allen Knoten ohne Transform, die `mtxWorld `überschreibt und bei allen mit die `local`.

Dann dürfte es theoretisch nicht nötig sein, dass eine Transform existiert. Dann ist der `mtxPivot `bei fehlender Transform und ohne absichtlichem Adjusting an Transform/Mesh, die relevante "Transformations"-Matrix. Entspricht dann nicht mehr der üblichen Vorgehensweise anderer Engines, aber ist konsistenter mit der Unabhängigkeit von Komponenten in Fudge.

**Comment by JirkaDellOro** [comment]
> Sehe ich das richtig, dass du die Kopplung von RB zu Transform aufheben möchtest,

Nein, ich weiß noch nicht, was ich will. Ich bin noch am rumschauen und mache nur kleine Verbesserungen und hoffentlich nix kaputt. 

mtxPivot erweckt den Eindruck, dass der Rigidbody gegenüber dem Knoten transformiert werden kann. Wenn ich das aber richtig verstanden habe, wird die Rigidbody-Transformation von der Physik auf die Knotentransformation übertragen, und damit ist der Eindruck falsch. Dann wird der Knoten "auf den Rigidbody gelegt" und mtxPivot ist ab da obsolet. Korrekt?

**Comment by Dev-MarkoF** [comment]
Irgendwie verrenne ich mich gerade in Reihenfolgen und Abhängigkeiten. 
Deshalb auch die Frage nach der Auflösung.

Es müsste folgendes nacheinander passieren.
1. BodyCreation (mtxTransform) -> Körper wird mit der Hereingabe erstellt
2. UpdateFromWorld vor dem 1. Frame -> Shape wird angepasst an cmpTransform + mtxPivot
3. Physik berechnet Ergebnisse -> Schreibt sie in mtxLocal

Damit ist der Pivot theoretisch unwichtig. Jetzt stimmt das aber nicht ganz, weil die Physik überschreibt nur rotation/translation. Skalierung bleibt für den Knoten erhalten. D.h. der Pivot ist für die Skalierung wichtig. Das habe ich deshalb gemacht, damit man den Collider unabhängig vom Mesh skalieren kann, das würde bei ebenfalls Überschreibung mit skalieren, sollte es vlt auch, aber abzüglich des Pivots vermutlich.

Da muss ich mir nochmal anschauen wie z.B. Unity das handelt. Ich gehe aber davon aus, dass da die Physik die oberste Priorität hat bei dynamischen Körpern. Der Pivot der Collider, in unserem Fall des ganzen Bodies, in den Berechnungen auch ganz einfach die Transform überschreiben, abseits der Skalierung. 
Dort hat ja keine Komponente einen Pivot außer der Collider und Joints.

Kanns aber gerade nicht sagen, muss ich überdenken. 
Stimmt schon der Pivot wirkt unwichtig, aber für die Skalierung auf jeden Fall doch nicht. Unabhängiges Skalieren von Collider zu Mesh muss gegeben sein, siehe Beispiel Charaktere, da wird immer der Collider angepasst. Aber eigentlich auch die Translation und Rotation... vlt. muss ich die noch bei der Rückübertragung von Oimo zu mtxLocal mit einbeziehen.

**Comment by JirkaDellOro** [comment]
Ich gehe davon aus, dass Du gerade nur darüber nachdenkst und nichts codest. Sonst wäre das ungünstig, da ich ja auch am Experimentieren bin und wir uns vielleicht unnötige Arbeit machen.

Ich will gerade einmal zwei Sache ausprobieren:
1. den Einbezug der Physik schon beim Render.prepare, weil mir aufgefallen ist, dass es ungünstig ist, wenn Knoten in einem Ast fertig durchkalkuliert werden und dann erst die Physik einen Elternknoten transformiert. Die Kinder kommen dann nicht mehr mit sondern erst im nächsten Frame. Man sieht das jetzt schon immer, dass die Meshes den Collidern einen Frame hinterher sind.
2. die Rücktransformation über den Pivot. Letztlich ist der Knoten eines Rigidbodies nur eine grafische Repräsentation desselben, so wie alle Kindknoten darunter, sofern diese nicht auch wieder Rigidbodies haben. Ich muss ja Objekte erstellen können, die aus vielen Teilen bestehen, sich als Gesamtheit aber einfach als Cube verhalten.  Durch die Rücktransformation würde der Pivot des Rigidbodies wieder mehr Sinn ergeben, da Knoten und Rigidbody dann dauerhaft gegeneinander transformiert sein können. Ich denke, so macht Unity es auch.

**Comment by Dev-MarkoF** [comment]
Ja ich denke nur darüber nach. 
Weil ich auch gern ein paar Unity Sachen nochmal ausprobieren will, weil die schon etwas weiter zurück liegen
und ich meist nur noch mit Verwaltungssoftware Entwicklung zu tun habe, keine Simulationen/Games.

Gebe nur meine Gedanken weiter, code da nichts spezifisches.

1. Würde den Einbezug der Physik in Render.prepare, die Physik nicht tiefer in Fudge integrieren? Ich hatte eher an eine Auslagerung gedacht. Ja die Schere zwischen 1 Frame ist nicht lösbar ohne tiefere Integration, die wollte ich aber vermeiden, wegen der Modularität von Fudge.

2. Also derzeit, wenn der Parent 1 Body ist und die Kindknoten alle Knoten nur mit Transform/Mesh. Dann verhalten sie sich in der Gesamtheit als Cube (bzw. Collider des Parent). Fügst du Kindern auch Bodies zu, trennen sie sich von den Eltern. So arbeitet Physik. Das mache ich schon wie Unity. Der Pivot des gesamten Objektes ist demnach der eine RB und seine Transformation.

Empfohlen wird deshalb immer, 1 GameObject zu machen, was den RB und Collider erhält und alle visuellen Elemente ohne Körper darunter. Knoten untereinander werden nicht mit dem RB gegengerechnet. Das Kind weiß nichts von der Physik, es bewegt sich halt mit, weil das Elternobjekt sich bewegt. 
Physik -> TransformLocal (parent) -> TransformLocal (kind). 

Das ist ja schon der Fall, oder habe ich das Vorhaben von 2. falsch verstanden?

**Comment by Dev-MarkoF** [comment]
Ich sehe da so keine Problemstellen.
Finde es auch gut, dass eine Node ein Parent braucht, das sollte ja durch den Graph Root auch immer gegeben sein.
Werde es zu gegebener Zeit mal anschauen.

Zum Zeitpunkt des Rendervorgangs hat die Physik ihre Berechnungen schon durchgeführt, da `simulate` vor `draw` im Update kommt, daher ist es richtig, dass kinematische da 1 Frame hinterher hängen, weil die ihre neue Info von transformByPhsics erst im nächsten ins Update mit einbringen.

Den Error bei fehlender Transform finde ich gut, aber vlt. kann man diese Notwendigkeit, wie oben beschrieben eliminieren. Habe am Wochenende mal nochmal mit Unity abgeglichen und die bisherige Funktionalität entspricht dem dortigen Vorgang. Allerdings kennt Unity natürlich das Konzept eines Pivots auf Komponenten so nicht. Nur der Collider hat einen Pivot.
