### ISSUE TITLE
Physik Debug - Draw Raycast before simulate, instead of after 

### ISSUE THREAD

**Issue by Dev-MarkoF** [JirkaDellOro/FUDGE#255]
@JirkaDellOro 
Habe es mir mal angeschaut.
Es stimmt, intuitiver wäre es wenn die Raycasts gezeichnet werden würden, wenn man sie vor dem `physics.simulate()` macht und simulate die Physik quasi abschließt für den Frame.

Ich stoße dabei auf folgendes Problem. Das Debug besteht aus eigenen Buffern, die dann in den Kontext von Fudge gezeichnet werden. Die Buffer werden in der `simulate()` geleert mittels `begin()`, der debugDraw von Oimo befüllt aus der dann simulierten Welt den Buffer. Das tatsächliche Zeichnen ist dann im Render z. 153 das `end()`, da werden die gefüllten Buffer gezeichnet.

Wenn wir den Raycast quasi nach der Simulate ausführen ist er 1 Frame verschoben 
(wobei das kein Problem darstellt, 3-5 Frames gelten als nicht wahrnehmbar, zumal der Strahl nur 1 Frame existiert). Da aber die Intuition ist zuerst zu Casten und dann zu simulaten, wäre eine Umstellung gut.

Aber dafür muss der Zeichenbefehl für den Raycast nach dem **leeren** kommen. Das lässt der Programmcode so nicht zu, ich schlage daher eine Zwischenspeicherung aller Zeichenbefehle vor. Und im Schritt, simulate(), wird dann eine drawDebugRays() aufgerufen, die für jeden Strahl im Array den Zeichenbefehl ausführt, nach der Leerung. Anschließend wird das Array geleert.

Dadurch ist sichergestellt, dass Strahlen gezeichnet werden die sowohl vor als nach der Simulate ausgeführt werden.
 
Idee: 
Denkbar wäre da die Erweiterung in diesem Array eine Dauer bzw. ein ExpirationDate mit einzuspeichern, d.h. es wird nicht das gesamte debugRays[] gelöscht, sondern nur die abgelaufenen. Das gäbe die Möglichkeit, wie in Unity einen Strahl für eine Dauer sichtbar zu lassen, auch wenn die Physik nicht mehr damit arbeitet, für verbessertes Debugging eines z.B. Schusses, der ja nur in einem Frame und nicht kontinuierlich ausgeführt wird.

**TL;DR;**
- Aufgrund der Reihenfolge des Buffers, muss bisher der Raycast nach dem simulate() erfolgen. Der Leervorgang des DebugDraw Buffers muss aber so bestehen bleiben.

- Mittels eines Zwischenspeicher Arrays (mehr Overhead), könnte aber Möglichkeit geschaffen werden, die Raycasting vor/nach dem simulate() frei erlaubt. Zudem wäre es möglich den Raycast für eine gegebene Dauer, immer zu zeichnen (z.B. Debugging eines Einzelschusses, analog zu Unity)

- Habe das jetzt nur mal getestet, wenn das aber gewünscht ist, kann ich das mal ordentlich reincoden und irgendwie pushen.

**Comment by JirkaDellOro** [comment]
Mein erster Vorschlag wäre ähnlich: dass man Extra-Buffer für die Rays macht, diese am Ende des simulate zeichnet und danach löscht. Dann sind sie im nächsten Frame leer. 

Vielleicht könntest Du das aber auch einfach grundsätzlich bei simulate machen, dass Du die Zeichenbuffer am Ende löschst und nicht "erst" am Anfang? Dann wären sie also am Ende von simulate leer und man könnte sie im nächsten Frame noch vor simulate schon z.B. mit Rays befüllen?

Das mit der Dauer erscheint mir jetzt zu viel Aufwand für den Effekt.

**Comment by Dev-MarkoF** [comment]
Könnte man andenken, ich werde mal etwas coden, wenns reinpasst. 
Dürfte ja keine allzu hohe Prio gerade haben, die Raycasts nach dem Simulate zu setzen.

Ich finde den Aufwand für den Effekt eigentlich angemessen, habe ich innerhalb der Thesis auch noch nicht gedacht. 

Aber wenn ich mich zurück an meine Bachelor Thesis erinnere, wie oft ich in einem Shooter einen Schuss debuggen muss, der üblicherweise per Klick in einem Frame gestartet wird, aber dann auch beobachtet werden sollte, dann halte ich es für angemessen. Alle anderen Buffer werden gelöscht, es wäre nur der "neu" angedachte Raycast Buffer, der eben zeitlich relevant gelöscht wird. 
Ist für Nutzer denke ich angenehmer für Raycasts in den Settings eine allgemeine Löschzeit anzugeben, anstatt für jeden Ray, wie in Unity. Aber insgesamt eine angenehmere Lösung, als eine schon programmierte Gameplay Mechanik, wie einen Schuss, aus einer fixen Eingabe, in eine kontinuierliche Eingabe zu verlagern.
