### ISSUE TITLE
Trigger testet gegen BoundingBox?

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#256]
Bitte mal das ausprobieren:

https://jirkadelloro.github.io/Prima/L05_PhysicsGame/PhysicsGame.html

An eine freie Stelle fahren und den Avatar drehen. Der Trigger vor dem Avatar scheint mit den Ecken einer BoundingBox um den Avatar zu kollidieren. In Zeile 59 kann man die Distanz des Triggers einstellen, ab 1.8 kommt keine Kollision mehr. Ist das so korrekt oder ein Bug?

**Comment by Dev-MarkoF** [comment]
Fast korrekt, es wird nicht gegen die Bounding Box getestet, sondern gegen die Axis Aligned Bounding Box,
die ist bei Drehung ggf. noch größer als die Bounding Box, da sie immer zur Grundachse X,Y parallel verläuft.

Ist in der Thesis beschrieben, wieso AABB's existieren wird (Performance) und warum das mit Oimo momentan nicht anders funktioniert. Ich hatte wie in #258 beschrieben den Entwickler darauf aufmerksam gemacht. Dies ist aber nicht nur ein Oimo Problem, Trigger bzw. Ghostbodies sind in Physik Engines immer ein Afterthought, da sie nicht Teil einer Realphysik sind, sondern nur von GamePhysics.
