### ISSUE TITLE
Time Test: Game_time Skaliert nicht richtig

### ISSUE THREAD

**Issue by DavidNiemann** [JirkaDellOro/FUDGE#261]
In dem Test zu Time funktioniert die Skalierung der Game_time nicht richtig.
Beim Einstellen einer Skalierung vor dem Wechsel des Modus in Game_time werden die Skalierungen wie erwartet berechnet.
Befindet man sich im Game_time Modus wird die erste Umstellung der Skalierung richtig berechnet, die darauf folgenden Umstellungen der Skalierung führen zu unerwarteten Ergebnissen.

Link zum Code 
[https://github.com/JirkaDellOro/FUDGE/tree/DavidTest/Test/Time](https://github.com/JirkaDellOro/FUDGE/tree/DavidTest/Test/Time)

**Comment by JirkaDellOro** [comment]
Die Tests habe ich nun lektoriert und in development integriert. Bitte teste mal den Time-Test und schließe den Issue, wenn er bei dir funktioniert.

**Comment by DavidNiemann** [comment]
Der Time Test skaliert jetzt bei mir richtig.
