### ISSUE TITLE
FUDGE Physics // Gravitationsachse einstellen 

### ISSUE THREAD

**Issue by luca1107** [JirkaDellOro/FUDGE#262]
Hey, bisher ist es glaube ich nicht möglich die Achse zu ändern, auf der die Gravitation wirkt. Das wäre super wenn das irgendwie möglich wäre einzustellen.

Liebe Grüße

**Comment by luca1107** [comment]
# # @Dev-MarkoF

**Comment by luca1107** [comment]
@JirkaDellOro

**Comment by JirkaDellOro** [comment]
Im Menü rechts kannst Du die Assignees einstellen, wenn Du möchtest, dass eine bestimmte Person angesprochen werden soll. Ich setzte hier mal Marko ein, er kann am besten Auskunft geben. Du kannst auch einstellen, dass es eine Frage und kein Bug ist. 

PS: Wahrscheinlich kannst Du auch selbst einen Methode für die Physik schreiben, die deinen Wunsch an OIMO weiterleitet.

**Comment by Dev-MarkoF** [comment]
Hi,
Mir ist nicht ganz klar was du erreichen möchtest. Die gesamte Gravitation lässt sich über eine Funktion `Physics.setGravity `als Vector3 setzen. Das gilt dann für die gesamte Simulation, einzelne Körper müsstest du von Hand machen. 

Dafür kann man bei jedem RB gravityScale einstellen auf 0, dann nimmt er nicht mehr an der Simulationsgravitation teil. Im Grunde ist eine Gravitation nur eine Beschleunigung in eine bestimmte Richtung, wenn du das also für jeden Gegenstand einzeln setzen möchtest musst du dann jedem RB die entsprechende Beschleunigung pro Frame addieren.

**Comment by JirkaDellOro** [comment]
@luca1107 Damit müsste sich deine Frage beantwortet haben, korrekt?

**Comment by luca1107** [comment]
@JirkaDellOro @Dev-MarkoF 
Jup hat sich hiermit erledigt.

Danke
