### ISSUE TITLE
joints | spielt verrückt wenn Kinderknoten Rigidbodykomponenten besitzen

### ISSUE THREAD

**Issue by vido-bit** [JirkaDellOro/FUDGE#263]
Besitzt die connected Node eines Joint Kinderknoten, so bewegen diese sich bei Drehung des Gelenks ordnungsgemäß mit dem elterlichen Knoten mit. Gibt man den Kinderknoten jedoch eine Rigidbodykomponente mit PHYSICS_TYPE.KINEMATIC, so spielt die gesamte Szene verrückt und alles bugt wild durcheinander.

**Comment by vido-bit** [comment]
@JirkaDellOro @Dev-MarkoF

**Comment by Dev-MarkoF** [comment]
Die ist ein beabsichtigtes Verhalten.
Physik kann KINEMATIC nicht verarbeiten, kinematisch ist nur eine Hilfestellung um das theoretisch Konstrukt der Mathematik mit der Realität der Physik zu verbinden. 
D.h. dass kannst du verwenden um z.B. eine Spielfigur mittels Transformationen zu steuern anstatt Kräften und dennoch Körper beeinflussen z.B. Gegenstände schieben. Der Gegenstand kann allerdings den kinematischen Körper nicht beeinflussen, denn dann müsste die Physik ja die Mathematik hinter dem Objekt kennen und das kann nicht passieren.
Daher gilt es diesen Typ von Körper nur gezielt einzusetzen. 

Physik ignoriert, der Realität entsprechend das mathematische Konstrukt, daher können Körper nur über Gelenke oder physikalische Gesetze verbunden werden. Hat Objekt A einen Rb, ist also ein Körper, dürfen Childnodes keine RB's sein, damit diese zum parent gehören, wenn du irgendeinen RB hinzufügst, unterliegen diese der Physik und damit wird die Knotenhierarchie ignoriert. Es gibt keine Eltern-/Kindbeziehungen in der Physik. 
Ohne Kleber/Schraube o.ä. würden zwei Holzteile auseinanderfallen, egal ob du ihnen sagst, sie gehören zusammen oder nicht. 

In deinem Fall hast du eine Struktur die nicht möglich ist, du versuchst 
Objekt A zu sagen -> dynamischer Körper
B/C zu sagen -> ihr gehört "theoretisch" zum dynamischen Körper, aber ihr seid kinematisch, also macht bitte nichts was die Physik euch sagt.

--> in Folge dessen dreht die Physik natürlich durch, weil versucht wird die constraints vom joint zu enforcen, aber deine Objekte das mathematisch ablehnen.

Was hast du den vor, wofür du das verwenden wolltest? 
Wenn du sagen wir mal einen Gegenstand bauen möchtest der aus mehreren Teilen besteht, die zusammengehören und der insgesamt auf die Physik reagieren soll, dann benutzt man besser eine Basisnode, welche einen RB besitzt und alle children sind ohne. Dann passt man den Collider der Basisnode so an, dass alle children mit in der Hülle sind.

**Comment by vido-bit** [comment]
Hi Marko, vielen dank für die ausführliuche Antwort. Ich würde gerne ein neigbares Labyrinth bauen, durch das eine Kugel zu einem Loch geführt werden soll. Die Neigefunktion wollte ich durch einen sphericalJoint implementieren und alle Labyrinth-Barrieren sollten bei jeder Neigung, ihre Position auf der Plattform natürlich behalten. Ist es überhaupt möglich den Collider hierfür anzupassen?

![marbleMaze]
![marbleMaze](https://user-images.githubusercontent.com/64126756/124452058-54067e80-dd86-11eb-85c2-4966023d2a02.jpg)

**Comment by Dev-MarkoF** [comment]
Nette Idee, würde ich anders angehen, vermutlich ganz ohne Joints, sehe nicht wo man die sinnvoll verwenden sollte.
Typischerweise, würde man auf eine Plane, als Hauptkörper die ganzen Wände anheften und die Wände bräuchten dann Collider. 
Alles wäre kinematisch, nur der Ball dynamisch.

Hab das mal kurz ein ganz kleines Test Tilt Maze gebaut, nur kugel, boden,wände.
Das funktioniert, wenn du:
1. MazeNode kreierst, eine leere Node, nur TransformComponent und wichtig Scaling muss Identity sein.
2. Boden/Wände/Hindernisse als kinematische Körper erstellst, die an MazeNode parentest.
3. Kugel als dynamischen Körper erstellt.
4. Per Input die MazeNode tiltest.

-> In dem Fall folgen die Wände/Boden, der Hierarchie, weil sie kinematisch sind, der tiltung der MazeNode, haben aber trotzdem einen Einfluss auf die Kugel. In dem Setup sind erstmal nur statische Hindernisse vorgesehen, dieses Setup ist die standard Herangehensweise an Tilt Maze Games. Von da aus kann man natürlich erweitern.

**Comment by JirkaDellOro** [comment]
@vido-bit 

Danke, dass Du die Diskussion zu github verlagert hast, dann kann auch Marko mithirnen. Also es geht ja schon, dass man Dynamik und Kinematik kombiniert, man muss halt einiges beachten. Und wir wollten ja auch schauen, wie das ganze per Gelenk aussehen würde. Den oben beschriebenen Ansatz haben wir bereist bei MazeBall von Matthias Roming. 

Schau dir mein aktuelles Beispiel an;   
https://jirkadelloro.github.io/Prima/L03_Physics/FudgeBall.html
da habe ich der Tür noch einen Knauf spendiert, jetzt mit kinematischem Kollider. Der bewegt sich mit der von der Physik bewegten Tür.

Zwei DInge sind mir bei deinem Ansatz aufgefallen:
1. Du hast zwar ein Gelenk eingesetzt, scheinst dann aber das bewegliche Teil kinematisch bewegen zu wollen, also nicht nur durch Kräfte. Das sollte problematisch werden.
2. Es dürfen keine Kollisionen zwischen dem dynamischen Elternobjekt und seinen kinematischen Kindern auftreten. Klar, sonst schubsen sie den Elternknoten herum an dem sie aber selbst hängen und Du hast ein Perpetuum Mobile. Deswegen sitzt bei mir der Knauf-Collider auch außerhalb des Tür-Kolliders.

@Dev-MarkoF 
Mit welchem Kommando kann man die Kollisionsprüfung zwischen bestimmten Gruppen unterdrücken?

**Comment by Dev-MarkoF** [comment]
@JirkaDellOro 
Der Befehl ist RB.collisionMask(mask).
Dabei ist die Mask aber eine Bit Summe an Zahlen, bin da mit dem System von Oimo nicht ganz zufrieden, hätte das gern wie Unity als Matrix, wer collided mit wem realisiert. In Oimo gibt man an, welche Gruppen colliden (steht aber auch in der Typedef), z.B. `collisionMask(PHYSICS_GROUP.DEFAULT | PHYSISCS_GROUP.GROUP_1 | etc)`. 
Vorsicht! Die Gruppe lässt sich absichtlich nur vor Beginn der Simulation einstellen, Oimo mag das sonst nicht so gerne, kann man ändern, aber führt zu Berechnungsfehlern.

Exakt, das meine ich, es kann natürlich Gelenke geben mit kinematischen ChildNodes, aber ein kinematisches Objekt kann nicht Teil des Gelenks selbst sein. Der Knob in dem Fall ist ja nicht Teil des Gelenks, das Gelenk besteht auch bei dir nur aus dynamic/static Bodies.
Aufgrund der beschriebenen Vorgänge, 
kinematisch -> kann nicht von der Physik gesteuert werden, sondern durch Transform Relations
Gelenk -> Muss sich an Physik Restriktionen halten.

**Comment by JirkaDellOro** [comment]
@vido-bit 
Wie gehst Du weiter vor? Ich bin jetzt wieder gut zu erreichen und schaue gerne mit rein.

**Comment by vido-bit** [comment]
@JirkaDellOro 
Ich habe das nochmal genauso probiert mit einem Gelenk zu lösen, auch ohne dass die Nodes kollidieren. Es treten jedoch nach wie vor ungewünschte Effekte auf, sodass ich es vorgezogen habe, es ohne Gelenk weiter zu versuchen und bin bisher auch zu einer zufriedenstellenden Alternative gekommen indem ich einfach die Elternnode in eine gewisse Richtung rotieren lasse. Ich bin momentan auch sehr bei meinen anderen Prüfungen eingespannt, weshalb ich die letzten Tage aber noch nicht groß weiterarbeiten konnte.

**Comment by JirkaDellOro** [comment]
Dann kann man den Issue schließen, denke ich, da es wohl nicht an der Physik selbst liegt.
