### ISSUE TITLE
Rigidbody Physics Type durch Kollision ändern

### ISSUE THREAD

**Issue by luca1107** [JirkaDellOro/FUDGE#264]
@JirkaDellOro @Dev-MarkoF 
Hallo ihr zwei, ich habe eine kleines Problem mit der Rigidbody Komponente, vlt liegt es auch am Code und nicht an der Komponente selbst.

export class Einzelgeometrie extends ƒ.Node {
    static mesh: ƒ.Mesh = new ƒ.MeshCube("Cube");
    static material: ƒ.Material = new ƒ.Material("Black", ƒ.ShaderUniColor, new ƒ.CoatColored(new ƒ.Color(0, 0, 1, 1)));
    **rigidbody: ƒ.ComponentRigidbody = new ƒ.ComponentRigidbody(1, ƒ.PHYSICS_TYPE.KINEMATIC, ƒ.COLLIDER_TYPE.CUBE, ƒ.PHYSICS_GROUP.DEFAULT);**  _// Hier erzeuge ich den Rigidbody, erstmal Kinematic, sodass er von der Physik unberührt bleibt, bis er mit einem Objekt kollidiert_
    direction: boolean ;

    constructor(_name: string, _pos: ƒ.Vector3, _scale: ƒ.Vector3, _dir: boolean ) {
      super(_name);

      this.addComponent(new ƒ.ComponentTransform());
      this.mtxLocal.translateX(_pos.x);
      this.mtxLocal.translateY(_pos.y);
      this.mtxLocal.translateZ(_pos.z);

      let cmpMesh: ƒ.ComponentMesh = new ƒ.ComponentMesh(Einzelgeometrie.mesh);
      cmpMesh.mtxPivot.scaleX(_scale.x);
      cmpMesh.mtxPivot.scaleY(_scale.y);
      cmpMesh.mtxPivot.scaleZ(_scale.z);

      this.direction = _dir;

      this.addComponent(cmpMesh);

      this.addComponent(new ƒ.ComponentMaterial(Einzelgeometrie.material));
      this.addComponent(this.rigidbody);
      **this.rigidbody.addEventListener(ƒ.EVENT_PHYSICS.COLLISION_ENTER, this.activatePhysics);**  _//Hier setze ich den Event Listener für die Kollision_ 
    }

    public setTransform(_pos: ƒ.Vector3, _rot: ƒ.Vector3): void {
      this.mtxLocal.translateX(_pos.x);
      this.mtxLocal.translateY(_pos.y);
      this.mtxLocal.translateZ(_pos.z);

      this.mtxLocal.rotateX(_rot.x);
      this.mtxLocal.rotateY(_rot.y);
      this.mtxLocal.rotateZ(_rot.z);

    }

    public move(): void {
      if (!this.direction)
      this.mtxLocal.translateX( - 1 / 4 * ƒ.Loop.timeFrameReal / 1000);
      else
      this.mtxLocal.translateX(  1 / 4 * ƒ.Loop.timeFrameReal / 1000);
    }

    **private activatePhysics(_event: ƒ.EventPhysics): void {
      console.log("Col");
      this.rigidbody.physicsType = ƒ.PHYSICS_TYPE.DYNAMIC;
    }**  _// Hier die Funktion zum ändern des Physic Types des Rigidbodys des Objektes bei welchem eine Kollision stattfindet_

  }
}

Die Kollisionsabfrage funktioniert und es wird in der Konsole eine Kollision ausgegeben, Fehlermeldung gibt es auch keine, jedoch passiert nichts und der Rigidbody bleibt weiterhin Kinematic

LG Luca

**Comment by JirkaDellOro** [comment]
Poste bitte Links zu Quellcode auf Github und zur App auf Pages. Dann ist es für uns viel besser möglich das zu untersuchen

**Comment by Dev-MarkoF** [comment]
Code sieht eigentlich clean aus, wenn die Collision registriert wird, ist auch schonmal gut.
Sehe intern auch kein Problem `set physicsType` macht vom Code her was es soll.
Kurzer Test in dem ich per Tastendruck einen Body von Kinematic auf Dynamic setze geht auch problemlos.

Ich muss Jirka da zustimmen, ich bräuchte den ganzen Source Code / Link zum Repository.

**Comment by luca1107** [comment]
https://github.com/luca1107/Prima_Abgabe_360_Defender

Hier ist der Link zum aktuellen Repository.

Für Pages muss ich erst noch erstellen .

Alles klar Marko, ich versuche das heute mal zu testen und gebe nochmal bescheid :)

Liebe Grüße

**Comment by luca1107** [comment]
Also ich habe es über Tastendruck versucht und jetzt funktioniert es 👯 

Woran liegt es dann, dass es bei der Kollision nicht funktioniert, bzw. was muss ich ändern dass er die Rigidbody-Änderung wie bei der Tasteneingabe ändert ?

Liebe Grüße

**Comment by Dev-MarkoF** [comment]
Es liegt nicht an der Physik, so viel kann ich schonmal sagen. 

Habe kurzfristig, meine Tutorial 3 - Physical Events Szene umgebaut, so dass der Collider bei Berührung anstatt seiner bisherigen Funktion von Kinematic auf Dynamic springt und das funktioniert einwandfrei, also quasi derselbe Versuchsaufbau wie bei dir.

Da es mit Tasteneingabe bei dir auch funktioniert ist, das also schon mal safe.
Ich schau mir mal dein Code an, wenn es mir zeitlich reinpasst.

**Comment by luca1107** [comment]
Hey Marko, super viele Danke für die ausführliche Erklärung und die Logik die dahinter steckt. Sehr interessant und gut zu wissen für die Zukunft, dass das so intern gehandhabt wird.

Ich werde deine Antwort mal in mein Projekt einbauen und melde mich nochmal ob soweit alles geklappt hat. Aber ich denke wird haben hiermit das Problem gefunden.

Nochmal vielen Dank und schönen Abend 

LG Luca

**Comment by luca1107** [comment]
Hey , ich habe noch ein kleines Problem damit.

Und zwar kann ich nicht direkt auf this.rigidbody referenzieren und muss noch davor nach .getComponent(ƒ.ComponentRigidbody) suchen. Hierbei bekomme ich den Fehler "xy is not a function" .

Habe es dann so versucht 

 this.rigidbody.addEventListener(ƒ.EVENT_PHYSICS.COLLISION_ENTER, this.triggerPhysics);

private triggerPhysics (): void
    {
      this.activatePhysics();
    }
    

    private activatePhysics(): void {
      console.log("Col");
      this.rigidbody.physicsType = ƒ.PHYSICS_TYPE.DYNAMIC;
    }

Auch hier der Fehler

**Comment by luca1107** [comment]
Ich habe die Kollision jetzt über die Kugel ausgelöst, jetzt funktioniert es.

Mich würde jetzt interessieren, wie es möglich ist , ein Rigidbody mitsammt dem Node welches des RB enthält zu löschen. 
Ich frage nach dem Namen des kollidierten Objektes, jedoch weiß ich nicht wie ich es löschen soll, da ich ja in einer seperaten Objektklasse die Kollision abrufe und somit noch auf den Wurzelknoten Zugriff habe.

LG

**Comment by luca1107** [comment]
Ich bin mit der Kollision noch nicht so zufrieden, irgendwas läuft da noch nicht richtig, was ich nicht verstehe. Er schmeißt Errors beim RB, aber nur manchmal.

Könntest du dir es mal anschauen ?

**Comment by Dev-MarkoF** [comment]
Habs mir angeschaut, da kommt wieder verschiedenes Zusammen.

a) Du brauchst kein _`event.cmpRigidbody.getContainer().getComponent(ƒ.ComponentRigibody). ....` das Event enthält den getroffenen Body, also deine "enemy". 

b) Die Fehler kommen, weil du versuchst den _event.cmpRigidbody.setVelocity() mit this.velocity zu füttern, was sich wieder auf die beschriebene Problematik bezieht, dass .this nicht der vermutete Wert "Kugeln" ist, auf dem die Property velocity liegt, sondern der Event Auslöser -> also die ComponentRigidbody. Das ist aber auch gut, weil du die Class Property nur im Constructor verwendest, wo du einmal die Velocity vom Rigidbody setzt, danach würdest du aber die Geschwindigkeit vom Körper bekommen -> this.getVelocity() ist die Funktion die Geschwindigkeit vom Körper am Ende der Kollision zu bekommen.

c) Dieser Ansatz ist aber auch physikalisch erstmal Falsch, den das getroffene Ziel bekommt ja nicht automatisch die Geschwindigkeit des Projektils, von dem es getroffenen wurde, Trägheit etc. spielen da noch eine Rolle. In deinem Game ist das oft sogar eine negative Geschwindigkeit, weil die Kugeln ja auch abprallen, also fliegen die Enemies dann auf dich zu, wenn sie einfach die Kugelgeschwindigkeit übernehmen.

Ich gehe davon aus, dass du sie "wegballern" möchtest. Logischerweise wendest du also den Impuls des Projektils auf den getroffenen Körper übertragen. 
```
          _event.cmpRigidbody.applyImpulseAtPoint(new ƒ.Vector3
            (_event.collisionNormal.x * _event.normalImpulse, _event.collisionNormal.y * _event.normalImpulse,
              _event.collisionNormal.z * _event.normalImpulse), _event.collisionPoint);
```
-> Der getroffene Körper, bekommt den Impuls trefferNormale * trefferIntensität, angewendet am getroffenen Punkt. D.h. wenn du die obere Ecke eines Feindes anschießt, dann wird auch von genau da der Impuls ausgelöst. Vorsicht Impulse sind recht kräftig stark.

Wie man Körper mit Node löscht? Einfach die ganze Node löschen, dann wird auch der Körper mit gelöscht. Das Löschen geschieht, wenn das nicht zwischenzeitlich verändert wurde, durch das Entfernen der Node aus der Hierachie, also deinem Szenenroot.

**Comment by luca1107** [comment]
Hey Marco erstmal vielen Dank für deine Antwort.

Ich habe noch das Problem, dass wenn ich die Node entferne aus ihrem Elternknoten, dass der Rigidbody an der Stelle weiterhin verbleibt, obwohl die Node aus der Szenenhierachie entfernt wurde. 

LG

**Comment by luca1107** [comment]
Die Impulsweitergabe an der jeweiligen Position funktioniert sehr gut

**Comment by Dev-MarkoF** [comment]
@luca1107 Danke guter Hinweis, es wird tatsächlich beim Remove der Node nicht die ComponentRigidbody Remove Funktion aufgerufen, diese Funktioniert zwar intern korrekt, aber da kommt kein Event von der Node, dass dieses Auslöst, das ist ein allg. Fudge Problem. Wenn du bevor du die Node entfernst, den RB noch entfernst, dann hat sich dieses Problem derzeit gelöst, das kann sogar sein, dass es Absicht ist und meine Physik Implementierung falsch ist.

Lösung derzeit: 
```
_event.cmpRigidbody.getContainer().removeComponent(
_event.cmpRigidbody.getContainer().getComponent(ƒ.ComponentRigidbody));

gameRoot.removeChild( [...]
```

Es kann trotzdem zu Fehlern kommen, wie "can't get Contact of Null", weil wenn du zu schnell schießt versucht die Physik Collision Events zu berechnen, mit einem RB der bereits weg ist. Ich schau, dass ich da noch einen besseren Check in der Zukunft einbaue, momentan einfach ignorieren.

Deine Kugeln fliegen derzeit noch etwas komisch, du gibst denen immer einen Initialspeed in dieselbe Richtung, 
`  this.velocity = new ƒ.Vector3(_pos.x * 2 , _pos.y * 2 , .3);`
das solltest du noch anpassen, die sollten Velocity in die Richtung bekommen in der Player derzeit schaut. 
Dazu übergibst du der Kugel am besten die komplette WorldMatrix und Transformst damit einen Forward Vector, diesen Multiplizierst du mit der Schussstärke die du willst. Allerdings bin ich mir nicht ganz sicher wie dein Szenenaufbau aussieht, wer da welche Rotation etc. hat, das musst du selbst rausfinden.
  
@JirkaDellOro` Node.removeChild(Node)`, ruft nicht das Event EVENT.COMPONENT_REMOVE in den Components der entfernten Node auf. Ist das gewollt? Physik und Audio Components sind die einzigen, die diese Funktion von Node derzeit selbst implementieren.

**Comment by JirkaDellOro** [comment]
EVENT.COMPONENT_REMOVE wäre auch das falsche Event, da ja nicht eine Komponente vom Knoten, sondern der Knoten von seinem Parent entfernt wird. Hier sollte CHILD_REMOVE gefeuert werden. Siehe 
https://jirkadelloro.github.io/FUDGE/Documentation/Reference/Core/enums/fudgecore.event.html#child_remove

**Comment by Dev-MarkoF** [comment]
Muss früher anders gewesen sein, EVENT.COMPONENT_REMOVE ist ebenso in der Audio und Animator Component als das Event welches gefeuert wird, bei der Beseitigung der Komponente. 

Die Komponente sollte als Folge der Löschung der Node auch mit beseitigt werden oder? Als Nutzer gehe ich zumindest davon aus.
Sonst muss in Zukunft jede Physik Komponente halt noch auf das EVENT.CHILD_REMOVE hören.

**Comment by JirkaDellOro** [comment]
"Löschung der Node" gibt es nicht in Javascript/Typescript, daher kann man das auch nicht abfangen.

**Comment by Dev-MarkoF** [comment]
@JirkaDellOro So war es auch nicht gemeint, my bad ging da vom Falschen aus. Hab das aus Reflex wie Unity gedacht, nicht wie Fudge.

Ich ging davon aus, dass wenn man von einer Node, dass Child removed die Components auch removed werden. 
Aber es stimmt, so funktioniert das hier im Zusammenhang wirklich nicht, da das Child vom Root entfernen dieselbe Vorgehensweise ist, wie das Child von irgendeiner Node entfernen und da sollten die Components natürlich erhalten bleiben.

Den Graphen und die Physik zu synchronisieren, wäre vermutlich auch wieder ein ungewollter Automatismus, der würde ja jetzt im gegebenen Fall für den Kreateur den Rigidbody entfernen, wenn er die Node "löscht", dass soll ja nicht geschehen. Durch umhängen wird die Physik ja bereits aktualisiert durch ComponentAdd/Remove Event. Daher stimmt das obige, @luca1107  du musst den Body manuell entfernen, das ist so gedacht.

_PS:
Hab OimoPhysics auch mal selbst compiled und ein paar Anregungen die bisher noch keiner bearbeitet hat übernommen. 
Erster Test für "Formgenaue" Trigger ist in langsamer Arbeit, ich sende bereits das OimoEvent und verwerfe die Kollisionsverarbeitung, aber auf Fudge Seite hab ichs noch nicht angefasst._

**Comment by JirkaDellOro** [comment]
> PS: Hab OimoPhysics auch mal selbst compiled und ein paar Anregungen die bisher noch keiner bearbeitet hat übernommen.
Erster Test für "Formgenaue" Trigger ist in langsamer Arbeit, ich sende bereits das OimoEvent und verwerfe die Kollisionsverarbeitung, (funktioniert noch nicht ganz korrekt), aber auf Fudge Seite hab ichs noch nicht angefasst.

👍
