### ISSUE TITLE
Abnormales Verhalten von Texturen bei der Ausführung mit MacOS

### ISSUE THREAD

**Issue by ParadoxMike** [JirkaDellOro/FUDGE#265]
Beim Ausführen von FUDGE Code unter MacOS werden Texturen in sich selbst verschoben und erst garnicht gerendert wenn keine Node mit Unicolor Shader existiert. 

Problem aufgetreten mit den Folgenden Systemen: 
iMac 27" Late 2013, GeForce GTX 780M, MacOS 10.14.6
MacBook Pro 15" Retina Mid 2014, GeForce GT 750M, MacOS 10.15.7

Links:
Lauffähige instanz mit Warkaround: https://paradoxmike.github.io/PRIMA-SoSe21/TexureDemo/mainHTML.html
Info & Screenshot: https://paradoxmike.github.io/PRIMA-SoSe21/TexureDemo/

**Comment by JirkaDellOro** [comment]
Bitte poste einen Link auf eine ausführbare Demo-App in Pages und ein Vergleichsbild von deinen Systemen, so dass David schnell erkennen kann, ob es auch auf modernen Macs so aussieht

**Comment by DavidNiemann** [comment]
Gleiches Problem wie bei Visual Novel im Discord,
man muss in den Settings von Chrome chrome://settings auf Advanced -> System und "Use hardware acceleration when available" Checkbox umstellen, dann Chrome neu starten.

Dann sollte es auch auf mac ohne Workaround funktionieren.

Ich habe bisher keine andere Lösung gefunden.

**Comment by JirkaDellOro** [comment]
Haben wir das schon im FUDGE-Repo beschrieben? Am besten im Wiki eine Troubleshooting-Seite anlegen.

**Comment by DavidNiemann** [comment]
Nach meinem Wissen steht es noch nirgendwo. Ich werde es Ins Wiki schreiben.

**Comment by JirkaDellOro** [comment]
Ja, und trage dort auch zusammen, was Du z.B. für Linux rausgefunden hast etc.

**Comment by JirkaDellOro** [comment]
+ Browsereinstellungen z.B. für Dialog-Element und private fields

**Comment by ParadoxMike** [comment]
Super danke!
