### ISSUE TITLE
Max frametime for Physics

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#266]
Wenn der Browser lagt, man Tabs wechselt etc. kommt es zu langen Dauern für einen Frame. Werden diese der Physiksimulation übergeben, sind die Änderungen zu groß und Kollisionen werden verpasst. Hier sollte mit einer maximalen Dauer experimentiert werden, die genutzt wird, wenn sie von der tatsächlichen überschritten wird. das bremst zwar das Geschehen, könnte aber eine Abhilfe für Glitches sein, die das Spiel zerstören. Gegebenenfalls kann diese Maximaldauer parametrierbar in die Physik eingebaut werden.

**Comment by Dev-MarkoF** [comment]
Habe es so im großen Physik Update eingebaut, dass wenn die FrameTime zu klein wird, eine Konstante FrameTime von 30 Frames angenommen wird. 
Muss ggf. getestet werden, ich habe mit dieser Variante keine Probleme feststellen können in meinem Test, aber mein Testgerät ist auch recht leistungsfähig.

**Comment by JirkaDellOro** [comment]
Es ist auf jeden Fall im Sinne der Zielsetzung von FUDGE, dass wir das selbst angeben können. So wird es sichtbar und man kann darüber diskutieren und schließlich lernen. Ich denke auch, dass es manche Anwendungen gibt, bei der die Physik durchaus in einem groberen Zeitraster arbeiten kann, da spart man Energie, .z.B. wichtig auf Mobilgeräten
