### ISSUE TITLE
Physic-Refaktorierung und Tests

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#278]
Ich habe Markos Tests in das offizielle Testverzeichnis kopiert und entsprechend des aktuellen Standes der Physik refaktoriert. Alle Tests laufen noch/wieder.

@Dev-MarkoF bitte schau durch, ob sie sich so verhalten wie Du erwartest. Ich habe zudem das Standardtemplate vornedran geschnallt, das jetzt mit den richtigen Texten versehen werden kann. Es wäre klasse, wenn Du hier ein paar Zeilen schreibst, dann kann nämlich jeder testen und qualifizierte Rückmeldung geben.

**Comment by JirkaDellOro** [comment]
Achtung: aktuell in devJirka

**Comment by Dev-MarkoF** [comment]
Ich schaue rein, was ist mit "richtigen" Texten gemeint? Hatte meistens schon etwas dazugeschrieben, wenn auch oft eilig.

**Comment by JirkaDellOro** [comment]
"Richtige Texte" meint entsprechend des Templates, das wiederum ist im Template beschrieben.

**Comment by JirkaDellOro** [comment]
Magst Du da noch etwas schreiben in den HTML-Templates? Ich halte die Tests weiter am Laufen...

**Comment by Dev-MarkoF** [comment]
Leider komme ich mit dem derzeitigen Stand von Fudge nicht mehr ganz mit, hab mir
mal den momentanen "development" branch geladen und ich sehe da keinen Bedarf für mehr Erklärung.

Bei allen Beispielen ist alles nötige beschrieben (allerdings sind die Tutorials/Experiments gerade nicht lauffähig ist mir aufgefallen), aber du hast jetzt einen Extra Ordner Test dort werden sie lauffähig gehalten?

Da sollten aber vlt. noch die Tutorials rein, da die extra für Studis gebaut und erklärt worden sind. Die Tests sind natürlich nicht erklärt, die sind aber auch nicht so gedacht gewesen, weil die für Studis unübersichtlich programmiert worden sind und wirklich nur da sind um zu testen das "alles" funktioniert wie gewünscht. 

Das **Joint-Car** ist da eh ein Spezialfall, da ich damit nie fertig geworden bin braucht das auch nicht lauffähig gehalten werden (ist auch ein wahnsinniger Aufwand realistisch Joints anstatt Raycast zu verwenden, weil man das ganz genau einstellen muss, das wird vermutlich nie fertig werden).

Ich hatte mich auch mal an eine Implementation von Heightmaps/Terrain für OIMO drangesetzt, aber auch noch nicht wirklich voran gekommen.

Was ist den der wirklich aktive Branch? Wenn Änderungen/Erklärungen gewünscht werden, wohin committen? Wird devMatze gerade fortgeführt, ist in meinem Tree der aktuellste branch.

**Comment by JirkaDellOro** [comment]
development ist der jüngste "offizielle", an devJirka probiere ich die meiste Zeit, in devMatze integriere ich gerade das Skelettsystem. Du solltest development nehmen.

Es geht um die Texte die erscheinen, wenn der Test startet, nicht um ein Extra-Dokument.

**Comment by Dev-MarkoF** [comment]
👍 Alles klar, ich schau bei Gelegenheit mal rein und schreib etwas.

**Comment by Dev-MarkoF** [comment]
@JirkaDellOro 
Erledigt, Texte sollten sinnvoll sein.
Tests habe ich teilweise sinnvoll ergänzt z.B. Kontrolle über Simulationsgeschwindigkeit, bei
schnell Vorgängen etc.
Habe noch die Tutorials auf den neuesten Stand gebracht, die sind wichtiger, fürs Verständnis,
auch wenn die weniger Funktionalitäten abbilden als die Tests.

Mir ist aufgefallen, dass m Zuge des Refactorings keinen Zugriff mehr auf die **OimoWorld** von der Physics Basisklasse drin ist, das sollte definitiv wieder rein, vor allem der Zugriff auf die **SolverIterations** muss gegeben sein, vorher über Physics.world geregelt, für komplexe Szenen ist das von Vorteil.

Was ist der Gedanke hinter Variablenbenennungen mit # vor dem Namen? Z.B. #mainCamera in Physics.ts, konnte ich nicht ganz nachvollziehen, ist dies ein Schema um etwas zu verdeutlichen?

**Comment by JirkaDellOro** [comment]
Hallo Marko,

gut dass dir das aufgefallen ist. Es wäre gut, wenn Du das mit dem Zugriff und den SolverIterations fixen könntest und einen kurzen Kommentar dazu schreibst, warum es vorteilhaft ist.  Ich erinnere mich, dass ich damit nicht anfangen konnte und wohl vermutet hatte, dass es versehentlich im Zugriff war. 

# ist ein neues Javascript-Feature. Es sind private fields, die also auch tatsächlich zur Laufzeit privat sind, nicht nur auf der Precompile-Ebene von TypesScript. Wo möglich, nutze ich diese nun und trage nach, um die Zugriffssicherheit zu erhöhen.

**Comment by Dev-MarkoF** [comment]
Gut zu wissen interessantes Feature.

Habe SolverIterations jetzt als Teil von Settings etabliert, sowie den Zugriff auf die OimoWorld wieder erlaubt,
beides beschrieben und im Test JointCar kommt der Zugriff auf die Solver Iterations auch zum Einsatz, dort 
kann gut beobachtet werden, wie sich die extra Präzision auswirkt auf die Qualität der Simulation.

**Comment by JirkaDellOro** [comment]
Die Shader wurden erweitert und damit auch die Coats. CoatColored ist nur noch mit ShaderLit zu gebrauchen, hier wird nicht auf Licht reagiert. Lichtsensitive Shader brauchen jetzt CoatRemissive oder Varianten davon, die Informationen zu diffusen und spekularen Remissionsanteilen enthalten. Ich habe das nachgetragen in den Tests.

Ein Test scheint gerade nicht mehr zu laufen: Phase2_Integration_Events.

**Comment by Dev-MarkoF** [comment]
Ah gut zu wissen, interessante Entscheidung einen RemissiveCoat zu etablieren, natürlich das sinnvolle Gegenstück zum Emissive, aber liest man doch selten.

Hab das bei allen Tutorials/Test angepasst und auch die Funktionalität überprüft. Test2 Events geht, aber ich hatte ihn abgeändert, dass die Zeitskalierung bei 0 startet und durch Tastendruck erhöht/gesenkt werden kann. Bei den Tests gibt es ja dieses Dialogfenster was sich automatisch beim Laden öffnet, das ist für einen selbst ablaufenden Test unpraktisch, da das Fenster dann immer schnell geschlossen werden musste. 
Für selbstablaufende Tests ist es eh praktisch die Geschwindigkeit, anhand jetzt hier der TimeScale einstellen zu können, damit Phänomene korrekt beobachtet werden können.

Dann denke ich passt jetzt alles, im Bereich Physik funktioniert das so wie ich mir das vorstelle, ich versuche auch mal wieder mehr mit den Entwicklungen mitzukommen.

**Comment by JirkaDellOro** [comment]
Bei Remissive kommt wieder die Lehre ins Spiel. Es haben sich in der Branche falsche Begriffe eingebürgert und die sollte ich nicht wiederholen, auch wenn es dann vielleicht sehr akademisch klingt. Zum Beispiel müsste Emissive eigentlich Licht emittieren und damit andere Objekte beleuchten. Daher heißt der bei uns Lit, also "beleuchtet" nicht "leuchtend" (wobei das im Englischen auch ambivalent ist). Wobei Remissive auch anderes beleuchten müsste, aber hier wird klar, dass es beleuchtet werden muss... es ist kompliziert.

Ich habe bei den TestInstructions nun noch ein Parameter `_open` hinzugefügt. Wenn der den Wert `false` hat, wird der Dialog nicht automatisch geöffnet. Da müsste man dann ggf. im Text des Tests noch unterbringen, dass man ihn mit Ctrl+F1 öffnen kann. Ich habe das bei den fallenden Stühlen mal eingebaut. 

Ich hatte die Coats schon verändert auch in den anderen Tests, allerdings nicht darauf geachtet, dass ich da gerade auf devJirka war. Habe jetzt gemerged, sollte alles passen.

**Comment by Dev-MarkoF** [comment]
Finde das mit dem automatisch öffnenden Dialog durchaus gut, so bekommt man direkt erst einmal die Instruktionen.

Das war jetzt nur bei den wenigen selbst ablaufenden Tests in meinem Fall nur bei einem ungünstig und das kann man ja mit der TimeScale sehr gut umgehen, das hätte ich da von Anfang an drin haben sollen, da Events in Realtime eh nicht so gut betrachtet werden können. Die Option das automatische Öffnen zu unterbinden ist natürlich auch gut, mehr Optionen schaden nie.

Vielen Dank für die Herleitung der Benennung, sehr interessant, hatte den Begriff wirklich bisher im Zusammenhang mit Material/Shader noch nicht gehört.
