### ISSUE TITLE
Not launching in Mac OS

### ISSUE THREAD

**Issue by philippjenny** [JirkaDellOro/FUDGE#283]
When starting FUDGE on a Mac it only shows an empty window
![Screenshot 2021-10-07 at 15 08 24](https://user-images.githubusercontent.com/42078113/136565355-b06eb0a7-3fe0-42fa-a782-ec3c9e124138.png)

**Comment by JirkaDellOro** [comment]
Please test the new version and send screenshots

**Comment by JirkaDellOro** [comment]
I tested it myself now on the lab-mac. Works like charm. Beware, on the mac you need to use chrome to view your projects at this time.

**Comment by JirkaDellOro** [comment]
Is this done? Please close
