### ISSUE TITLE
Fudge Editor inserts error message into game html

### ISSUE THREAD

**Issue by AljoshaVieth** [JirkaDellOro/FUDGE#287]
When saving in the FUDGE Editor (without any changes made), an error message get´s generated and inserted into the game .HTML.

The bug occurred when working on [this](https://github.com/AljoshaVieth/Prima/tree/769167e6b066b18a2108d885b74f530e0525c40f/projects/LaserLeague
) project (this very commit).

https://user-images.githubusercontent.com/12802765/140935064-2da4119e-6ac9-483e-b4f8-755ae6daabd3.mp4

![image](https://user-images.githubusercontent.com/12802765/140936950-3968d7e0-2430-4978-acdf-039dc32aae45.png)

**Comment by JirkaDellOro** [comment]
Lass' uns mal Versionen vergleichen. Ich habe
electron 12.0.2 (hier kann ich mir vorstellen, dass Du etwas Neueres hast, da könnte es knirschen)
typescript 4.5.0-Beta (hier genügt aber garantiert 4.4.0)

**Comment by AljoshaVieth** [comment]
Ich habe auch Electron  12.0.2.
Hatte TypeScript 3.8.3, habe gerade mal auf 4.4.4 geupdated, das Problem bleibt aber bestehen.
Fudge hatte ich heute direkt vor der Vorlesung gepullt.

**Comment by JirkaDellOro** [comment]
Poste mal bitte diesen Error-Tag, der eingefügt wird. Auf dem Video ist er nicht vollständig zu sehen. Gibt es zudem eine Fehlerausgabe in der Konsole? Aus diesen Infos kann ich mir vielleicht etwas reimen. Ansonsten müssten wir mal eine Fernwartung per Discord machen. Bist Du morgen erreichbar?

**Comment by AljoshaVieth** [comment]
In der Konsole kommt nur `MenuSelect: Item-id=undefined`. In der Konsole der Developper Tools im Editor selbst kommt keine Ausgabe.

Die Fehlermeldung im .html :
```HTML
<parsererror style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black">
<h3>This page contains the following errors:</h3>
<div style="font-family:monospace;font-size:12px">error on line 100 at column 82: Specification mandates value for attribute disabled
</div>
<h3>Below is a rendering of the page up to the first error.</h3>
</parsererror>
```
![image](https://user-images.githubusercontent.com/12802765/140996464-9be5894b-cca0-4cf9-a284-20d39251f6c9.png)

Zeile 89 ist die letzte Zeile innerhalb des script-Tags:

```JavaScript
[...]
    })(document.head.querySelector("meta[autoView]").getAttribute("autoView"));
</script>
```

Morgen kann ich eventuell spontan ab 18:00 Uhr, genau kann ich das aber erst morgen Nachmittag sagen.

**Comment by JirkaDellOro** [comment]
Ok, vielen Dank. Ich hab's, konnte es reproduzieren. Chromium warnt bei Parsen von HTML vor Attributen, denen kein Wert zugeordnet ist, obwohl Browser diese in der Regel bedingungslos akzeptieren. Die Warnung wird in die HTML-Seite geschrieben.

Lösung:
in deinem Hud, schreibe statt nur `disabled` das Attribut mit Wert, z.B. `disabled = "true"`. Widersinnig ist, dass es mit `false` wahrscheinlich den gleiche Effekt hätte, da der Wert ignoriert wird. Aus formalen Gründen scheint Chromium darauf zu bestehen ihn zu haben, um ihn dann zu ignorieren. 🙄

**Comment by JirkaDellOro** [comment]
Ich habe nochmal geschaut, ob ich dem Parser das abgewöhnen kann und gesehen, dass als `xhtml+xml` geparsed wurde, was viel strenger ist. Jetzt parsed der Editor als `html` und damit sind auch "wertlose" Attribute akzeptiert. Allerdings fügt der Parser dabei selbst leere Strings `=""` bei diesen Attributen ein, also nicht wundern....

Ich glaube, ich kann jetzt selbst den Issue schließen und ihr öffnet ihn wieder, falls doch noch etwas klemmt.
