### ISSUE TITLE
API Reference page not working

### ISSUE THREAD

**Issue by UmbertoFalkenhagen** [JirkaDellOro/FUDGE#288]
Hey,

I am trying to go on the API references page, but seemingly its not working...

![image](https://user-images.githubusercontent.com/48802310/142207096-eb5bf370-2b8c-40dd-bbdf-3bbb69cdb8f6.png)

Cheers,
Umberto

**Comment by JirkaDellOro** [comment]
Ich habe da rumgebastelt, über welchen Link bist Du gegangen?

**Comment by JirkaDellOro** [comment]
Ah... über's Wiki. Hab's gefixt und leite über die Start-Page
