### ISSUE TITLE
Error when adding a child node in scene graph

### ISSUE THREAD

**Issue by UmbertoFalkenhagen** [JirkaDellOro/FUDGE#289]
Hey, when I try to add a child node to one of my existing nodes I get the error which can be seen in the screenshot. This hasn't happened so far and it happens on all of my nodes.
![image](https://user-images.githubusercontent.com/48802310/144407113-51f36c41-3f39-4ff7-949f-baddd942b4bb.png)

Is this a known issue/ does anyone know how to solve it?

**Comment by UmbertoFalkenhagen** [comment]
Okay so apparently this problem seems to be linked to the ComponentTransform of an object. Adding a child node to a node without a transform component works, but once an object has a transform the error occurs...

**Comment by UmbertoFalkenhagen** [comment]
Once an object has a transform component, something odd happens: Whenever I try to select the node in the scene graph hierarchy (for example when trying to add a new child node) the editor automatically selects the transform component in the node, as hopefully might be visible in the screenshot. this happens straight away when I click on the node in the hierarchy.
![image](https://user-images.githubusercontent.com/48802310/144408433-a32b7810-a200-4aee-94e8-a0249f180d9c.png)

**Comment by JirkaDellOro** [comment]
fixed that yesterday, check newest version

**Comment by JirkaDellOro** [comment]
close when done

**Comment by JirkaDellOro** [comment]
@UmbertoFalkenhagen ???
