### ISSUE TITLE
Raycast "schießt" in die falsche Richtung

### ISSUE THREAD

**Issue by Jonathan-Schnee** [JirkaDellOro/FUDGE#290]
## Expected Behavior
Der Raycast soll von einer bestimmten Position in eine Richtung "schießen" mit einer bestimmten Länge.

## Actual Behavior
Der Raycast Endpoint ist immer in der Nähe des Worldorigin. und ignoriert die Länge die man festlegt.
![grafik](https://user-images.githubusercontent.com/48802338/147688902-339f7333-7c47-4372-b70e-b639f49fdd84.png)
in der Nähe einer Wand zeigt er zwar drauf aber trotzdem noch mit einer Richtung zum Mittelpunkt.
![grafik](https://user-images.githubusercontent.com/48802338/147688936-a52035cd-f7b2-448e-8083-41eb9b887be1.png)

## Code
    let direction = ƒ.Vector3.Y()
    let rayL = ƒ.Physics.raycast(agent.mtxWorld.translation, direction, 1, true)

**Comment by Jonathan-Schnee** [comment]
Nach etwas rumgeteste habe ich herausgefunden, das die Funktion getRayEndPoint in der Physics.ts Probleme macht. Ich weiß nicht wieso aber anscheinend ändert er nach ausführen der Zeile 103 die Variable "origin" zu dem selben Wert wie "direction". Ich habe es nun mit einem Umweg zum laufen gebracht.

Das ist mein Umweg:

    let direction = ƒ.Vector3.SUM(agent.mtxWorld.translation, ƒ.Vector3.Y())
    direction.x /= 2
    direction.y /= 2
    direction.z /= 2
    let rayL = ƒ.Physics.raycast(agent.mtxWorld.translation, direction, 1, true)

Hier ein Bild wie es nun aussieht:
![grafik](https://user-images.githubusercontent.com/48802338/147712524-1b7a96c4-0249-4cd2-867a-da390552ab87.png)

Was genau den Wertwechsel verursacht hab ich leider noch nicht herausgefunden.

**Comment by JirkaDellOro** [comment]
Gut möglich, dass es eine verfrühte Optimierung war. Ich habe eine Änderung im Core vorgenommen, bitte erneut ziehen und testen.

**Comment by Jonathan-Schnee** [comment]
Es funktioniert nun wieder, danke.
