### ISSUE TITLE
RigidBody isInitalized auf false setzten bringt Fehler

### ISSUE THREAD

**Issue by Jonathan-Schnee** [JirkaDellOro/FUDGE#291]
Wenn man ein RigidBody die Variable isInitalized auf false setzt um ihn neu berechnen zu lassen ( zum Beispiel nach einer Scale Veränderung) bekommt man den Fehler "A rigid body cannot belong to multiple worlds". Obwohl in der Doku steht das man diese nach Veränderungen auf false setzen soll.

**Comment by JirkaDellOro** [comment]
Das ist wahrscheinlich ein Seiteneffekt meines jüngsten Fixes. Falls es noch relevant ist, stattdessen die removeComponent und addComponent aufrufen, initialize ist da implizit mit drin, aber der body wird damit auch aus der Welt gelöscht.

**Comment by JirkaDellOro** [comment]
Ich habe nun Unterstützung für verschiedene Welten implementiert, wobei weiterhin ein Rigidbody nur einer angehören kann. Es ist aber möglich, dass das Problem hiermit gefixt ist, es Bedarf eines Tests.

**Comment by JirkaDellOro** [comment]
... vieler Tests!

**Comment by JirkaDellOro** [comment]
Es ist so einiges passiert, der Fehler dürfte nicht mehr relevant sein.
