### ISSUE TITLE
Multi Select - Editor

### ISSUE THREAD

**Issue by vale-sch** [JirkaDellOro/FUDGE#296]
Multiselect im Editor funktioniert nur so halbwegs. Vorallem eine visuelle Feedback fehlt noch.

**Comment by vale-sch** [comment]
Sieht für mich so aus als würde es wieder funktionieren. Innerhalb des Multiselects gleiche Komponenten zu verändern war bisher noch nicht geplant?

**Comment by JirkaDellOro** [comment]
Das könnte man danke der Mutatoren eigentlich relativ leicht implementieren. Ich kann mir aber vorstellen, dass für dich noch interessanter sein könnte, was ich gerade auf meinem devJirka-Branch implementiert habe, nämlich dass Subgraphen mit und über ihr Original synchronisiert werden. Bei meinem Kugellabyrinth-Prototypen habe ich damit gearbeitet, aber das Prefab-System von Unity kam an seine Grenzen. Das FUDGE-System muss noch ausgiebig getestet werden, daher zeige ich es dir gern in einer Session,

**Comment by vale-sch** [comment]
Ja können wir uns gerne mal anschauen.
