### ISSUE TITLE
Editor not working with exported variables

### ISSUE THREAD

**Issue by SorayaFe** [JirkaDellOro/FUDGE#303]
Hat man eine exportierte Variable (z.B.:  export let movingDirection: string = "y";) dann lässt sich das Projekt im Editor nicht öffnen.
![image](https://user-images.githubusercontent.com/64090992/162204164-00f0517b-c35a-435e-8f24-1c8e056162ea.png)

**Comment by JirkaDellOro** [comment]
Alter Bug der jetzt erst hochkam, wo wir den Editor intensiv nutzen. Ich merge gleich meinen Branch, dann bitte FUDGE aktualisieren.
