### ISSUE TITLE
Negative Scaling malfunction

### ISSUE THREAD

**Issue by RolandHeer** [JirkaDellOro/FUDGE#304]
Problem mit Pacman, der in der scaling abfrage immer 1 hat, selbst wenn der Wert negiert wurde

**Comment by JirkaDellOro** [comment]
Mich dünkt, es gibt ein Problem mit dem Rückrechnen der Euler-Winkel bei einer Spiegelung. Ich gehe der Sache nach.

Als Lösung/Workaround
Wie im Seminar erwähnt, oft ist es besser die Informationen selbst mitführen und der Renderengine übergeben, als Informationen daraus abzufragen. Ich habe meine Transformation in Abhängigkeit von der Bewegungsrichtung so implementiert:


      sprite.mtxLocal.set(ƒ.Matrix4x4.IDENTITY());
      sprite.mtxLocal.scaleX(direction.x < 0 ? -1 : 1);
      sprite.mtxLocal.rotateZ(direction.y * 90);

Es wird also immer erstmal die Transformation auf die Identitätsmatrix zurückgesetzt und dann von dort aus mit meinen Infos manipuliert. So bin ich nicht auf einen vorangegangenen Zustand angewiesen.

**Comment by JirkaDellOro** [comment]
Ok, ich habe einen Bug gefunden, das Vorzeichen ging bei der Extraktion der Skalierung aus der Matrix verloren. Daher war dann auch die Winkelberechnung bei Spiegelung nciht mehr korrekt. Ich habe einen Fix implementiert, bin aber noch nicht sicher, ob der ganz vollständig ist. Es wäre sehr interessant zu wissen, ob dein Pacman, so wie Du ihn hattest, als Du auf den Fehler stießt, mit der neuesten FUDGE-Version funktioniert.

**Comment by JirkaDellOro** [comment]
Achtung, ich habe das wieder revidiert. Im Editor konnte ich testen und es gab viele Nebeneffekte. Essenz: die Rücktransformation ist problematisch, daher besser Information immer in eine Richtung wandern lassen, von der App zur Engine.
