### ISSUE TITLE
Point Light

### ISSUE THREAD

**Issue by Tobias-Bodmer** [JirkaDellOro/FUDGE#305]
Point Lights implementieren.

**Comment by JirkaDellOro** [comment]
Jawoll!

**Comment by JirkaDellOro** [comment]
Melde Vollzug!

Ich werde das die Tage noch optimieren, aber es scheint schon gut zu funktionieren, probiert es aus. Beachtet: derzeit ist Phong-Shading noch nicht wirklich implementiert, nutzt Gouraud. Hier werden die Lichtberechnungen der Vertices über die Fläche linear interpoliert. Bei großen Flächen mit wenigen Vertices und nahen Lichtquellen treten dann scheinbar widersinnige effekte auf. Die Fläche müsste stark beleuchtet sein, aber da die Vertices sehr schräg angeleuchtet werden, wird sie dunkler. Sagt bescheid, wenn Phong erforderlich ist, dann wird pro Pixel die Beleuchtung berechnet. 

Bei dem Punktlicht ist jetzt die Pivotmatrix voll im Einsatz, das habe ich mal ausprobiert. Translation erklärt sich von selbst. Die Skalierung bestimmt die Beleuchtungsreichweite, bei der Standardskalierung von 1,1,1 leuchtet das Licht bis zu einem Meter in alle Richtungen, die Intensität fällt linear vom Zentrum zur Reichweite ab. Ihr könnt auch ungleich skalieren, dann gibt es keine Leuchtkugel sonder ein Leuchtei oder eine Leuchscheibe. Mit der Rotation kann man die dann drehen, da kann man interessante Effekte erzeugen.

Viel Spaß und gerne viele Bugs melden!

**Comment by JirkaDellOro** [comment]
eben noch einen Naming-Bug gefixt. Hier könnt ihr euch das übrigens in Aktion anschauen
https://jirkadelloro.github.io/Prima/Pacman/
