### ISSUE TITLE
Error when using imported OBJ Meshes

### ISSUE THREAD

**Issue by nathanielkeeler** [JirkaDellOro/FUDGE#307]
First of all, after importing a .obj file into the internal resources, it is not displayed in the preview. Only in some rare cases will it be displayed, but not properly. It seems to be file dependent because some .obj never show while others only show this way. See Screenshot below.
![Screenshot 2022-04-21 131707](https://user-images.githubusercontent.com/62625108/164446916-59fbd438-2164-448c-9260-ed869bb3728b.png)

When using the .obj Mesh as ComponentMesh and after adding a ComponentMaterial to it, I get the following error:
![Screenshot 2022-04-21 131431](https://user-images.githubusercontent.com/62625108/164446495-c13e7145-c1c9-4b01-b924-08890df1cbf1.png)

Tried creating my own Mesh in Blender as well, doesn't work that way either.

**Comment by JirkaDellOro** [comment]
Please see Test/Mesh, there is an OBJ file there that loads (4th from the left when you start the test). The importer is rudimentary and certainly has some restrictions. Compare the file with yours to see what needs to be done and write this down here, please, so that other can follow your guidance.

**Comment by JirkaDellOro** [comment]
any news?

**Comment by JirkaDellOro** [comment]
Ist das durch? Oder gibt es noch Probleme? Sind die erforderlichen Einstellungen gefunden?

**Comment by nathanielkeeler** [comment]
Hat soweit alles geklappt, nachdem Roland seine Blendereinstellungen im Unterricht erläutert hat

**Comment by JirkaDellOro** [comment]
Dann bitte schließen!

-- 
​Mit den besten Grüßen
Jirka R. Dell'Oro-FriedlProf. Dipl.-Ing. (FH), 5. Dan
Software & Games | Design & Development
Spiellabor M007 | Tel:07723-920-2569
Hochschule Furtwangen University

Gegendert mit dem geschlechtergerechten Neutrum

Am Sonntag, Juni 26, 2022 15:30 CEST, schrieb Nathaniel Keeler ***@***.***>:
 
 
Hat soweit alles geklappt, nachdem Roland seine Blendereinstellungen im Unterricht erläutert hat
