### ISSUE TITLE
Editor: Drag and Drop

### ISSUE THREAD

**Issue by plojo** [JirkaDellOro/FUDGE#310]
When dropping a resource over its corresponding component (i.e. a MeshCube over ComponentMesh) the resource gets replaced in the component. Which is the expected behavior.

![image](https://user-images.githubusercontent.com/38690628/165087033-b690fb17-38e1-465a-9f95-496d48aa5f01.png)

But at the same time ViewComponent is also trying to create a new component with the resource attached to it leading to this error:

![image](https://user-images.githubusercontent.com/38690628/165087769-7b8f1d52-d810-4027-ad10-aff1d6a5680d.png)

Shouldn't the component creation only happen if the resource is dropped over an empty space in ViewComponents?

**Comment by JirkaDellOro** [comment]
The View listened in the capture phase, so first it tried to attach a new component, then the event was passed to the existing one. Changed that. Testing needed to watch out for side effects, if listining in the capture phase had some reason...

**Comment by plojo** [comment]
ok, I will watch out for side effects
