### ISSUE TITLE
FUDGE stürzt ab wenn man 2mal den gleichen Graphen für eine Hierarchy benutzt

### ISSUE THREAD

**Issue by Duvid19** [JirkaDellOro/FUDGE#312]
Wenn man 2mal den gleichen Graphen für eine Hierarchy benutzt
![image](https://user-images.githubusercontent.com/91938270/166422852-c98c240b-36d2-4913-b0a8-21594841f636.png) 

und in diesen die jeweiligen Meshes verändert kommt in der Console diese Fehlermeldung: 
![image](https://user-images.githubusercontent.com/91938270/166423046-e48d9402-6e94-4f98-9e4b-f2a82613b686.png). 

Der Fehler kann bis zu 1000 hochgehen und alles darüber hinaus stürzt das Programm dann ab und man kann nichts mehr anklicken. 
Wenn man dann FUDGE neustartet und dann nochmal auf den gleichen Graphen klickt, kommt der gleiche Fehler nochmal und wenn der Error weit über 3000 ist kann man nicht mal ein neues Projekt starten.

**Comment by JirkaDellOro** [comment]
Was soll das bedeuten: "2mal den gleichen Graphen für eine Hierarchy" ?

**Comment by JirkaDellOro** [comment]
Achso, einen Graphen in sich selbst zu platzieren. Das gehört verboten!

**Comment by JirkaDellOro** [comment]
Bitte nun ausgiebig testen mit verschiedenen verschachtelten Strukturen. Beabsichtigt ist, dass ein Graph nicht in einen anderen Graphen, egal in welcher Tiefe, gedropt werden kann, wenn er den Zielgraphen in seiner eigenen Hierarchy enthält, egal in welcher Tiefe.

**Comment by Duvid19** [comment]
Man kann jetzt nicht mehr einen Graphen in sich selber platzieren. Allerdings besteht noch das Problem ,dass wenn man 2 Graphen erstellt und diese miteinander verhängt, kann man z.B den 2. Graphen nochmal in sich selber platzieren.
![image](https://user-images.githubusercontent.com/91938270/167364735-ba9733dc-86e6-4855-9fed-2d00b53053f0.png)
![image](https://user-images.githubusercontent.com/91938270/167364761-2bd23e06-1a8c-4e1b-a186-85232c940075.png)

**Comment by JirkaDellOro** [comment]
Bitte probieren, ob Du es immer noch kaputt kriegst.

**Comment by JirkaDellOro** [comment]
Ergebnis? Hier posten!

**Comment by Duvid19** [comment]
Man kann keine Graphen in sich selber mehr erzeugen ^^
