### ISSUE TITLE
Draggable Valuechanger

### ISSUE THREAD

**Issue by Xanderthier** [JirkaDellOro/FUDGE#313]
Draggable Valuechanger - Gimmick?

Da die Werte Einstellung im Editor selbst etwas suboptimal funktioniert dachte ich mir im Rahmen des Ausprobierens und Rumexperimentierens ist es manchmal wichtig Werte schnell zu verändern.

Blender Beispiel hierfür:
![Blender Value change](https://user-images.githubusercontent.com/9372410/167011948-15f9c481-4115-4e2d-b346-d467c68b0eff.gif)
Linker Mausklick + ziehen nach links oder rechts (Habe auch schon oben und unten gesehen, je nach Ausrichtung. Wichtig zu bedenken ist, dass die Stärke anpassbar ist, indem man die jeweils nicht benutzte Achse zum ziehen mitverwendet.)

-> Zusatzidee: 
Könnte man, da dies schnell geht, vielleicht in 2 unterschiedliche draggable values unterscheiden, Dezimal-Bereich und die natürlichen Zahlen als separaten draggable Bereich pro Value.
 
 
 Ist einfach nur ein Denkanstoß das arbeiten mit Fudge etwas angenehmer zu machen. 
 Ist natürlich nur mein Pitch was dies angeht und mit keiner Ahnung von der Schwierigkeit des Umsetzens in Fudge verfasst.

**Comment by JirkaDellOro** [comment]
Die Transformationen lassen sich bereits per drag manipulieren, hast Du das schon bemerkt? Wenn Du die Maus im RenderView parkst, erklärt dir der Editor wie.

**Comment by Xanderthier** [comment]
Oh! Gerade ausprobiert. Sorry das wusste ich nicht. 
Lässt UX technisch zwar etwas zu wünschen übrig, aber macht was es soll.

Kannst das Ticket also schließen wenn die Sache für dich erledigt ist.

**Comment by JirkaDellOro** [comment]
Ja, visuelles Feedback und Feedforward im Renderview ist nochmal ein eigene Thema, das habe ich bislang noch gemieden. Vielleicht für eine Bachelorthesis, schreibe ich gleich mal auf.
