### ISSUE TITLE
Die Fehlermeldung "Cannot read property 'controller'" stacked sich -> CPU überlastung

### ISSUE THREAD

**Issue by Duvid19** [JirkaDellOro/FUDGE#315]
Wenn man ein neues Projekt startet und irgendwas erstellt was nicht in den Hierachy Fenster gehört wie zum Beispiel ein Mesh oder einen Graphen und dieses über das Hierachy Fenster zieht, stacked sich die Fehlermeldung  Cannot read property 'controller' of undefined. Wenn man ein Objekt lang genug über den Hierachy Fenster hovert kann die Fehlermeldung weit über 15.000 gehen und  es kann sein das die CPU bisschen darunter bisschen leidet.
![image](https://user-images.githubusercontent.com/91938270/167633055-b06a35f6-04a7-4ae8-886e-d79af3b8cf0a.png)

**Comment by JirkaDellOro** [comment]
Gut aufgepasst! Bitte jetzt testen.

**Comment by Duvid19** [comment]
Die Fehlermeldung kommt nicht mehr
