### ISSUE TITLE
Preserve Scaling Issue

### ISSUE THREAD

**Issue by Xanderthier** [JirkaDellOro/FUDGE#316]
![image](https://user-images.githubusercontent.com/9372410/167646116-610edc44-9063-45c3-8efb-a6e8cb416763.png)
Preserve Scaling Issue

**Comment by JirkaDellOro** [comment]
Description needs update

**Comment by Xanderthier** [comment]
The description of the Item "When _preserveScaling is false...", not issue.

Just as clarification.
