### ISSUE TITLE
Fix for query selectors in ui generator and controller "not a valid selector"

### ISSUE THREAD

**Issue by plojo** [JirkaDellOro/FUDGE#317]
I have found a way to fix the query selector search in Controller.ts `findChildElementByKey` method [link](https://github.com/JirkaDellOro/FUDGE/blob/f33c986572ff8fb24c5f21da5054983164b8200d/UserInterface/Source/Controller/Controller.ts#L119). The query selector simply needs to be changed from `` `[key = ${key}]` `` to `` `[key = "${key}"]` ``. This change seems to solve all "not a valid selector" issues. Following this change there is no need for CustomElements to append "ƒ" at the start of their key attribute in any case.

**Comment by JirkaDellOro** [comment]
😃 👍

**Comment by JirkaDellOro** [comment]
Will you clean it out, since you're at it?

**Comment by plojo** [comment]
should I change it in development branch or mine?

**Comment by plojo** [comment]
so far I couldn't find a spot in the editor where this [line](https://github.com/JirkaDellOro/FUDGE/blob/653d69b1177676b9e5ad46cc9b4f79400b00cba1/UserInterface/Source/CustomElement/DetailsArray.ts#L46) gets called so my change to this is still untested.

**Comment by JirkaDellOro** [comment]
That happens, when you manipulate an array in the editor.

Create a MeshPolygon -> In the PropertiesView, rearrange the vertices of the shape by dragging and dropping on another position.

**Comment by JirkaDellOro** [comment]
How about this, have you been able to test?

**Comment by plojo** [comment]
Ok, there were still some "" missing. Everything seems to be working now.
