### ISSUE TITLE
Editor: ViewPreview freezes editor

### ISSUE THREAD

**Issue by plojo** [JirkaDellOro/FUDGE#318]
Use the attached Project:
[FUDGE_EDITOR_BUG.zip](https://github.com/JirkaDellOro/FUDGE/files/8672889/FUDGE_EDITOR_BUG.zip)

When selecting the graph in the internal view the editor freezes.

![image](https://user-images.githubusercontent.com/38690628/167931843-6cc4af4f-31a2-4ba7-ae62-f8b2f43d1c99.png)

This seems to happen because `ViewPreview` attaches an event listener which listens for `FudgeCore.EVENT.MUTATE` ([link](https://github.com/JirkaDellOro/FUDGE/blob/f33c986572ff8fb24c5f21da5054983164b8200d/Editor/Source/Fudge/View/Project/ViewPreview.ts#L135)) to initiate a redraw (redrawing the viewport). Both animation and particle system will dispatch the mutate event while redrawing causing a new redraw leading to an endless loop.

**Comment by JirkaDellOro** [comment]
Aua. I think it's not so much an issue with the ViewPreview, but with the recently implemented functionality of the synchronization of a graph and its instances. If not explicitely stopped. a mutation of a graph mutates all its instances, and a mutation of an instance mutates the graph and subsequently the instances again. I didn't think of the animation which of course works through mutation. Let's talk about that today.
