### ISSUE TITLE
Debugger öffnet sich automatisch wenn man den ShaderFlatSkin auswählt

### ISSUE THREAD

**Issue by Duvid19** [JirkaDellOro/FUDGE#319]
Wenn man unter CreateMaterial den ShaderFlatSkin auswählt öffnet sich automatisch der debugger und es kommt zu Fehlermeldungen in der Konsole. 
![image](https://user-images.githubusercontent.com/91938270/168013566-6aa1e790-a6b4-492b-a2b2-85428fa4f05f.png)
wenn man jetzt den debugger schließt und andere shader hinzufügen möchte, öffnet sich dann wieder der debugger von alleine.

**Comment by JirkaDellOro** [comment]
```typescript

      } catch (_error) {
        Debug.error(_error);
        debugger;
      }
```

Das Öffnen lässt sich durch Obenstehendes erklären. Ich nehme an, Du hast kein Skelett mit dabei.

**Comment by JirkaDellOro** [comment]
Grund für die Exception ist aber ein Fehler in der Parametrierung des Skin-Shaders. Bitte jetzt erneut testen!
