### ISSUE TITLE
Animation on Graph instance

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#321]
Gibt's da etwas neues, hat es geklappt einfach den Event zu unterdrücken?

**Comment by plojo** [comment]
Sorry hatte die alte Issue schon geschlossen. Ja das Eventunterdrücken hat funktioniert. Die Änderungen befinden sich im Branch RenderParticle [link zum Commit](https://github.com/JirkaDellOro/FUDGE/commit/0b670c73eb1c71462b53e2720deda6d6febc4e24)

**Comment by JirkaDellOro** [comment]
Ah, das hatte ich übersehen, weil kein Kommentar dabei war. Sieht aus, als musstest Du zuvor noch aus dem aktuellen development mergen?

**Comment by JirkaDellOro** [comment]
sollen/können wir den schließen?

**Comment by plojo** [comment]
ja können wir
