### ISSUE TITLE
Fixing/Adding orthographic projection

### ISSUE THREAD

**Issue by nathanielkeeler** [JirkaDellOro/FUDGE#324]
Please add/fix orthographic projection option

**Comment by JirkaDellOro** [comment]
Hast Du etwas gefixed, Nathan? Oder hatte ich schon und vergessen? Du jast jedenfalls den Issue geschlossen...

**Comment by nathanielkeeler** [comment]
Hey, Alida war schneller als ich mit dem Issue, wollte nicht dass er zwei
mal drin ist.

JirkaDellOro ***@***.***> schrieb am Di., 24. Mai 2022, 20:38:

**Comment by JirkaDellOro** [comment]
achso
