### ISSUE TITLE
Sprite showFrame() macht Animation "kaputt"

### ISSUE THREAD

**Issue by SorayaFe** [JirkaDellOro/FUDGE#325]
Hat man ein Sprite mit der Framerate 1 läuft dessen Animation ganz normal durch, also jede Sekunde ein Frame. Sobald man aber showFrame() aufruft also z.B.:  sprite.showFrame(30), läuft die Sprite-Animation nicht mehr richtig ab. Frames machen den Anschein. als laufen sie schneller als mit dem eingestellten einen Frame oder scheinen als werden sie übersprungen. 
Ich denke es liegt daran, dass wenn showFrame() aufgerufen wird, der vorhandene Timer nicht entfernt wird. Weil wenn man bei FudgeAid.js über der Zeile 405 folgendes einfügt:  if (this.timer) "ƒ.Time.game.deleteTimer(this.timer);" dann verhält sich alles wie erwartet.

**Comment by JirkaDellOro** [comment]
Ja, das könnte so sein. Ich habe mal in den Code geschaut, bei setAnimation findet sich etwas ähnliches:

```typescript
public setAnimation(_animation: SpriteSheetAnimation): void {
      this.animation = _animation;
      if (this.timer)
        ƒ.Time.game.deleteTimer(this.timer);
      this.showFrame(0);
    }
```

Es stellt sich zunächst die Frage, was Du vorhast. Warum rufst Du showFrame explizit auf?

**Comment by SorayaFe** [comment]
Ich rufe showFrame explizit auf, da ich ein Sprite für einen timer benutzen möchte. Ich habe also ein Sprite mit 30 frames (von 00:00 bis 00:30) und jede Sekunde wird ein frame angezeigt, sodass der Nutzer eben einen countdown hat. Nun möchte ich aber je nach Umständen den timer unterschiedlich lang laufen lassen, also zum Beispiel nur 10 Sekunden (also von 00:10 bis 00:00) hierzu müsste ich dann eben den frame setzten mit showFrame(), sodass ich von diesem frame aus dann die Animation weiter laufen lassen kann.
Ich hoffe das war halbwegs verständlich ausgedrückt :)

**Comment by JirkaDellOro** [comment]
Ja, so angewendet ergibt es Sinn.

Hast Du einen Fork von FUDGE gemacht? Dann könntest Du den Fix machen und mir eine Pull-Request schicken. Ansonsten bastel ich es in Aid ein.

**Comment by JirkaDellOro** [comment]
Damit bist Du zu einem FUDGE-Contributori geworden
