### ISSUE TITLE
Reload-Fenster, nach dem Speichervorgang

### ISSUE THREAD

**Issue by RolandHeer** [JirkaDellOro/FUDGE#327]
Teil1 beinahe jedes mal nachdem Speichervorgang im Editor werde ich durch Fudge "gezwungen" das Projekt neu zu laden. Nach dem reload wird die gesamte Hirarchie zusammengeklappt, was vorallem bei größeren Strukturen doch sehr stören kann.

Teil2 Ich mein mich zu erinnern dass das Fenster durch cancle nicht weggeklickt werden, konnte, kann dieses Verhalten jedoch momentan nicht überprüfen, da Problem aus Teil1 ausnahmsweise gerade nicht auftreten will, obgleich es das noch bis vor einer halben Stunde tat

**Comment by JirkaDellOro** [comment]
Dann bitte wieder hier melden, wenn Du das Problem provozieren kannst.

**Comment by RolandHeer** [comment]
Das Problem mit dem Reload Fenster nach dem Speichern besteht weiterhin, lediglich teil2 mit dem "nicht wegclickbaren" Fenster scheint behoben zu sein

**Comment by JirkaDellOro** [comment]
Heißt, Teil 1 ist nun wieder reproduzierbar?

**Comment by JirkaDellOro** [comment]
Da ich nicht selbst reproduzieren kann, bin ich auf Hilfe angewiesen. Ich habe etwas implementiert, was vielleicht hilft. Bitte testen und ggf. den Issue wieder öffnen.

**Comment by RolandHeer** [comment]
Die änderung scheint das Problem (zumindest bei mir) gefixt zu haben, die Firma dankt!

**Comment by JirkaDellOro** [comment]
erstaunlich... gerne wieder öffnen, falls es doch wieder kommt. Ich traue dem Frieden nicht.
