### ISSUE TITLE
Feature Request - Blick durch eine Kamera

### ISSUE THREAD

**Issue by RolandHeer** [JirkaDellOro/FUDGE#328]
Ich fände es super, wenn es die Möglichkeit gäb durch eine ausgewählte Kamera-Komponente zu blicken, das würde arbeiten im Editor um einiges vereinfachen und vorallem im Hinblick auf Prototyping, bei dem man auch gern mal schnelle Änderungen machen will mMn sehr viel Sinn ergeben.

**Comment by JirkaDellOro** [comment]
Ich habe dir mal einen kleinen Hack gebastelt. Da kannst nun aus dem ComponentView eine ComponentCamera in den RenderView ziehen. Dann schaust Du durch diese Kamera und kannst sei einstellen.

Der Weg zurück ist (noch) nicht drin, mach dir dafür am besten also ein eigenes Graph-Panel auf.

Auf Basis deiner Erfahrung damit würde ich dann an dem Feature weiterbasteln.

**Comment by JirkaDellOro** [comment]
Mal ausprobiert? Passt?

**Comment by JirkaDellOro** [comment]
Dann mach' ich mal zu hier. Man kann nun auch per rechte Maustaste und dem Umschalter zwischen Orthografie und Perspektive auf die Editorkamera zurückwechseln.
