### ISSUE TITLE
Seltsames Verhalten von UVs bei OBJs

### ISSUE THREAD

**Issue by RolandHeer** [JirkaDellOro/FUDGE#329]
Soooo und noch ein letztes Issue für heute, Mir ist aufgefallen dass die UVs bei importierten Objekten ein seltsames Verahlten an den Tag legen. zum Testen habe ich hier mal was vorbereitet. Darin zu finden ist ein Fudge Projekt, mit bereits zugeordneten Materialien und Co. und als Referenz noch die .blend datei...
https://github.com/RolandHeer/Prima/tree/main/OBJ-UV-Example

und hier noch ein Bild als referenz wie s in blender ausschaut, sofern das funktioniert...
![grafik](https://user-images.githubusercontent.com/48826831/173166765-0d417bee-0766-4089-9677-7a60db800583.png)

**Comment by JirkaDellOro** [comment]
Mir fällt schonmal auf, dass die Texturen gespiegelt sind. Daher: welches Koordinatensystem verwendest Du in Blender? Links- oder rechtshändig?

**Comment by JirkaDellOro** [comment]
Oder kann man bei Blender einstellén, wo bei einer Textur die 0 sitzt, also oben links oder unten links?

**Comment by JirkaDellOro** [comment]
Negiere ich nämlich beim Import die vertikale Texturkoordinate erhalte ich
![image](https://user-images.githubusercontent.com/6279994/175818930-3b3a7838-a15d-41e5-8cf2-86fe48993535.png)

Jetzt muss ich aber wissen, ob das generell so zu machen ist, oder ob es an Export-Parametern liegt...!

**Comment by RolandHeer** [comment]
Blender verwendet (laut Internet) ein rechtshändiges Koordinatensystem. Beim OBJ Export kann man einstellen ob die  vertikale die Y Achse sein soll (standardeinstellung für den export) (blender hat intern standardmäßig Z für vertikal) 
Für UVs kann man beim Export außer dass generell UVs exportiert werden sollen nix einstellen. 
Ich hab mit Blender auch schon öfters für Unity exportiert, und da hat das mit den Texturen eigentlich immer hingehauen, würde also behaupten dass das Problem nicht am Blender-OBJ-Exporter liegt

**Comment by JirkaDellOro** [comment]
Dann lasse ich die Import-Einstellung mal so.
