### ISSUE TITLE
Editor Error bei Custom Component Script rename

### ISSUE THREAD

**Issue by Shykaro** [JirkaDellOro/FUDGE#336]
Die internal.json muss aktualisiert werden wenn man den Klassennamen eines CustomcomponentScripts im Code umschreibt. 

Momentan läuft der Editor nicht mehr wenn man ein Customcomponentscript umbenennt und ist nur fixable indem man manuell die internal.json umschreibt.

Das sollte vlt für Neulinge angepasst werden da der serialization error keinen guten Verweis darstellt.

**Comment by JirkaDellOro** [comment]
Das wird knifflig, die Dateien werden von unterschiedlichen Editoren bearbeitet, die nichts voneinander wissen. Vielleicht fällt mir mal etwas ein.

**Comment by Shykaro** [comment]
Alternativ könnte natürlich auch ein besserer Verweis, aka eine spezifischere Fehlermeldung eingebaut werden?

-> Ist nur ein Vorschlag, da aber mein neues Issue den selben Fehler beinhaltet, wird dies wohl anscheinend sehr schwer differenzierbar sein.

**Comment by JirkaDellOro** [comment]
Ich hatte gerade erkannt, dass bei der Ausgabe des Fehlers wieder ein Fehler auftreten konnte, der die eigentiche Ursache verschleierte. Jetzt kriegt man so etwas:

Uncaught (in promise) Error: Deserialization of ƒ.Graph, undefined failed: Error: Deserialization of ƒ.Node, undefined failed: Error: Deserialization of Mario.ScriptRotator,  failed: TypeError: constructor is not a constructor

Man sieht nun den Verweis auf den ursprünglichen Namen der Script-Komponente, das sollte helfen.
