### ISSUE TITLE
NodeSprite.getCurrentFrame zählt weiter obwohl NodeSprite deaktiviert ist.

### ISSUE THREAD

**Issue by Matzengo** [JirkaDellOro/FUDGE#337]
"getCurrentFrame" liefert weiterhin Werte obwohl NodeSprite auf "aktivate(false)" gesetzt wurde.

**Comment by JirkaDellOro** [comment]
es müsste activate(false) heißen, oder? Wird denn der Knoten weiter gerendert?

**Comment by Matzengo** [comment]
sorry ich meinte activate(false). Nein, der Knoten wird nur aktiviert und deaktiviert.

**Comment by JirkaDellOro** [comment]
Ein deaktivierter Knoten sollte nicht mehr gerendert werden. Ist das so?

**Comment by JirkaDellOro** [comment]
Da die Sprites mittelfristig von Animation gesteuert werden sollen, wird das zurück gestellt
