### ISSUE TITLE
Editor sprint in Ursprung zurück

### ISSUE THREAD

**Issue by SorayaFe** [JirkaDellOro/FUDGE#339]
Positioniert man seine Ansicht auf einen bestimmten Punkt z.B. so
![image](https://user-images.githubusercontent.com/64090992/180660264-a9d269c1-5222-4aee-9ca8-ac78e5cce4a3.png)

und klickt dann in der Hierarchy auf einen Node, dann landet man in der Ansicht wieder im Ursprung und sieht nicht mehr das, auf was man sich eigentlich den viewport eingestellt hatte:

![image](https://user-images.githubusercontent.com/64090992/180660306-9e0d0aef-96bb-40e9-af1e-3a0aef535896.png)

**Comment by JirkaDellOro** [comment]
Achso... eigentlich ist das so gedacht, dass automatisch die Position des Knotens fokussiert wird. Wenn das den Arbeitsfluss stört, muss das anders gelöst werden. In Unity drückt man dafür "F", finde ich aber irgendwie doof. Vielleicht besser "SPACE" oder nochmaliger Klick nach dem ersten?

**Comment by SorayaFe** [comment]
Ja, so eine Art Doppelklick wäre vielleicht ganz gut.

**Comment by JirkaDellOro** [comment]
Es würde mich freuen, wenn Du testest und Rückmeldung gibst, ob das so nun besser ist. Zweiter Klick oder Space.

**Comment by SorayaFe** [comment]
Habe es ausprobiert. Ist jetzt besser.

**Comment by JirkaDellOro** [comment]
Noch nicht gut? Was kann noch besser werden?

**Comment by SorayaFe** [comment]
Ich finde es ist jetzt gut so. Wenn man die Kamera einstellt springt es nicht mehr zurück, sondern man sieht weiterhin genau den Punkt, auf den man fokussiert hat, wodurch der Arbeitsfluss nicht gestört wird. Sollte man doch zum Element springen wollen, ist der zweite Klick / die Leertaste eine praktische Option.
