### ISSUE TITLE
shaderlit und shaderlittexture bug beim Mac

### ISSUE THREAD

**Issue by jankefyn** [JirkaDellOro/FUDGE#345]
Beim erzeugen von shaderLit oder shaderlitTexture auf einem Mac erhalte ich die Fehlermeldung "paused in Debug Mode"

Außerdem funktionieren die shortcuts für copy und paste vom Mac nicht. Kopieren und einfügen ist mir nur möglich wenn ich eine externe Tastatur anschließe.

**Comment by JirkaDellOro** [comment]
Bitte mal Shader testen. Der Mac scheint es nicht zu mögen, wenn der Fragmentshader Ausgaben des Vertexshaders ignorieren soll.

**Comment by JirkaDellOro** [comment]
Bitte auch copy/paste testen.

In Zukunft bitte für jedes Problem einen eigenen Issue schreiben

**Comment by JirkaDellOro** [comment]
Erkenntnisse??

**Comment by JirkaDellOro** [comment]
Ich habe nun auch auf Runtime gepusht, bitte testen und ggf. schließen

**Comment by JirkaDellOro** [comment]
Closed? Wolltest Du den nicht reaktivieren?
