### ISSUE TITLE
Animation zerhaut Transition und Bildschärfe

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/FUDGE#359]
Hallo,

ich brauche bitte Hilfe...
Wenn in einer Szene eine Animation ausgeführt wird, dann wird die Transition aller nächsten Szene nicht richtig ausgeführt. 
Außerdem werden die Umrisse aller darauffolgenden Bilder unscharf und verpixelt. :-(

Als Beispiel habe ich in meiner Main-Datei die Szene 03 und 05 hinterlegt. In Szene 03 wird, wenn man die Auswahl "Anfassen" wählt, eine Animation ausgeführt. Wenn dann die nächste Szene kommt sieht man schon was ich meine....
Wählt man aber eine andere Option z.B. "Ignorieren", dann läuft die Transition normal und die Bilder sehen scharf aus.

Hier ist mein Pages-Link: https://frankesa.github.io/vn_repo_sarah/The_Pingu/SarahsNovel.html
Und hier zu meinem Repo: https://frankesa.github.io/vn_repo_sarah/The_Pingu/

**Comment by JirkaDellOro** [comment]
Ich kann leider nicht testen, ein Bild wird wohl nicht gefunden
-url:https://frankesa.github.io/vn_repo_sarah/The_Pingu/Images/Hintergruende/an_der_Haustuer.png

**Comment by JirkaDellOro** [comment]
Der Link zum Repo funktioniert leider nicht, das muss eine github.com-Adresse sein. 

Ich habe ein wenig geschaut, es gibt im Repo ein Bild mit diesem URL:
https://frankesa.github.io/vn_repo_sarah/The_Pingu/Images/Hintergruende/an_der_haustuer.png

Groß-/Kleinschreibung und Umlaute etc. sind wichtig, allerdings vom Server abhängig. Dein Localhost ist sehr viel toleranter. Daher folgende Tipps:
- alle Dateinamen auf Englisch, wie alles, was der Computer lesen soll (also auch Variablennamen etc.)
- keine Leerzeichen und Sonderzeichen verwenden, Unterstrich ist in Ordnung
- eindeutiges Namensgebungsschema entwerfen und strikt anwenden, auch z.B. für Groß-/Kleinschreibung
- ständig über Pages testen, der Server ist relativ intolerant

**Comment by FrankeSa** [comment]
Also...
ich habe nun alle Dateien z.B. Bilder und Ordner auf englisch umgeschrieben.
Nach der Animation besteht das Problem aber immer noch...
Link zum Repo: https://github.com/FrankeSa/vn_repo_sarah
Link zur Anwendung: https://frankesa.github.io/vn_repo_sarah/The_Pingu/SarahsNovel.html

Auf Microsoft Edge und Google Chrome kann meine VN gestartet werden, aber auf FireFox nicht, da bekomme ich einen Fehler.... muss es auch auf FireFox laufen? PS. die Transition nach der Animation funktioniert in beiden Browsern nicht.

**Comment by JirkaDellOro** [comment]
Ich schau mir das an. Bitte stelle im Compiler ein, dass map-Files erzeugt werden, dann kann man besser debuggen.

**Comment by JirkaDellOro** [comment]
PS: Chrome ist unsere primäre Zielplattform, ich weiß nicht, ob Riem andere bedienen möchte.

**Comment by JirkaDellOro** [comment]
Auf den ersten Blick kann ich keine Ursache für dein Problem erkennen.

@Riem: das müsste eigentlich schonmal woanders aufgetaucht sein, ist das ein bekanntes Problem?
@FrankeSa: wie verhält sich das, wenn Du ein anderes Transition-Bild nutzt?

**Comment by FrankeSa** [comment]
Ich hab das auch mit anderen Transitions getestet und bei zwei war die Transition gut und bei den anderen nicht... und die Bildunschärfe ist aber bei allen aufgetreten.

Ich habe eine neue Version in mein Repository gepuscht, wenn ich aber den Pages Link in Chrome teste, zeigt es mir immer noch eine Vorgängerversion an??? Also z.B. mit altem SplashScreen :(

Und: Wie stelle ich im Compiler die Map-Files ein?

**Comment by FrankeSa** [comment]
Ok, ich glaube, das mit dem Link hat sich erledtgt.

**Comment by JirkaDellOro** [comment]
Das map-File wird generiert, es hatte sich wohl nur mein Browser verschluckt gehabt.  Einstellen kann man das in der tsconfig.json

**Comment by FrankeSa** [comment]
Dann mach ich diesen Issue auch in Fudge Story...
