### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/FUDGE#360]
Ich habe noch ein paar Fragen zu dem Startbildschirm:

Wie kann ich die Text Box auf dem Startbildschirm ausblenden?
Wie kann ich die Meter Anzeige auf dem Startbildschirm ausblenden?
Warum wird mir mein Splash png nicht angezeigt?

**Comment by JirkaDellOro** [comment]
Das ist sehr FudgeStory-spezifisch und besser dort im Repo bei den Issues aufgehoben. Da kann dir dann auch Riem antworten, die FUDGE selbst wahrscheinlich nicht überwacht.

**Comment by FrankeSa** [comment]
Ok, das mache ich. Danke, ich habe nicht darauf geachtet.
