### ISSUE TITLE
Rectangle Calculation Bug

### ISSUE THREAD

**Issue by KakuschkeFelix** [JirkaDellOro/FUDGE#365]
# Problem
In `Core/Math/Rectangle.ts:82`, "bottom" is calculated as
```
get bottom(): number {
      if (this.size.y > 0)
        return (this.position.y + this.size.y);
      return this.position.y;
    }
```

Given that FUDGE uses a coordinate system where the Origin is in the bottom left, this causes the bottom to be above the top.

# Example 
`const rect = {x: 0, y: 1, width: 4, height: 1}` => `bottom = 2; top = 1`

# Expected behaviour
 `bottom = 1; top = 2`

**Comment by JirkaDellOro** [comment]
Rectangle is used for 2D space/screen space and the common 2D system is used with y pointing down. However, where the origin is supposed to be is determined by a parameter of the type `ORIGIN2D`
