### ISSUE TITLE
REnder Fehler wenn man Material ändert bei Component Material

### ISSUE THREAD

**Issue by LuciaRot** [JirkaDellOro/FUDGE#367]
![image](https://user-images.githubusercontent.com/56443226/231758651-39973ac1-9027-4839-a9ec-67d5af50f9db.png)

**Comment by JirkaDellOro** [comment]
Bitte pushe den Code, der den Fehler erzeugt auf Github. Ich kann ihn nicht reproduzieren. Mein Code:

```typescript
function changeSonicMaterial(): void {
    let mtrNew: ƒ.Material = <ƒ.Material>ƒ.Project.getResourcesByName("Floor")[0];
    let cmpMaterial: ƒ.ComponentMaterial = sonic.getComponent(ƒ.ComponentMaterial);
    console.log(mtrNew, cmpMaterial);
    cmpMaterial.material = mtrNew;
  }
}
```

**Comment by LuciaRot** [comment]
https://github.com/LuciaRot/Prima/tree/main/FudgeFehlercode
Ich hatte den Code schon überschrieben. Als ich versucht habe ihn wieder herzustellen kam der Error bei mir auch nicht mehr.
