### ISSUE TITLE
Rotation bug

### ISSUE THREAD

**Issue by ArthurErlich** [JirkaDellOro/FUDGE#374]
rotation is not settable. 

```typescript
maxPitch = 15;

this.mtxLocal.rotation.set(this.mtxLocal.rotation.x, this.mtxLocal.rotation.y, maxPitch);

or

 this.mtxLocal.rotation.z = maxPitch;
```
-70 is the setted rotation.
-123 is the actual rotation
![image](https://user-images.githubusercontent.com/92059317/236670024-47bfd718-6db9-4e4a-a879-6e53e9b55467.png)

**Comment by JirkaDellOro** [comment]
Beachte, dass `rotation` eine get-Accessormethode ist, welche die Rotation aus der Matrix herausrechnet und dir als Vektor liefert. Wenn Du diesen Vektor veränderst, hat das keine Auswirkung auf die Matrix. Dazu musst Du die entsprechende set-Accessormethode verwenden, also `rotation = ...`

**Comment by ArthurErlich** [comment]
Rotation funktioniert nicht sobald davor eine Translation gemacht wurde. Getrennt funktioniert es.
` this.mtxLocal.rotation.= new Vector3();` war die Lösung
