### ISSUE TITLE
FudgeConfig 

### ISSUE THREAD

**Issue by RolandHeer** [JirkaDellOro/FUDGE#381]
geht nicht   (╯‵□′)╯︵┻━┻

**Comment by JirkaDellOro** [comment]
Sollte gefixed sein, bitte ausprobieren

**Comment by JirkaDellOro** [comment]
@RolandHeer  Erkenntnisse?

**Comment by RolandHeer** [comment]
Bei mir hat es scheints die normale FUDGE Version zerschossen, daher kann ich das gerade nicht austesten. Aber der Komilitone mit den Würfeln könnte dies sicher tun, der wollte ja auch wissen wie s geht. (hab bloß leider weder dessen Mailadresse noch dessen Namen parat um ihm dies weiterzugeben)

**Comment by JirkaDellOro** [comment]
Wie kam es zum Zerschuss, hast Du etwas frisches gepullt?

**Comment by RolandHeer** [comment]
Ich glaub das größte Problem war, dass beim öffnen von Fudge als zuletzt verwendetes Projekt eine Testszene für meine Fudgeversion drin war und es damit nicht viel anfangen konnte. Ich hab jetzt Fudge neu gepullt, eine neue Szene erstellt, und die Antialias Geschichte dort ausgetestet und es scheint ohne Probleme zu funktionieren.

**Comment by JirkaDellOro** [comment]
Ja, das Autoload ist ein Problem, wenn man das Projekt gelöscht oder kaputtgemacht hat. Da müssen wir auch ran.

Aber Config geht, dann kann der Issue weg
