### ISSUE TITLE
Implement playbackRate in the audio system

### ISSUE THREAD

**Issue by easzyyyyy** [JirkaDellOro/FUDGE#384]

**Comment by JirkaDellOro** [comment]
Please test

**Comment by easzyyyyy** [comment]
I tried to change the playbackRate of my sound with this code : 
```js
let cmpAudio: ƒ.ComponentAudio = new ƒ.ComponentAudio();
cmpAudio.loop = true;
cmpAudio.playbackRate = 2;
this.node.addComponent(cmpAudio);
```
But it doesn't change the speed of the sound and in didn't change the value in the console neither.
Project : https://easzyyyyy.github.io/prima/Projects/Karting/index.html

**Comment by JirkaDellOro** [comment]
I found out, that the sound must be playing (being connected) when changing the playbackRate. In the MDN-Example, the slider is deactivated when the sound is stopped.

Have you tried the latest version of FUDGE? I see only a black screen with your example, so it's hard to test. But when I type 
`Script.karting.audio.playbackRate=2`
in the console, the rate changes

**Comment by easzyyyyy** [comment]
It works perfectly, thank you.
