### ISSUE TITLE
"Start" event 

### ISSUE THREAD

**Issue by plojo** [JirkaDellOro/FUDGE#386]
Is there any event in FUDGE which acts like Unity Engines [`MonoBehaviour.Start()`](https://docs.unity3d.com/ScriptReference/MonoBehaviour.Start.html) (see [Order of execution for event functions](https://docs.unity3d.com/Manual/ExecutionOrder.html#BeforeTheFirstFrameUpdate))? CustomScripts in FUDGE can listen for [`ƒ.EVENT.NODE_DESERIALIZED`](https://jirkadelloro.github.io/FUDGE/Documentation/Reference/Core/enums/FudgeCore.EVENT.html#NODE_DESERIALIZED) but this gets called when the node and its descendants are deserialized but before the ancestors/graph is deserialized. This is unpractical if we want to apply any logic which needs the whole scene to be loaded.
A currently working solution seems to be adding a listener for [`ƒ.EVENT.RESOURCES_LOADED`](https://jirkadelloro.github.io/FUDGE/Documentation/Reference/Core/enums/FudgeCore.EVENT.html#RESOURCES_LOADED) to `ƒ.Project` from a CustomScript e.g.:
`ƒ.Project.addEventListener(ƒ.EVENT.RESOURCES_LOADED, this.start);`. 
But since we add the update function to the loop:
`ƒ.Loop.addEventListener(ƒ.EVENT.LOOP_FRAME, this.update);`
maybe we should implement a new event called `ƒ.EVENT.LOOP_START` which gets dispatched just before the first `ƒ.EVENT.LOOP_FRAME` gets dispatched essentially mimicking Unitys `MonoBehaviour.Start()` behaviour.

**Comment by JirkaDellOro** [comment]
I don't see a problem adding this event. However, I think it should start everytime Loop.start() is called, since the Loop has to be started explicitely anyway. And to do so, the creator needs to know, that the scene has loaded. So the event is not actually a solution to the stated problem, since it is independend of the loading.

Another alternative is to listen for the deserialization of the specific graph

**Comment by plojo** [comment]
Maybe we could broadcast the graph deserialization event because our (custom) component instances don't really know which graph they belong to. Currently they can search for this graph but this is rather tedious as it requires multiple nested event listener attachments for example like this:
```typescript
const handleComponentAdd: EventListenerUnified = () => {
  const handleChildAppend: EventListenerUnified = () => {
    // find next graph in hierarchy
    let graph: Node = this.node;
    while (graph.getParent() && !(graph.getParent() instanceof Graph))
      graph = graph.getParent();

    const handleGraphDeserialized: EventListenerUnified = () => {
      // do the "start" logic
      // ...
      
      // cleanup
      graph.removeEventListener(graph instanceof GraphInstance ? EVENT.GRAPH_INSTANTIATED : EVENT.GRAPH_DESERIALIZED, handleGraphDeserialized);
      this.node.removeEventListener(EVENT.CHILD_APPEND, handleChildAppend);
      this.removeEventListener(EVENT.COMPONENT_ADD, handleComponentAdd);
    };
    graph.addEventListener(graph instanceof GraphInstance ? EVENT.GRAPH_INSTANTIATED : EVENT.GRAPH_DESERIALIZED, handleGraphDeserialized);
  };
  this.node.addEventListener(EVENT.CHILD_APPEND, handleChildAppend);
};
this.addEventListener(EVENT.COMPONENT_ADD, handleComponentAdd);
```
However, this approach encounters issues when the component belongs to a graph instance. Inside the handleChildAppend listener, we can only navigate up to the level of the graph instance, which, in itself, has no parent at this point. To address this, we'd have to recursively attach an extra child append listener to each discovered graph instance and then once more search upwards until we locate the actual graph...

Or perhaps I'm overlooking something here; is there a simpler way to locate the container graph?

**Comment by Plagiatus** [comment]
I believe this was solved through the broadcast of the `GraphDeserialized` / `GraphInstantiated` events in 537e338c966eeae5b0f2573540922f6d616740c4?
