### ISSUE TITLE
deepsearch for childs & components

### ISSUE THREAD

**Issue by MauriceHuchler** [JirkaDellOro/FUDGE#390]
`ƒ.Node.getChildrenByName()` & `ƒ.Node.getComponentsByName()` return the first layer of children / components. When building more complex graphs with nested nodes having multiple children its difficult to get the desired child or component. 

Currently if you want to find deeper nodes you can just call `ƒ.Node.getChildrenByName()` again on the children. But imagine having a Node with very deep hierarchy. It would be messy to find the right depth for the desired node.

**Comment by JirkaDellOro** [comment]
use the iterator, like
`for (let node of branch.getIterator(...))`

see https://jirkadelloro.github.io/FUDGE/Documentation/Reference/Core/classes/FudgeCore.Node.html#getIterator

**Comment by JirkaDellOro** [comment]
Wenn der Issue durch ist, bitte schließen
