### ISSUE TITLE
Dragging a CameraComponent in the editor into the Render window locks the Render window to that camera permanently

### ISSUE THREAD

**Issue by Plagiatus** [JirkaDellOro/FUDGE#399]
When using the Render Panel to preview a ComponentCamera's camera view, you cannot get out of this static view anymore. You can switch to other, static ComponentCamera's, but there is no way to go back to the default renderer that lets you move around in the scene.  
Dragging Graphs into the renderer updates the Hierarchy properly, but doesn't exit the camera view.

**Comment by JirkaDellOro** [comment]
At this time, you can switch to the orthografic view and then disable it. I don't have an idea yet for a nice and intuitive way to switch back, without adding very specific icons or menu options...

**Comment by Plagiatus** [comment]
The way I tried to "solve" this is to drag a graph onto the Render view - that's how I originally got there, that's how I expected to get there again.

**Comment by JirkaDellOro** [comment]
That makes sense and will be implemented

**Comment by Plagiatus** [comment]
An additional "release view" button while viewing through a camera component might be useful as well, though I understand the hesitancy to add highly specific interfaces.

**Comment by JirkaDellOro** [comment]
Please test. 

Dragging the graph into ViewRender should switch the camera. Also, disabling the ComponentCamera switches...

**Comment by Plagiatus** [comment]
The reported issue seems to be fixed or at least circumvented - both described methods work for me to get rid of the ComponentCamera view from the ViewRender.

&nbsp;

However, now my project freezes (in a way where you need to click close twice to even end FUDGE). Steps to reproduce:

1. create a graph
2. create a node under said graph, call it "camera"
3. add a ComponentCamera to the node
4. drag the "camera" node into Internal, creating a graph
5. update the hierachy view to re-sync the graph instances (either by minimizing/maximizing the root graph or dragging that graph into the ViewRender again).
6. drag ComponentCamera of "camera" node into the ViewRender
7. attempt to modify any attribute of the camera nodes components
8. freeze

No indications of issues in neither the in-FUDGE console nor the FUDGE running console.

This new issue might be related to #401.

**Comment by JirkaDellOro** [comment]
Have you tested the fix for #401 ?

**Comment by Plagiatus** [comment]
No, I started with this one and didn't check 401 yet, but I'm working in the updated version that should include the fix. I'll be checking that one shortly

**Comment by JirkaDellOro** [comment]
reproducable...

**Comment by JirkaDellOro** [comment]
Test again please. A new parameter list for the mutation method was implemented only for some components for testing, now for hopefully all.

**Comment by Plagiatus** [comment]
I cannot reproduce the new issue anymore 👍

**Comment by Plagiatus** [comment]
Here is an observation that I'm not sure happened before this fix, so whether it's something completely unrelated that I just never noticed before: 

The name that is displayed in the Graph panel is, after dragging a graph into the view, `Graph | <name of graph>`. But as soon as you select any node in the Hierarchy (does not happen when only clicking on the arrow), it changes to be just `Graph`.
