### ISSUE TITLE
FUDGE freezes in infinite loop when trying to modify graph instance

### ISSUE THREAD

**Issue by Plagiatus** [JirkaDellOro/FUDGE#401]
Freeze in this case means: electron is clearly still working and interactable (both the top menu and console, though the console doesn't react to sending commands), but nothing else will react to anything.

Steps to reproduce:

1. create two graphs
2. to second graph, add a transform component
3. add second graph as node to first graph
4. modify transform component, e.g. changing translation x value
5. FUDGE freezes

Alternative path to reproduce:
1. create two graphs
2. to second graph, add a transform component
3. to first graph, add a node, then the second graph as a child of the node. No problem so far
4. add a second instance of the graph as a child of the node. The same issue occurs.

Once i got a quickly repeating error message in the console reading `Sync aborted, target already synced`, but so far in only 1/8 tries. In the other 7/8 the console, while still interactable, doesn't show anything of note.

**Comment by JirkaDellOro** [comment]
Please try again now

**Comment by Plagiatus** [comment]
I can't reproduce the issue in either of the mentioned ways anymore. Let's hope it doesn't show up again in some other way.

**Comment by JulienTrue** [comment]
I am having a similar issue with FUDGE freezing when interacting with the rigidbody component. Here are the steps to reproduce my error in a fresh project:
1. Create two graphs
2. To second graph, add a transform and a rigidbody component
3. Add second graph as node to first graph
4. Modify rigidbody component, e.g. changing typeBody, etc.
5. FUDGE freezes

**Comment by JirkaDellOro** [comment]
Note: line 61 in Project.ts keeps firing, when Rigidbody mutates.
![image](https://github.com/JirkaDellOro/FUDGE/assets/6279994/b3e2a061-6476-44c1-8d76-a099572aa7fe)

**Comment by JirkaDellOro** [comment]
please test again

**Comment by JulienTrue** [comment]
The issue is no longer reproduceable!
