### ISSUE TITLE
Animation Editor: Editing a label / event without a change causes the Dopesheet to not be interactable anymore

### ISSUE THREAD

**Issue by Plagiatus** [JirkaDellOro/FUDGE#406]
Steps to reproduce:

1. open a project with animations, e.g. the Project located here: https://github.com/JirkaDellOro/FUDGE/tree/development/Test/Animation/Editor
2. Drag the animated node into the editor (in the example it's the "Sun" object)
3. click on either the label or event. You'll see their names.
4. Click on the nametag of the label/event. DO NOT EDIT. Just click to get to the text editor. Click somewhere else.
5. You can't interact with the dopesheet at all anymore, you cannot close the nametag unless you edit it. Even when loading a new node, the dopesheet stays on the old one.

The only way out of this is to modify the name of the label/event you clicked on or to completely close the Animation Panel and reopen it.

**Comment by Plagiatus** [comment]
The original problem has been solved, but instead i have a new one:

When I click on the name of the label/event, modify it and then scroll my mousewheel (aka zoom) without clicking out of the name, the name is reset to what it was and the name edit stays active.  
In this state (opened nametag editor) the scroll bar at the bottom also stops working. You can move the bar, but it doesn't actually move the view.

I can fix this issue by clicking anywhere outside the name (but inside the dopesheet), so it's not a huge deal.

**Comment by plojo** [comment]
This behavior mostly boils down to using the html onchange event to actually modify the underlying animation data
```TypeScript
this.eventInput.onchange = () => {
  if (this.selectedEvent.type == "event") {
    let time: number = this.animation.events[this.selectedEvent.data];
    this.animation.removeEvent(this.selectedEvent.data);
    this.animation.setEvent(this.eventInput.value, time);
  } else {
    let time: number = this.animation.labels[this.selectedEvent.data];
    delete this.animation.labels[this.selectedEvent.data];
    this.animation.labels[this.eventInput.value] = time;
  }
  this.selectedEvent.data = this.eventInput.value;
  this.draw();
};
````
We could use oninput event instead but then every change made inside the input field would immediatley be reflected in the animation data. What behavior regarding when the underlying data is actually modified would you expect?
