### ISSUE TITLE
Picking

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#65]

**Comment by Wowaiki** [comment]
http://htmlpreview.github.io/?https://github.com/Wowaiki/FUDGE/blob/master/Test/Raycast%20Picker/webgl_raycast/webgl_raycast_without_orbitcontrol.html

Picking funktioniert am Beispiel.
Ich weiß aber nicht wie bzw. wo ich es integrieren soll.

https://github.com/mrdoob/three.js/blob/master/editor/js/Viewport.js
Beim three,js Editor haben sie es in viewport integriert.
Deswegen habe ich mir gedacht es in 'FUDGE/Core/Source/Engine/Viewport.ts' zu integrieren.
Oder doch nicht?

**Comment by JirkaDellOro** [comment]
Wenn das Picking auf Raycasting basiert, sollte das Raycasting in einen eigenen Ordner, z.B. Physics, und das Picking in den Viewport.

Derzeit sehe ich aber nur, dass Du bereits existierende Beispiele von THREE.js präsentierst und von einer Integration in FUDGE weit entfernt scheinst. Du kannst zunächst alles in deinen Experimenten coden ohne es in den FUDGE-Core zu integrieren. Wenn es läuft, können wir gemeinsam schauen, welche Teile wir wo hinpacken. Bei deiner aktuellen Progressrate sehe ich das aber nicht mehr in diesem Jahr auf uns zukommen.
