### ISSUE TITLE
Element implicitly has an 'any' type beim Lesen eines Mutable Attributes als Mutable

### ISSUE THREAD

**Issue by AkikoOsaka** [JirkaDellOro/FUDGE#73]
@JirkaDellOro 
Beim implementieren vom rekursiven Aufruf der "CreateFromMutable" Funktion in FudgeUI mit den Änderungen aus dem Experiment die wir vorher Besprochen und getestet haben bin Ich in folgendes Problem gerannt. 

> Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Mutable'.
> No index signature with a parameter of type 'string' was found on type 'Mutable'.

Ich weiss grad nicht was Ich damit anfangen soll weils im Experiment ja ohne Probleme gelaufen ist. Es ist warscheinlich wieder nur ein blöder kleiner Fehler den Ich mach aber Ich find nicht wie Ich da drum komm

**Comment by JirkaDellOro** [comment]
Fertig hier?
