### ISSUE TITLE
Integrating NetworkCode into Fudge structure

### ISSUE THREAD

**Issue by Falco-Boehnke** [JirkaDellOro/FUDGE#78]
- -[x] Putting stuff in Fudge folder
- -[x] Resolving merge conflicts
- -[x] resolcing node module conflicts
- -[x] compliling and resolving errors

**Comment by JirkaDellOro** [comment]
öh... ist hier noch etwas zu tun oder kann das weg?

**Comment by JirkaDellOro** [comment]
Soll Marius mal nach schauen
