### ISSUE TITLE
Automatic labelling function for FudgeUI

### ISSUE THREAD

**Issue by AkikoOsaka** [JirkaDellOro/FUDGE#79]
Es sollte eine automatisierte Funktion geben, die durch ein HTMLElement und dessen Kinder schaut und anhand einer Liste die Textinhalte von Elementen verändert.
So können dann automatisch generierte UI Elemente schnell und einfach verschönert werden, und zusätzlich können dann UI Elemente auch leicht übersetzt werden.
Es sollte dadurch kein Problem mit der automatischen generierung von Elementen auftretten, da nur Elemente die sowohl in der Liste also auch im gefragten UI Element vorkommen so übersetzt werden. Elemente die in der Liste nicht auftauchen werden einfach ignoriert und behalten ihren default-Namen.

**Comment by JirkaDellOro** [comment]
Ich denke, dass muss man eher bei der Erzeugung der Elemente machen und nicht im Nachhinein.
