### ISSUE TITLE
Fudge auf Barrelstruktur umwandeln - ca 12 Errors

### ISSUE THREAD

**Issue by Falco-Boehnke** [JirkaDellOro/FUDGE#83]
https://github.com/Falco-Boehnke/FUDGE.git

Es gibt ein paar wenige Error die ich nicht lösen konnte. Wenn man die fixen kann, sollte man es neu kompilieren und testen können. Ansonsten muss das im Laufe der nächsten Woche von mir gemacht werden.

**Comment by JirkaDellOro** [comment]
Hmm... das war vor über einem Jahr. 

Mittlerweile habe ich auch wieder etwas mit Modulen vs. Namespaces herumgetüftelt, aber auch keine Lösung gefunden, die beiden Paradigmen zusammen zu bringen. Ich bin noch nicht bereit vom Namespace abzurücken, da gerade die einfache Codeaufteilung und das Kompilieren in ein File "out of the box" zu gut ist. Ansonsten müsste man in einem Post-Prozess mit z.B. Webpack das Zeug bündeln und aufteilen lassen. Das gefällt mir gar nicht. Gerade bauen wir ein Spiel mit der Netzwerk-Anbindung, mal schauen was da so rauskommt.

**Comment by JirkaDellOro** [comment]
Net wurde komplett umgebaut und ein Verfahren gefunden, mit dem die Probleme gelöst sind.
