### ISSUE TITLE
SingleWindow wird funktionieren

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/FUDGE#91]
Ich habe nun ein Template für euch programmiert. Das Beispiel ist analog zu dem, mit dem die Dysfunktionalität der MultiWindow-Lösung demonstriert wurde. Die Struktur entspricht dem, was ich mit Lukas auf der gamescom geplant hatte. Lediglich die Bezeichnung "Container" für eine Entität, die mehrere Views aufnimmt, wurde zu "Panel" geändert, da Container schon stark von GoldenLayout besetzt ist. Ihr könnt euch also ganz an der Zeichnung orientieren, sie befindet sich in den Logs und ich habe sie aktualisiert.

**Comment by AkikoOsaka** [comment]
Bedenken bezüglich User Experience sollten doch wohl relevant sein. Für mich sieht das grade so aus als sollten alle Views in genau ein Fenster passen, wo wir schon drüber geredet haben und beschlossen haben, das sowas nur zu Verwirrung sorgen würde.
Ich weiss jetzt nicht ob Ich mich unklar ausgedrückt hab oder du vergessen hast, aber durch die Tab Funktionalität die GoldenLayout mitsich bringt, müssen wir das nicht machen, sondern können statt einem "MultiWindow" Ansatz, ein "SingleWindow, MultiTab" Ansatz probieren.
Ich werde dazu nochmal ein paar Tests laufen lassen, aber im Grunde sind alle Tabs immernoch auf der selben Seite und sind nur visuell getrennt voneinander. Man kann auch Tabs verschachteln (siehe dieses Example: http://golden-layout.com/examples/#b40c19e79915493e9d3ae0220773358f).
Falls das nicht geht, dann haben können wir immernoch *diese* Lösung nehmen

**Comment by AkikoOsaka** [comment]
Also, Ich habe zumindest mal ein kleinen Versuch gestartet mit mit PopOut Windows und er legt beim Pop Out einfach eine weitere Instanz der Fudge App an, ohne die passende Menüleiste. 
Ich hab mir sowas ähnliches schon letzte Woche gedacht, aber Ich schätze das fällt dann raus.
Es bleibt Tabs im Detail zu checken.
Was mir grade auffällt ist das wir jetzt wieder ein Benennungskonflikt haben der Lea in die Thesis grätscht weil jetzt im Code die einzelenen Komponenten die wir ins Layout hauen "Views" heißen, wir aber zuvor "Editor" in "View" umbenannt haben, was jetzt bei Lea in der Thesis steht.
Das sorgt halt jetzt für Verwirrung.
Ich mein, mir kanns egal sein wie wir die jetzt im Endeffekt nennen, aber es sollte halt auch mit Lea's Thesis stimmen.

**Comment by JirkaDellOro** [comment]
Im aktuellen Konzept sind die Views tatsächlich noch ein winziges Bisschen kleinteiliger geworden. Ein ViewNode besteht aus einem Viewport und einem Tree und in der Regel einem ViewData. Der ViewData ist eigenständig aber standardmäßig Teil jedes Panels, die anderen Views dockt sich der Nutzer dazu bzw. werden beim Öffnen eines Presets standardmäßig automatisch angedockt. Gegenüber Leas Stand ist die Änderung lediglich, 
- dass ViewData als eigener View aufgefasst wird
- er nicht standardmäßig Teil anderer Views ist sondern eines Panels
- im Panel mit einer beliebigen Zahl beliebiger anderen Views kombiniert wird
- und es überhaupt Panels gibt.

**Comment by JirkaDellOro** [comment]
PopOut: ja, fällt raus. Tabs sind Teil des Plans, die Panels und die Views innerhalb der Panels sollen tab-bar sein. Beachte:
- Panels können nicht Teil anderer Panels sein, sie bilden eine hohe Hierarchieebene
- Darüber gibt es also nur den document.body bzw die oberst GoldenLayout-Instanz
- die Panels sind darin tab-bar
- Innerhalb der Panels nur Views. Diese sind festgelegt und können nur als Ganzes hinzugefügt oder entfernt werden.
- die Views sind innerhalb ihres Panels tab-bar, ggf innerhalb der View auch deren Komponenten

**Comment by AkikoOsaka** [comment]
Ah.
Das kam nicht wirklich raus aus den Logs (etc.).
Dann hab ich soweit keine Einwände

**Comment by JirkaDellOro** [comment]
Ja, mach' mal. Leider kann ich mit dem Begriff Stack in diesem Kontext nichts anfangen und daher deine Vorschläge nicht beurteilen. Derzeit ist GoldenLayout von einer Klassenvariable referenziert, also statisch und damit ebenso eine globale Instanz. Ich hatte die Frage formuliert, ob es möglich und sinnvoll ist, für jedes Panel eine Instanz anzulegen. Siehe meine allererste Prüfanweisung ganz oben. Bitte dringend meine Geschreibsel beachten, ich mach' mir viel Mühe damit.
