### ISSUE TITLE
define Events for interpanel-communication

### ISSUE THREAD

**Issue by Plagiatus** [JirkaDellOro/FUDGE#97]
Wir sind uns nicht ganz sicher, wie wir die Panel Events umsetzen sollen.  

Zuerst dachten wir, wir nutzen einfach standard `CustomEvent`s und packen unsere Informationen in deren `.detail` Eigenschaft. Allerdings scheint das doch eher unschön zu sein, da wir ja verschiedene Events mit verschiedenen Typen von Übergabeobjekten haben usw.  

Dann haben wir gedacht wir definieren unsere eigenen Events mit Attributen in denen wir alles mitgeben können was wir brauchen (z.B. den Objekttyp etc).

Inzwischen bin ich aber wieder der Meinung, dass es keinen Unterschied macht ob wir das selbst deifinieren oder das CustomEvent mit `detail` nutzen, da man dank `instanceof` ja den typen auch so herausbekommt. Jetzt sind wir uns nicht ganz sicher was die beste vorgehensweise hier wäre.

**Comment by JirkaDellOro** [comment]
Sofern die Lösung nicht gravierende Nachteile bringt, solltet ihr immer bereits existierende und standardisierte Implementationen nutzen. Und, genau wie Du beschreibst, kann man sicher schöne Interfaces kreieren, die sich intuitiv nutzen lassen. Auch sollte man bedenken, dass wir zu Standardverhalten keine Dokumentation schreiben müssen, die existiert bereits und wird von anderen (z.B. W3C, Mozilla) gepflegt. Und je dichter wir am Standard bleiben, um so leichter ist es für unsere User unsere System auch in eigenen Kontexten zu nutzen.

Klarer Fall.

**Comment by Plagiatus** [comment]
`CustomEvent` it is.
